### ISSUE TITLE
Gather and collate "best of" Teaching Kits for web literacy competencies

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#105]
This issue has been migrated from mozilla/teach.webmaker.org#404.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Wed Mar 25 2015 and had the following description:

> We need to search through a couple years worth of curricular resources made by the community and begin reworking content to serve as a “best in show” library. We may need to remix / rebuild the kits to update the content, make 'em pretty and remixable. 
> 
> Related resources can be found in mozilla/teach.webmaker.org#27 

On Wed Mar 25 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> So. Much. Stuff.
> https://teach.etherpad.mozilla.org/best-in-show
> https://webmaker.etherpad.mozilla.org/best-makes-call
> https://blog.webmaker.org/?s=community+literacies

On Thu Mar 26 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> This too - has some recent curation to narrow down 10 to feature on Teaching Activities page: https://teach.etherpad.mozilla.org/contentreview

On Mon Mar 30 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> depends on mozilla/teach.webmaker.org#27 

On Mon Mar 30 2015, [LucyeoH](https://api.github.com/users/LucyeoH) commented:

> Oh I have a list for this!! https://teach.etherpad.mozilla.org/BestTeachingKits **@****LauraHilliger** 

On Fri Apr 17 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> https://keyboardkat.makes.org/thimble/MTEzODQyNjExMg==/appmaker-for-educators-teaching-kit

On Tue Apr 21 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Here's another one from Global Kids (Hive NYC member) that's all about using littleBits to learn about design thinking, make simple circuits, and create a project based on a theme–in this case, disaster relief. 
> 
> https://jrubio.makes.org/thimble/Mjk3NTk5MjMy/make-change-with-little-bits
> 
> If we like it I can find out about getting photos or examples of things students made during a workshop they ran on this activity last fall.

**Comment by LauraHilliger** [comment]
closing in favor of: https://github.com/mozilla/learning-networks/issues/162
