### ISSUE TITLE
Kick-off call with Q2 testers

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#106]
This issue has been migrated from mozilla/teach.webmaker.org#456.

It was originally written by [thornet](https://api.github.com/users/thornet) on Mon Mar 30 2015 and had the following description:

> Goal: Have a kick-off call(s) with 200 Q2 testers. 
> 
> Agenda could include: 
> - Elements from Teach like Mozilla module to on-board. 
> - Option to test i) privacy module, ii) Webmaker app extension, or iii) Web Lit Basics.

**Comment by thornet** [comment]
In progress with the clubs curriculum fortnightly call. Closing. 

https://teach.etherpad.mozilla.org/club-calls
