### ISSUE TITLE
Design quarterly report template for RC's

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#11]
This issue has been migrated from mozilla/teach.webmaker.org#21.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> ## RACI
> - Phase: 
> - Owner: 
> - Decision Maker: 
> - Design Lead: 
> - Development Lead: 
> - Quality Verifier: 
> ## Deliverables
> - [ ] Standard reporting template that we request of RCs each quarter

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by amirad** [comment]
I'm going to close this since we discussed yesterday that the focus is on reporting for the CC's
