### ISSUE TITLE
Add remixable resources to activity pages

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#110]
This issue has been migrated from mozilla/teach.webmaker.org#602.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 07 2015 and had the following description:

> a few EDITABLE resources **@****thornet** received from Mouse. We should figure out how / where to link to these resources:
> 
> (kraken legitometer) https://docs.google.com/a/mozillafoundation.org/document/d/1bX7-G1rn-8BY5DNMIWHhS1utHoxcKi73RTmCuOL6CGU/edit#
> (kraken tip sheet): https://docs.google.com/a/mozillafoundation.org/document/d/1k4QHueV4a88L1X4-Qoji4lMhJ5TUrUioWvk7Uei0gtA/edit
> (ping utility tip sheet): https://docs.google.com/a/mozillafoundation.org/document/d/18qe8mdhb9lfheaz1tJw_mqC9hmLPPuGxUJZmL-CnnRk/edit

On Wed Apr 08 2015, [thornet](https://api.github.com/users/thornet) commented:

> And now their German localizations: 
> - Kraken legitometer: https://docs.google.com/a/mozillafoundation.org/document/d/1t6B06QR5Xd-wq-7i5vN-EHBtT00jy1aTmLJf-ifiGuk/edit
> - Kraken signs: https://docs.google.com/document/d/1sCXYEaFfoo7gCUord3Uxrx7Mr1E_DqUlQxvXNqz3DF4/edit?usp=sharing

**Comment by ldecoursy** [comment]
Closing, to be addressed as part of Curriculum Database work.
