### ISSUE TITLE
Close Hive Global Calls and fold into TTW Talks

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#112]
This issue has been migrated from mozilla/teach.webmaker.org#634.

It was originally written by [amirad](https://api.github.com/users/amirad) on Thu Apr 09 2015 and had the following description:

> Close Hive Global call in next meeting on April 16th. Transition over to TTW talks (add Hive global mailing list to monthly BSD emails). Start mapping Hive needs and potential Hive speakers for TTW talks.

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by simonaramkisson** [comment]
We can close, still trying to figure out when we will merge everything
