### ISSUE TITLE
Improve communication and sharing across local Hive calls

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#113]
This issue has been migrated from mozilla/teach.webmaker.org#635.

It was originally written by [amirad](https://api.github.com/users/amirad) on Thu Apr 09 2015 and had the following description:

> Simona to email Elsa, Julia, Lindsay, and Kari to see how far in advance these calls are planned and how we can share call/themes across cities and share information/tweets for social. \
> 
> Make sure all the hives have their calls in the calendar, and share it at the top of each of their monthly call pads for guests to see what else they can join this month. As well as share on social networks. 

On Fri Apr 10 2015, [simonaramkisson](https://api.github.com/users/simonaramkisson) commented:

> • Teams will begin adding me to invites so the calls/hangouts are in my calendar. I can share this information in office hours with new emerging communities
> • All teams are excited to have new cities join their calls especially if the content will be useful
> 
> Elsa: 
> • plans Hive Chicago call at least a week in advance, canvasses for speakers via member updates and Minigroup
> 
> Julia: 
> • plans calls a month in advance, the more time the better
> •

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?
