### ISSUE TITLE
Transactional Email: Sign up to Hive Learning Networks Mailing List

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#117]
This issue has been migrated from mozilla/teach.webmaker.org#639.

It was originally written by [amirad](https://api.github.com/users/amirad) on Thu Apr 09 2015 and had the following description:

> We need to update this email to include new information and a link to teach.mozilla.org (which is launching in the next heartbeat)
> CTA of email: Get information and access resources

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?
