### ISSUE TITLE
Conduct Train the Trainer in Whistler for RC's

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#12]
This issue has been migrated from mozilla/teach.webmaker.org#22.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> We'll invite RCs to Whistler, and will use the time to train them in the Teach Like Mozilla module so they can then go forth and train Club Leaders.
> ## RACI
> - Phase: 
> - Owner: 
> - Decision Maker: 
> - Design Lead: 
> - Development Lead: 
> - Quality Verifier: 
> ## Deliverables
> - [ ] Invite RCs to Whistler
> - [ ] Plan TTT
> - [ ] Prepare supplementary materials
> - [ ] Run the training!

**Comment by hannahkane** [comment]
Can we close this?

**Comment by amirad** [comment]
Outdated.
