### ISSUE TITLE
Write final report on Maker Party grant

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#124]
This issue has been migrated from mozilla/teach.webmaker.org#662.

It was originally written by [amirad](https://api.github.com/users/amirad) on Fri Apr 10 2015 and had the following description:

> We need to write a final report for the Maker Party grant. I've sent an email to Angela to get templates of previous reports for us to use as a base. 
> 
> **@****chrislarry33** can you provide more info on what needs to be included?
> cc: **@****edrushka** **@****ldecoursy**

**Comment by amirad** [comment]
Finished and sent to NWP
Available here: https://drive.google.com/folderview?id=0B5CSa8l3sstMfm92RUZjOHQ5YXdnLTlIaUdvS3V6TktaR3pvamMwMHBPc3RNYzgxN2FSRGM&usp=sharing
