### ISSUE TITLE
Write Club Leader on-boarding and guidelines with RCs

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#13]
This issue has been migrated from mozilla/teach.webmaker.org#23.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> ## RACI
> - Phase: 
> - Owner: 
> - Decision Maker: 
> - Design Lead: 
> - Development Lead: 
> - Quality Verifier: 
> ## Deliverables
> - [ ] TBD, but should end with RCs beginning to onboard new Club Leaders

On Tue Apr 14 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> we talked about this a little in our sustaining engagement call. Have scoped some things in the Teach Like Mozilla content (italics are topics scoped for TLM), and have noted:
> ### Your 1st Month as a Regional Coordinator
> - (_Finding your Crew, Working Openly, Open Tools_) Focus in on Recruitment. Kickoff meetings. Protocols & patterns for coordinating clubs. How to connect with RCs and regions (video bridge / cross-region comms & connection)
> - (_Sharing/Storytelling_) Talking points for how a club will add value to your club captain. 
> - (_Sharing/Storytelling_) How to tell the story of the clubs so that the club captain can tell the story. 
> - Includes regional case studies (i.e. Rio LAN houses, Chicago public schools)
> ### Your 1st Month as a Club Captain
> - (_Remixing for Context_) How to set up your club or embed it in your existing program
> - First 16hr of curriculum
> - How to get help and connect with other clubs and your coordinator
> - (_Sharing/Storytelling_) How to attract the public. 
> - (_Sharing/Storytelling_) How to tell the story of the clubs so that the participants can tell the story.

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by amirad** [comment]
We have the 1st month as CC guide and there is another ticket for 1st month as RC guide so closing this.
