### ISSUE TITLE
Draft minor policy for website

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#133]
This issue has been migrated from mozilla/teach.webmaker.org#730.

It was originally written by [thornet](https://api.github.com/users/thornet) on Mon Apr 20 2015 and had the following description:

> With legal team, review our options around age-related pieces of the site. Learn from how other orgs deal with this. Prepare and publish our own minor policy before June.

**Comment by hannahkane** [comment]
Removing from May 8 milestone, since that's passed. Can we close this or add to an upcoming heartbeat? Sorry I'm just c/p'ing this boring comment everywhere! :)

**Comment by ldecoursy** [comment]
@hannahkane think we're covered here with the updated TOS?

**Comment by ldecoursy** [comment]
This is covered by TOS, closing.
