### ISSUE TITLE
Create TLM "recruitment template"

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#134]
This issue has been migrated from mozilla/teach.webmaker.org#731.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Mon Apr 20 2015 and had the following description:

> For _Your first Month as a Club Captain/Regional Coordinator_, there's an action for people to "recruit". In one instance for club leaders, and in another for learners. We should provide a spreadsheet that they can remix to help them track of who they talk to and outcomes. 
> 
> I'd imagine we have good and better spreadsheets to remix for this purpose. Got something low bar and suitable Mobilizers? **@****amirad** **@****Saallen** **@****simonaramkisson** **@****ldecoursy** **@****Elsamozilla**

On Mon Apr 20 2015, [thornet](https://api.github.com/users/thornet) commented:

> cc **@****soapdog** who's prototyping some of our RC materials. He might have a document for tracking recruitment. 
> 
> Also **@****ldecoursy** and **@****adamlofting** were helping with some activity tracking spreadsheets.

**Comment by LauraHilliger** [comment]
@soapdog do you happen to have a spreadsheet you're using to track potential club captians/partners/etc? I'd like to remix something you're using for teach like mozilla curriculum as it will be more applicable to people working locally.

**Comment by soapdog** [comment]
We don't have a template here. We're a special case where we're working with LAN House  owners. We're playing captain here while we train everyone. There is no spreadsheet yet but I will think of one and collaborate here.
