### ISSUE TITLE
Collect Maker Party case studies for site

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#137]
This issue has been migrated from mozilla/teach.webmaker.org#743.

It was originally written by [hannahkane](https://api.github.com/users/hannahkane) on Mon Apr 20 2015 and had the following description:

> In order to help scaffold the Maker Party experience for potential hosts, we want to showcase a few typical Maker Party styles. Case studies might include photos, basic information (# of attendees, age range of attendees, budget, etc.), and stories/lessons from the hosts.
> 
> The case studies should reflect the different types/formats of common Maker Parties.

On Mon Apr 20 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> cc **@****amirad** - What do you think about this? Does this already exist? Would you be up for collecting these case studies?

On Thu Apr 23 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> **@****amirad** - are you okay with me putting this into the next heartbeat and assigning to you?

On Thu Apr 23 2015, [amirad](https://api.github.com/users/amirad) commented:

> Sure. I have a lot of this info already in different places. I can collect and share. 

On Thu Apr 30 2015, [amirad](https://api.github.com/users/amirad) commented:

> Created a pad filled with past events: https://teach.etherpad.mozilla.org/MPcasestudies
> It's broken down into my 2014 favs, other 2014 stories and some 2013 stories. I can maybe dig up more from each depending on which ones you like. 

On Thu Apr 30 2015, [amirad](https://api.github.com/users/amirad) commented:

> **@****hannahkane** let me know if that's usable ^

**Comment by hannahkane** [comment]
What about featuring these three? I think they represent the diversity of Maker Party experiences in terms of location, setting, participants, and activities.

Net Neutrality Maker Party 
Hosted by: David, a community member
Location: a private home in Barcelona, Spain
Participants: David and his family
Activities: participants learned about the importance of Net Neutrality, and considered how to take action. They used Thimble to create Net Neutrality-themed memes.
Photo: http://bit.ly/1srXfUk

Kids Maker Party
Hosted by: the Mozilla Community of Bhopal
Location: a public school in Itarsi, India
Participants: (do we know how many?) 9th and 10th graders
Activities: For the first Maker Party in Itarsi, the Mozilla Bhopal community celebrated international friendship day by learning how to create for the web using Thimble and X-Ray Goggles with high school students in the local community.
Photo: https://www.flickr.com/photos/64132560@N07/14816744494/in/album-72157646148674844/ (or another from that album) - WILL NEED PERMISSION

Pittsburgh Second Annual Maker Party
Hosted by: The Sprout Fund
Location: an art gallery/studio in Pittsburgh, United States
Participants: hundreds of young people
Activities: The  event featured making stations where participants created DIY Pop Art screen prints, made seed bombs for secret gardens, hacked the New York Times webpage with X-Ray Goggles, and more.
Photo: [can we get a photo from the Sprout Fund?]

**Comment by hannahkane** [comment]
@amirad @ldecoursy @chrislarry33  Please see the above for a suggestion of what content to feature on the /events page to help provide context for MP.

The relevant design ticket is https://github.com/mozilla/teach.webmaker.org/issues/843

**Comment by ldecoursy** [comment]
@amirad Do we have a good MP case study for something using HTML puzzle boxes? I know there are great photos and I like that it's lo-fi/no-fi but still clearly web literacy. 

I might also suggest swapping the Digital Corps option with this one:
Digital Harbor Make and Remake Hackathon - August 22nd, Baltimore
At  the Make and Remake Hackathon Day attendees spent the first half of  the  day using Webmaker tools to MAKE something awesome. In the second  half  of the Hackathon individuals then turned their completed makes  over to a  friend so they could then REMAKE their make to create  something new.  You can see what was made and remade on the event page http://mzl.la/1tFx6TZ and see more pictures http://bit.ly/1viGr76. 

I like the idea of the Net Neutrality kitchen table event, but not sure about those photos. 

I'm nitpicking - I do like @hannahkane's suggestions - @amirad ultimately up to you :)

**Comment by chrislarry33** [comment]
+1 swapping digital harbor in for digital corp

**Comment by amirad** [comment]
Yup, digital harbor case is way stronger. 
I personally like the NN kitchen party pictures. 1) shows an older audience when most of our stuff on the site perceives to be only youth and 2) is a not-so-fancy case study which makes it more real and replicable to people. 

I would take out the kids MP since all three of the case studies are laptop based and we can show something a little more offline and makey. What about one of the digital ready MP's in NYC? https://www.flickr.com/photos/newyouthcity/sets/72157644495371568 http://digitalready.net/event/digital-ready-maker-party/  http://technical.ly/brooklyn/2014/08/18/watch-video-recap-digital-readys-maker-party/

Or another offline makey one from India? If we like the HTML puzzle box ones we can ask Yofie but I do know there was the Maker Party in the park one in Indonesia https://michelle.makes.org/thimble/LTI5Mjk0MzM2/webmaker-in-the-park

**Comment by ldecoursy** [comment]
OK - let's do this:

Net Neutrality Maker Party
Hosted by: David, a community member
Location: a private home in Barcelona, Spain
Participants: David and his family
Activities: participants learned about the importance of Net Neutrality, and considered how to take action. They used Thimble to create Net Neutrality-themed memes.
Photo: http://bit.ly/1srXfUk

Make and Remake Hackathon 
Hosted by: Digital Harbor, local community organization
Location: Makerspace in Baltimore, MD
Participants: 20 teens
Activities: At the Make and Remake Hackathon Day attendees spent the first half of the day using Webmaker tools to MAKE something awesome. In the second half of the Hackathon individuals then turned their completed makes over to a friend so they could then REMAKE their make to create something new. 
Photos: http://mzl.la/1tFx6TZ and http://bit.ly/1viGr76

Lo-Fi Maker Party
Hosted by: Mozilla Indonesia
Location: Park in Jakarta, Indonesia
Participants:
Activities: At this Lo-Fi Maker Party, participants used paper, Post-it's and tennis balls to learn basic HTML and website structure, simple programming commands and app design. 
Photos: https://michelle.makes.org/thimble/LTI5Mjk0MzM2/webmaker-in-the-park and more here: https://www.flickr.com/photos/yofiesetiawan/sets/72157647044545045

**Comment by ldecoursy** [comment]
@amirad Can we close this?
