### ISSUE TITLE
Check in with RCs at end of Q2 to plan for Q3

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#14]
This issue has been migrated from mozilla/teach.webmaker.org#24.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> ## RACI
> - Phase: Review
> - Owner: **@****thornet**
> - Quality Verifier: **@****chrislarry33** 
> ## Deliverables
> - [ ] 1:1s with R.C. to review organizing model
> - [ ] Document needs and iterations on model for Q3

**Comment by hannahkane** [comment]
Taking this out of the June 19th milestone, so we can close the milestone. Feel free to add to another milestone if needed.

**Comment by amirad** [comment]
Outdated
