### ISSUE TITLE
[META] Produce "Your First Month as a Regional Coordinator" Guide [TLM]

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#143]
This issue has been migrated from mozilla/teach.webmaker.org#755.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> **_Learning outcome for this content**_: Have a set of activities remixed to your specific topic area, location and learner interests that embed web literacy.
> - [x] Produce TLM "Finding your Crew" module mozilla/teach.webmaker.org#751
> - [x] Produce TLM "Reflecting Openly" module mozilla/teach.webmaker.org#752 
> - [x] Template an etherpad and discourse thread for coordinating clubs mozilla/teach.webmaker.org#802 
> - [x] Produce TLM "Open Tools" module mozilla/teach.webmaker.org#753
> - [ ] Produce Recruitment template mozilla/teach.webmaker.org#731 
> - [x] Produce TLM "Sharing and Storytelling" module mozilla/teach.webmaker.org#754
> - [x] Produce TLM "Remixing for Context" module mozilla/teach.webmaker.org#757
> - [ ] Produce Case Studies documentation  (i.e. Rio LAN houses, Chicago public schools)#756
> - [x] Design scalable solution for Web Lit Curriculum on Teach site mozilla/teach.webmaker.org#457
> - [x] Template a letter from the future mozilla/teach.webmaker.org#837 
> 
> **_Content Folder**_ https://drive.google.com/drive/u/1/#folders/0B0u8434q8_LPNTJlejh4YWhWRkk/0B0u8434q8_LPfkVzUlRuMVZ4MmxIb0dKc01ueEs3MW9uREFUb2RYdWJKeEFTcGRYX2ppM1U

On Wed Apr 22 2015, [thornet](https://api.github.com/users/thornet) commented:

> Adding the May 8 milestone since we'll have the RC kickoff call on May 5. 

On Tue Apr 28 2015, [thornet](https://api.github.com/users/thornet) commented:

> Latest version: https://docs.google.com/document/d/1f7r94MfAXyaNgLoFWINjenx6MQYVJTSjCqMzTJTFqBY/edit#

**Comment by LauraHilliger** [comment]
still more linking to do, once other issues are completed, but I put together a prettier page for this: http://mozilla.github.io/webmaker-curriculum/Experiments/StartHere/1stmonthRC.html

**Comment by hannahkane** [comment]
Removing from May 8 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by amirad** [comment]
Closing. Most of this should be covered in @Carotejada's RC training guides.
