### ISSUE TITLE
Produce 3 -5 Case Studies on Clubs

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#144]
This issue has been migrated from mozilla/teach.webmaker.org#756.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> We need a snazzy reportage on clubs that currently exist in our network. Rio LAN houses, Chicago public schools, individual contributor clubs – profiling pre-existing clubs will help new RCs and CCs imagine clubs for themselves. Suggest Research Report / Final Report like look and feel.
> 
> Resource will be used in "Your First Month" modules mozilla/teach.webmaker.org#755

On Wed Apr 22 2015, [thornet](https://api.github.com/users/thornet) commented:

> Let's list the elements we think these case studies should have: 
> - Target participants
> - Relationship of club captain to participants
> - Learning goals of club
> - Location
> - Setting (i.e. library, school, makerspace)
> - Meeting frequency
> - Favorite activities

On Wed Apr 22 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> I would add:
> 
> History
> Motivation
> 
> This case study should profile both RCs and CCs (we'll need to be able to separate those pieces for mozilla/teach.webmaker.org#755 and mozilla/teach.webmaker.org#758 )

On Wed Apr 22 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> I will work on a model example for the formal higher ed school setting
> later today. Maybe we can get **@****chadsansing** to do one for K12 setting.
> 
> On Wed, Apr 22, 2015, 6:28 AM Laura Hilliger notifications@github.com
> wrote:
> 
> > I would add:
> > 
> > History
> > Motivation
> > 
> > This case study should profile both RCs and CCs (we'll need to be able to
> > separate those pieces for mozilla/teach.webmaker.org#755
> > https://github.com/mozilla/teach.webmaker.org/issues/755 and mozilla/teach.webmaker.org#758
> > https://github.com/mozilla/teach.webmaker.org/issues/758 )
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/teach.webmaker.org/issues/756#issuecomment-95122182
> > .

On Thu Apr 23 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> I'd add that it would be great to collect photos for each of the case studies! Also, I'd love to include a super pared down version on the Clubs section of the site.

On Thu Apr 23 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> Here is my quick example:
> http://jgregorymcverry.com/how-i-forked-mozilla-web-clubs-for-a-formal-educational-setting/
> 
> Wish I had pictures but I didn't do media releases.
> 
> On Thu, Apr 23, 2015 at 6:45 PM hannahkane notifications@github.com wrote:
> 
> > I'd add that it would be great to collect photos for each of the case
> > studies! Also, I'd love to include a super pared down version on the Clubs
> > section of the site.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/teach.webmaker.org/issues/756#issuecomment-95737758
> > .

On Fri Apr 24 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****jgmac1106** this is excellent. Full on excellent. I think we should stick with the personal voice (e.g. have the case studies produced by club leaders/coordinators, and then edit as opposed to "official" reporting style). Greg, would you be ok with us using your language and remixing into something (read on)?
> 
> I think these stories would work well as 1 page infosheets. Something like this:
> ![club-report-idea](https://cloud.githubusercontent.com/assets/539017/7318209/985d1126-ea89-11e4-8477-c30ad7bebbd2.png)
> 
> but with the club map, look and feel of teach [dot]... 
> 
> What do you all think?

On Fri Apr 24 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> Everything I do is licensed for remix. Feel free to do anything. I am going
> to go in and fix some grammar. It was late and I too often publish then
> proofread.
> 
> On Fri, Apr 24, 2015, 7:57 AM Laura Hilliger notifications@github.com
> wrote:
> 
> > **@****jgmac1106** https://github.com/jgmac1106 this is excellent. Full on
> > excellent. I think we should stick with the personal voice (e.g. have the
> > case studies produced by club leaders/coordinators, and then edit as
> > opposed to "official" reporting style). Greg, would you be ok with us using
> > your language and remixing into something (read on)?
> > 
> > I think these stories would work well as 1 page infosheets. Something like
> > this:
> > [image: club-report-idea]
> > https://cloud.githubusercontent.com/assets/539017/7318209/985d1126-ea89-11e4-8477-c30ad7bebbd2.png
> > 
> > but with the club map, look and feel of teach [dot]...
> > 
> > What do you all think?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/teach.webmaker.org/issues/756#issuecomment-95908744
> > .

On Fri Apr 24 2015, [thornet](https://api.github.com/users/thornet) commented:

> **@****jgmac1106** <3! Great post, and your learner portfolios are brilliant. Such an inspiration. Would you be up for sharing your case study in the next club call on May 5?

On Fri Apr 24 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> If I am available for the call.
> 
> On Fri, Apr 24, 2015, 11:23 AM Michelle Thorne notifications@github.com
> wrote:
> 
> > **@****jgmac1106** https://github.com/jgmac1106 <3! Great post, and your
> > learner portfolios are brilliant. Such an inspiration. Would you be up for
> > sharing your case study in the next club call on May 5?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/teach.webmaker.org/issues/756#issuecomment-95965298
> > .

**Comment by LauraHilliger** [comment]
I've spent some time trying to make these short and snappy. There are 3 in the pad based on what @jgmac1106 @omnignorant and @emmairwin added in our recent call. @jgmac1006's looks pretty tight IMHO:

Greg - could you check and see if you like the remix?
Robert - could you check what I wrote for you, add/subtract and include your motivation?
Emma - same as Robert?

https://teach.etherpad.mozilla.org/club-casestudies

Once these are tighter, we can start talking about how they should be incorporated into #146
cc @soapdog @thornet @amirad

**Comment by thornet** [comment]
This should be synced up with the case studies/skins being produced in @ldecoursy's working group. See: https://teach.etherpad.mozilla.org/clubspartners

**Comment by hannahkane** [comment]
Taking this out of the May 22 milestone, so we can close the milestone.

**Comment by amirad** [comment]
This is being scoped elsewhere so will close this ticket.
