### ISSUE TITLE
[TLM] Produce "Remixing for Context" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#145]
This issue has been migrated from mozilla/teach.webmaker.org#757.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> (empty) doc for this module: https://docs.google.com/document/d/1q5p1ID6CyMomfs_S5uf7Jki_agWWQQMUs8HfN97zBv0/edit
> 
> Other relevant content:
> http://mozillascience.github.io/instructorTraining/designAndAdaptation/index.html
> https://github.com/mozilla/school-of-webmaking/issues/240
> https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Webmaker-Club-activities
> http://www.zythepsary.com/techie/prove-that-people-want-to-remix-curriculum/
> https://wiki.mozilla.org/Hackasaurus/FAQ

**Comment by LauraHilliger** [comment]
no longer empty: https://docs.google.com/document/d/1q5p1ID6CyMomfs_S5uf7Jki_agWWQQMUs8HfN97zBv0/edit#

feel free to add comments in the Doc. We'll file a new issue with any future specifications
