### ISSUE TITLE
[META] Produce "Your First Month as a Club Captain" Guide [TLM]

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#146]
This issue has been migrated from mozilla/teach.webmaker.org#758.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> _**Depends on mozilla/teach.webmaker.org#755 *_*
> 
> Includes: 
> - [x] TLM Working Openly mozilla/teach.webmaker.org#752 
> - [x] TLM Open Tools mozilla/teach.webmaker.org#753 
> - [x] TLM Remixing for Context mozilla/teach.webmaker.org#757 
> - [ ] Clubs Curriculum User Guide including first 16hr of curriculum
> - [x] TLM Sharing/Storytelling mozilla/teach.webmaker.org#754 
> - [x] TLM Facilitating mozilla/teach.webmaker.org#763 
> - [ ] Case Studies of real-life Club Captains mozilla/teach.webmaker.org#756 
> - [ ] TLM Finding Cohesion & Collaboration mozilla/teach.webmaker.org#765 
> 
> Have updated this issue based on the April 21st Club Call. There may be other TLM modules (e.g. Making is Learning mozilla/teach.webmaker.org#760 or mozilla/teach.webmaker.org#761 ) that are part of this pathway 

On Fri Apr 24 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Not sure where this might fit best, but worth checking out Open Science handbook if you haven't yet to see where some of this might inform process of starting a club... http://mozillascience.github.io/studyGroupHandbook/

**Comment by LauraHilliger** [comment]
started a doc here @thornet https://docs.google.com/document/d/17hK0NoPN61C_VLxEj-ZLQ6ZzQ2CFSQ6ehLxEvhmCBx4/edit 

Was very helpful to cowork on the RC Guide, let's do that again!!

**Comment by LauraHilliger** [comment]
@amirad @thornet @ldecoursy - thoughts on this document? Is there a club captain guide happening elsewhere?

**Comment by amirad** [comment]
Not that I know of, but here's Dorine's on-boarding guide that might be helpful https://drive.google.com/folderview?id=0B8Id3JjcsjfJflpzVElJWHJQUU03U0EzenNwOXdBM3ctdVBoYXpjQnFzNFlUZmZENllacHM&usp=sharing @LauraHilliger

**Comment by amirad** [comment]
COmpleted http://soapdog.github.io/your-first-month-as-a-club-captain-guide/
