### ISSUE TITLE
[TLM] Produce "Making is Learning" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#147]
This issue has been migrated from mozilla/teach.webmaker.org#760.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> Doc for this module: https://docs.google.com/document/d/1TgnkR64WfRPn0ICJyZ7L4DP236vqeCYj_8rh6d3gpdE/edit#heading=h.j9411nx9ut08
> 
> Needs images and example “make”, reword “makes” as “activity or projects, make them tool agnostic, Connected Learning section needs review from Hivers, review “makes”, add examples and resources

**Comment by LauraHilliger** [comment]
http://laurahilliger.gitbooks.io/teach-like-mozilla/content/teaching_learning/en/making.html
