### ISSUE TITLE
[TLM] Produce "Facilitating" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#149]
This issue has been migrated from mozilla/teach.webmaker.org#763.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> Doc: https://docs.google.com/document/d/1IjdRKaQ7ctHGAPzx2BzxQXlpg8YCYNRUB2XwQ0DkzfQ/edit#
> 
> Other relevant content:
> http://mozillascience.github.io/instructorTraining/compellingInstruction/index.html (includes metacog)
> https://training.webmakerprototypes.org/en/host-a-training/ training agendas may need remix

On Wed Apr 22 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> This may also be helpful, from Digital Corps: https://www.scribd.com/fullscreen/241612718?access_key=key-Bg478gqESrAGRd9vGINd&allow_share=false&escape=false&show_recommendations=false&view_mode=scroll  
> 
> And this: https://theanimal.makes.org/thimble/MTYzMzIyMjkxMg==/facilitating-digital-corps-workshops
> 
> Both found here: http://rldc.weebly.com/teaching-kits.html

**Comment by amirad** [comment]
@chadsansing  can you review if this fits into your current TLM plans and if any of the links are helpful for you before closing?

**Comment by chadsansing** [comment]
Closing. Waiting on the ongoing Leadership Dev work to reboot TLM process/products.
