### ISSUE TITLE
[TLM] Produce "Encouraging Diversity" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#150]
This issue has been migrated from mozilla/teach.webmaker.org#764.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> doc for this module: https://docs.google.com/document/d/1ltx2AJV8uwoFY6ihukz-4zC7LuUmQAo2eVRsyML66HA/edit
> 
> content to inspire/remix:
> http://www.omnignorant.com/2014/09/cultivating-diversity-networked-digital-age/
> http://ascendproject.org/

**Comment by LauraHilliger** [comment]
http://laurahilliger.gitbooks.io/teach-like-mozilla/content/teaching_learning/en/diversity.html
