### ISSUE TITLE
[TLM] Produce "Finding Cohesion & Collaboration" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#151]
This issue has been migrated from mozilla/teach.webmaker.org#765.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> doc for this module: https://docs.google.com/document/d/1BBQWj-cYrbkzbnKE_80NwtUz9jZO6Iivl84d4-9b3as/edit#
> 
> other relevant content:
> https://wiki.mozilla.org/Webmaker/HiveCookbook
> http://hivechicago.org/working-open-hive-chicago-style/
>  http://hivechicago.org/moonshots/moonshot-working-groups/
> https://juliahivenyc.makes.org/thimble/hive-nyc-cohort-guide

**Comment by ldecoursy** [comment]
No longer in the curriculum queue.
