### ISSUE TITLE
[TLM] Produce "Web Literacy" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#152]
This issue has been migrated from mozilla/teach.webmaker.org#766.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> doc for this module: https://docs.google.com/document/d/1GT1iJ5HVS2c7yov4YldvcBXj1oKIY6c247xmeCYPimU/edit#
> 
> needs tightening, edits on teaching kit references, new projects, fleshed out thinking, reduce web literacy map references
> 
> Other relevant content:
> http://mozillascience.github.io/instructorTraining/designAndAdaptation/index.html
> http://akenygren.tumblr.com/mymakerboxes

**Comment by LauraHilliger** [comment]
http://laurahilliger.gitbooks.io/teach-like-mozilla/content/teaching_learning/en/webliteracy.html
