### ISSUE TITLE
[TLM] Produce "Design Thinking" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#153]
This issue has been migrated from mozilla/teach.webmaker.org#767.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> doc for this module: https://docs.google.com/document/d/1IhNSm6faR_2jVFcgBlZZLp3VnhbYaOb6D51mcHDQW0c/edit#

**Comment by amirad** [comment]
I'll take this doc and list it as a WIP clubs guide but going to close this ticket since it's super outdated.
