### ISSUE TITLE
[TLM] Produce "Finding Funding and Support" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#154]
This issue has been migrated from mozilla/teach.webmaker.org#768.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> (empty) doc for this module: https://docs.google.com/document/d/1pNlGBncjcubxvpJonSjytA8Vt9SekylaoL6md-BXY-0/edit
> 
> Need learning objectives.
> 
> Relevant content:
> (project briefs, local partnerships, grant writing – need to make determinations of how much of this is DIY doable)
> https://wiki.mozilla.org/Webmaker/HiveCookbook
> Geoffrey’s blog / fundraising team might have some basic tips and tricks

**Comment by ldecoursy** [comment]
No loner in the curriculum queue.
