### ISSUE TITLE
[TLM] Produce "Playtesting and Iteration" module

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#155]
This issue has been migrated from mozilla/teach.webmaker.org#769.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Apr 21 2015 and had the following description:

> doc for this module: https://docs.google.com/document/d/18SlaxsmMKyDZePyzNMKBWPh8ZM6s-8bgbrOONH619rA/edit#
> 
> needs tightening, rearranging and new projects
> 
> Relevant content: 
> http://mozillascience.github.io/instructorTraining/feedback/index.html (loads of good content to build out this module.)

**Comment by amirad** [comment]
@chadsansing  can you review if this fits into your current TLM plans and if any of the links are helpful for you before closing?

**Comment by chadsansing** [comment]
Closing. Waiting on the ongoing Leadership Dev work to reboot TLM process/products.
