### ISSUE TITLE
Contact Q2 Privacy curriculum testers

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#156]
This issue has been migrated from mozilla/teach.webmaker.org#783.

It was originally written by [thornet](https://api.github.com/users/thornet) on Wed Apr 22 2015 and had the following description:

> - [ ] Make list of orgs and people to invite to testing 
> - [ ] Invite to fortnightly calls 
> 
> Ideas: 
> - EFF
> - Advocacy (Melissa)
> - Privacy (Stacy)
> - Leah
> - many more

**Comment by hannahkane** [comment]
Can we close this?
