### ISSUE TITLE
Template a "Letter from the Future" for RC Guide

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#160]
This issue has been migrated from mozilla/teach.webmaker.org#837.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Wed Apr 29 2015 and had the following description:

> We need to write an example letter to ourselves from 2018 on what Mozilla Clubs look like in our region. 
> 
> Describe what it looks like if Mozilla Clubs grew in your region. What inspires you about it? How would you have gotten there? What are the challenges?

On Wed Apr 29 2015, [thornet](https://api.github.com/users/thornet) commented:

> cc **@****soapdog** who's taking a first stab.

**Comment by LauraHilliger** [comment]
we added a new category to Discourse for these templates: http://discourse.webmaker.org/category/clubs/stories

**Comment by LauraHilliger** [comment]
YAY! Modeled by several in the community including a template:

http://discourse.webmaker.org/t/blog-post-via-a-2018-email-reflections-of-a-journey-traveled/1399/2
