### ISSUE TITLE
Update design collateral for Maker Party

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#163]
@amirad can you please add links to the design assets from last year that we need to update for this year?
- Save the date
- images for social media shares
- anything else?

My understanding is that we are simply changing the dates and photos, but can take a closer look once we have the assets in one place.

**Comment by amirad** [comment]
![join maker party](https://cloud.githubusercontent.com/assets/10170768/7519984/92a2b15a-f4b1-11e4-8a39-560d159299c6.jpg)

![maker party](https://cloud.githubusercontent.com/assets/10170768/7519987/99060c54-f4b1-11e4-9cdc-0ebab9f375da.png)

![save the date](https://cloud.githubusercontent.com/assets/10170768/7519997/a4c527dc-f4b1-11e4-983a-16d6b6705dce.png)

**Comment by amirad** [comment]
@sabrinang created this last year and has the original files

**Comment by hannahkane** [comment]
Intentionally duped this in platform repo so that we can account for it in our heartbeat planning. https://github.com/mozilla/teach.webmaker.org/issues/869

**Comment by ldecoursy** [comment]
@sabrinang rocked it - closing this ticket (also closed in teach.webmaker.org repo)
