### ISSUE TITLE
Plan MoCo channel support for MP

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#164]
Detail opportunities and plans for MoCo support for Maker Party this year

@amirad to update following initial conversation with MJ

**Comment by amirad** [comment]
Meet with MJ last week on getting her help in sharing MP this year. She's all teed up to share Save the Date info now and in June. And do a big push for MP in July. Also, she's going to do a feature in Firefox and You newsletter in July. @KevZawacki will coordinate sending the right content and images. 

Also talking to @HPaulJohnson about whether we want to do a snippet this year
Also talking to Sean Bohan about doing titles that push to MP page.

**Comment by HPaulJohnson** [comment]
@amirad, @KevZawacki  and I met Friday to develop a final list of deliverables: 

https://docs.google.com/spreadsheets/d/1JCWWQw4eTU8ZR6tQjEDgoKfoFBVq8Y90VH5B5-IUfhQ/edit#gid=0

This includes both MoFo and MoCo supported channels. If we need to create separate issues for each let me know, or we can manage progress on all here.

**Comment by ldecoursy** [comment]
@HPaulJohnson Looks good - don't think we need separate tickets, unless you need others to weigh in with feedback/approvals.

**Comment by amirad** [comment]
@KevZawacki has done this and tracking efforts
