### ISSUE TITLE
Send MP Save the Date email and begin social media promo

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#166]
Send MP Save the Date email. 

Deploy through:
[ ] Maker Party BSD
[ ] Mentor BSD
[ ] Webmaker BSD
[ ] List Adam created in Q1?
[ ] Social
[ ] Partner
[ ] Listserv
[ ] Blog 
[ ] Hive Minigroups 

cc @kevzawacki @HPaulJohnson

**Comment by ldecoursy** [comment]
Dependent on #163

**Comment by HPaulJohnson** [comment]
Starting on copy this week and will have @KevinZawacki polish when he gets back next week. 

Is there a MP specific email template we can use?

**Comment by amirad** [comment]
MP template in BSD. 

We can work off copy from last year that I sent in the last call https://teach.etherpad.mozilla.org/MPlaunchemails

**Comment by KevZawacki** [comment]
Hi all,

Proposed Save the Date copy here: https://docs.google.com/document/d/14v7qIq_WZqDQjQK3VI4wXPUsBO5DrjBaqLaIgsHLZJU/edit

Comment away!

**Comment by HPaulJohnson** [comment]
Nice, @KevZawacki - left comments in the pad. Overall it's good but could stand to be shorter.

**Comment by KevZawacki** [comment]
- @hannahkane 

Thanks for the feedback, all! I've updated accordingly.

The latest version is here: https://docs.google.com/document/d/14v7qIq_WZqDQjQK3VI4wXPUsBO5DrjBaqLaIgsHLZJU/edit

Once @amirad weighs in, we'll be ready to email it out on May 21.

**Comment by ldecoursy** [comment]
Thanks a million, @KevZawacki! I left a few comments too. 

@chrislarry33 may also want to take a peek.

**Comment by amirad** [comment]
Edited this one after the internal email and blog post so would suggest looking there first and then updating this text. Biggest thing to point out is the narrative that we decided on: we should encourage people to run Maker Party events throughout the year but to come celebrate their work during July 15-31. This means that MP doesn't end and it's a celebration of the hard work the community has been doing during the year to teach the web. Mozilla Clubs is an evolution of MP from people doing one off events to on-going events to teach.

**Comment by KevZawacki** [comment]
Resurfacing to see if anyone has last-minute edits before we distribute on Thursday. 

https://docs.google.com/document/d/14v7qIq_WZqDQjQK3VI4wXPUsBO5DrjBaqLaIgsHLZJU/edit

**Comment by HPaulJohnson** [comment]
Email sent!
