### ISSUE TITLE
Update MP Comms Timeline and Messaging

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#167]
Need to update the timeline and messaging here: https://docs.google.com/document/d/1-XY8Q8Hr4tEdNbRxBUmEAK4nk2ZTdL_XWVQPTgT5rOg/edit

Also identify any specific needs or materials that we can ticket.

@kevzawacki @HPaulJohnson @amirad

**Comment by ldecoursy** [comment]
Pre Maker Party comms also being tracked here: https://github.com/MozillaFoundation/plan/issues/446

**Comment by HPaulJohnson** [comment]
I updated timeline in comms doc. Short-term deliverables: 
- Blog post, internal email and update on project call on 5/18. @KevinZawacki and I will put together messaging for this next week. 
- Save the date email and social promotion on 5/21.
- All other dates stay the same.

**Comment by ldecoursy** [comment]
Save the date being tracked here: https://github.com/mozilla/learning-networks/issues/166

**Comment by KevZawacki** [comment]
Blog post & internal email ready for review here: https://docs.google.com/document/d/1w9SkQfOE55lPfMOmtgAa9g8NQKCK97tmVr4poJvO4KY/edit

**Comment by HPaulJohnson** [comment]
Comments added to doc.

**Comment by ldecoursy** [comment]
I added a few too, thanks so much @KevZawacki 
@amirad should review, and @chrislarry33 too

cc @thornet re: references to Clubs - think we can pull some copy from the updated fact sheet.

**Comment by amirad** [comment]
Added lots of notes!

**Comment by KevZawacki** [comment]
Thanks for the edits, everyone. We're in great shape for Monday.
Amira can send the internal email shortly after the 2 p.m. ET all-hands call.
Any preference as to what time we post the blog?

**Comment by KevZawacki** [comment]
& if anyone wants to take a final look and add edits: https://docs.google.com/document/d/1w9SkQfOE55lPfMOmtgAa9g8NQKCK97tmVr4poJvO4KY/edit

**Comment by chrislarry33** [comment]
Looks great @amirad @HPaulJohnson @ldecoursy @KevZawacki Thanks for the work

**Comment by KevZawacki** [comment]
Thanks, all! Closing out this ticket. 

Next up: Maker Party Save the Date email, slated for Thursday, May 21. See ticket #166
