### ISSUE TITLE
Finalize and package three activities for Maker Party

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#169]
## RACI
- Owner: @amirad 
- Decision Maker: @chrislarry33 
- Consulted: @ldecoursy @thornet @hannahkane 
- Design: TBD when links/copy are finalized

Instead of featuring just one Mozilla Clubs activity for Maker Party, we'd like to offer three. This enables us to incorporate a Webmaker-app specific project (that would otherwise be limiting as the only option given Android-only status at launch). 

Having three activities also provides several touch points for outreach during the campaign timeframe, with a spotlight on each. 

Each activity will also have a lo-fi alternative. 

Here are @amirad's suggestions: 
- **Hack the News** http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

Pssst. No wifi at your event? Do the Human HTML Tag Puzzle https://gingercoons.makes.org/thimble/human-html-tag-puzzle
- **Create a Comic** on Webmaker App (placeholder until #20 is closed). http://flukeout.com/examples/tiles-nav-2/load.html

Pssst. No wifi at your event? Do a mobile app brainstorm activity https://jess.makes.org/thimble/LTEyMjY3NjgzODQ=/mobile-app-brainstorming
- **Get a hold of your data online** Learn about cookies and third party tracking http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-lightbeam.html

Psst. No wifi at your event? Do the Draw a Secure Password activity http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-secure-passwords.html

**Comment by amirad** [comment]
Past learning shows that for every activity we should offer an offline activity that users can do as well. 

@HPaulJohnson @thornet @chrislarry33 thoughts on the lineup?

**Comment by HPaulJohnson** [comment]
Looks good. I like the lineup and the opportunity 3 gives us to keep things fresh over the course of the campaign.

One question is how different are these from last year's activities: specifically, did we use "hack the news" or lightbeam last year? Might not be an issue but just want to make sure there is not fatigue, assuming many of this year's parties will be thrown by participant's from past years.

**Comment by thornet** [comment]
+1 to keeping the activities fresh. Also worth thinking about a "read, write, participate" frame for these three. 

How about this alternative to Hack the News?
- Hacking my media with X-Ray Goggles - https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles 

---> It's an alternative to Hack the News, with a focus on identity. Could update to not just be about gender. 

---> You can extend it by teaching participation, where learners could actually edit Wikipedia or create their own page using the Webmaker app. 

---> No-fi alternative: Print out a Wikipedia page and do all the editing on paper.

**Comment by chrislarry33** [comment]
I am setting read, write, participate narrative as mandatory 

Really like Michelle's suggestions

**Comment by amirad** [comment]
Here's a revised given Michelle's comments, Read/Write/Participate narrative and Webmaker.

**Read the web**

IP Address Protocol. http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session01-ip.html

No wifi alternative: Do the draw a secure password activity http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-secure-passwords.html

**Write the web**

[insert Webmaker App activity being developed by Souktel]

No wifi alternative: Do a mobile app brainstorm activity https://jess.makes.org/thimble/LTEyMjY3NjgzODQ=/mobile-app-brainstorming

**Participate on the web**

Hacking my media. http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

No wifi alternative: Print out the media page and make your edits on paper. [activity kit link]

**Comment by ldecoursy** [comment]
@chrislarry33 What's the specific timing on when the Souktel activities will be ready? We can design the page with placeholders, but might need to substitute a different "write the web" activity until those are completed. 

Also we likely need someone to help edit the Hacking My Media activity.

**Comment by ldecoursy** [comment]
Featured here: https://teach.mozilla.org/activities/maker-party-2015/ 

Finalizing the Webmaker activities here: https://github.com/mozilla/webmaker-curriculum/pull/215#issuecomment-120980832
