### ISSUE TITLE
Gather and collate resources for Teach Like Mozilla module 

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#17]
This issue has been migrated from mozilla/teach.webmaker.org#27.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> ## RACI
> - Phase: Scoping
> - Owner: **@****LauraHilliger** 
> - Decision Maker: **@****chrislarry33** 
> - Quality Verifier: **@****thornet**
> 
> [edited by Laura]
> ## Collections
> - [x] **@****jvallera** collection
> - [ ] **@****leahatplay**
> - [x] **@****smithisgeneric**
> - [ ] **@****kkeefe4**
> - [x] **@****amirad**
> - [ ] **@****Saallen** 
> - [ ] **@****LucyeoH** 
> - [ ] **@****omnignorant** 
> - [ ] **@****gmillener** 
> - [ ] **@****LindseyFrost** 
> - [ ] **@****SimonaRamkisson**
> - [x] **@****iamjessklein** 
> - [ ] **@****mcdermott415**
> - [ ] **@****Elsamozilla**
> - [ ] **@****thornet** 
> - [x] **@****kathrynmeisner** (though, on your last day maybe this one doesn't happen!)
> - [ ] **@****ldecoursy**
>   [end edit]
> ## Deliverables
> - [ ] Research and collation of resources for Teach like Mozilla. (curated, annotated folder): **@****LauraHilliger** 
> - [ ] Cluster into six modules to write and test: **@****LauraHilliger** **@****thornet** **@****chrislarry33** 
> - [ ] Tickets for next steps 

On Tue Feb 24 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> Several possible modules and approaches:
> 1) revisions for content currently on Training. At the moment projects and activities are mostly contingent on the old Webmaker tools. 
> 2) how to be open (partner with SOO)
> 3) how to be a Mozillian (define the cultural differences b/w Mozilla & open. Collaborate with Emma and reps teams)
> 4) confidence in  teaching (I would think about general personal and professional development here, with the "teaching" bit as a lens and avenue for practicing newly developed perspective skills)

On Thu Feb 26 2015, [dajbelshaw](https://api.github.com/users/dajbelshaw) commented:

> I'd also add that there's at least three different audiences:
> - Those that already teach in **formal** settings and want to try out different pedagogies/styles
> - Those that already teach in **informal** settings and want to up their game
> - Those that have **no experience** of teaching at all

On Mon Mar 09 2015, [thornet](https://api.github.com/users/thornet) commented:

> Possible later topic as well: 
> "how to organize and mobilze learners start to learn to take action in their community" 

On Tue Mar 10 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> Julia & Mouse just did Innovative Partner Professional Development: http://hivenyc.org/2015/02/18/ippd-training-doe-educators/
> 
> just storing a note I received from **@****thornet** 

On Mon Mar 16 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****chrislarry33** - I started a google doc here:
> https://docs.google.com/a/mozillafoundation.org/document/d/1quD8jfETB3_vuRc6IqWlbKAcn9bMcLGQOnpBiuH66Mw/edit
> 
> It is reflective of the conversation we had last week and begins to pull together resources for remixing content. Most is from Webmaker Training, but as I think about building out each module, I'll be looking through Hive archives ;)

On Wed Mar 25 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> tons of PD example agendas collected by **@****jvallera** in https://github.com/MozillaHive/HiveCreate/issues/1
> 
> https://hive.etherpad.mozilla.org/JuliaGH

On Thu Mar 26 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> added this to my doc, but double adding here cause it's awesome **@****billmills** http://mozillascience.github.io/instructorTraining/

On Thu Mar 26 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> Thanks **@****LauraHilliger** great start. I still think there is tons more to collect. Would like to map to heartbeat structure to do a similar capture to what we did with **@****jvallera** I want it all in one place" agendas, blog posts, curriculum, best practices etc. Lets design an intake process and use a heartbeat to drive all team members to get us their stuff. 

On Thu Mar 26 2015, [jvallera](https://api.github.com/users/jvallera) commented:

> Yes, love the training by Bill! and like the idea of gathering even more from across team. I am also interested in substantial ways to share out. I've am hoping to work **@****billmills** training into a community call or future PD of some kind. Would love to do the same once we have curated more from across team. Other ideas for sharing with community aside from discourse/minigroup and other channels:
> - Bi-monthly "Learn new curriculum with Hive NYC" hangout 
> - 20 minutes of every community call designated to sharing/testing new content
> - Curriculum Jam - twice a year for anyone, but directed toward classroom teachers

On Thu Mar 26 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****chrislarry33** for intake, can we just repeat the process **@****jvallera** guinea pigged? See:
> 
> https://teach.etherpad.mozilla.org/Collection
> 
> Then we could either file an issue & assign individual team members or you could email MozTeach w/ a deadline?

On Thu Mar 26 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> Love the momentum here, makes me very happy.
> 
> WFM. I'd copy Julia's example at top with the ask (and still leave at first completed version later). 
> - Lets do a combo of a mozteach email and assigning tickets for the discreet work ala what we did with **@****jvallera** 
> - **@****LauraHilliger** can draft email copy to send to team and share with me. Still debating better to come from me or you. I am leaning towards you, with a followup email from me to say this is important.
> - Want to make sure its mapped to upcoming heartbeat and advertised as such to 1) better condition us to do direct ask tasks in a project managed and time boxed way 2) build accountability 3) Have better tracking and  publicity in the TPS process.
> 
> sound good?

On Thu Mar 26 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> Also next step is a Discourse conversation aligned with this research, discovery and reflection. Put plan together for up coming heart beat, launch conversation in second for a start to finish date range of a month.

On Fri Mar 27 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****chrislarry33**  Draft copy: https://teach.etherpad.mozilla.org/CollectionDraft
> Discourse thread: http://discourse.webmaker.org/t/what-have-you-made-for-teaching-in-the-last-3-years/1299
> 
> Please hack at will, happy to edit the discourse thread as well if you have suggestions.

On Fri Mar 27 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> Looks good **@****LauraHilliger** I made a few minor tweaks and edits in the email pad. Go ahead and send on Monday!

On Mon Mar 30 2015, [thornet](https://api.github.com/users/thornet) commented:

> ＼（＾▽＾）／ 
> **@****LauraHilliger** this is brilliant. great stuff!

On Mon Mar 30 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****chrislarry33** - sending email, edited the description of this issue to include a checklist of folks on Mozteach team, probably easier than filing separate issues.

On Mon Mar 30 2015, [iamjessklein](https://api.github.com/users/iamjessklein) commented:

> Added my [etherpad](https://etherpad.mozilla.org/collections-jess) - it's  not exhaustive, but I have indicated to the best of my memory what I am not providing content on. 

On Tue Mar 31 2015, [BillMills](https://api.github.com/users/BillMills) commented:

> >  I've am hoping to work **@****billmills** training into a community call or future PD of some kind.
> 
> **@****jvallera** cool! Let me know if I can help out there or answer any questions.

On Tue Mar 31 2015, [jvallera](https://api.github.com/users/jvallera) commented:

> **@****BillMills** thanks! I really loved your kit and was wondering if you would introduce it/give background about it on an upcoming Hive NYC community call. Thinking June-ish. I will connect via email. 

On Tue Mar 31 2015, [BillMills](https://api.github.com/users/BillMills) commented:

> **@****jvallera** happy to - reach me at bill@mozillafoundation.org. I'm happy to find excuses to visit NY too, if a live meeting us useful; let me know.

**Comment by LauraHilliger** [comment]
@chrislarry33 @thornet @ldecoursy 
since this issue is so messy and this work is ongoing, I started a new one which includes most recent docs. Please add further comments there: https://github.com/mozilla/learning-networks/issues/162
