### ISSUE TITLE
Determine fate of Webmaker Newsgroup

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#170]
After a conversation with @emmairwin, we determined that there are 2 "Mozilla Learning" newsgroups. Since we're now separating "Mozilla Learning Networks" and Webmaker, it may make sense to refocus the Webmaker list as a place for tools and development, and take a look at the Education list as a place for Mozilla Learning Networks listserv discussions.

Emma said there are 97 people on the quiet "education.lists.mozilla.org" and she has admin over it. Would appreciate if @ldecoursy @openmatt @amira might advise - Does it make sense to reevaluate our mailing lists at this time?

cc @chrislarry33 @thornet

**Comment by ldecoursy** [comment]
cc @HPaulJohnson 

Could consider if/how this connects to any upcoming changes in Twitter channels, and perhaps also Discourse. Currently, teach.mozilla.org is pointing here as a way to connect: http://discourse.webmaker.org/category/meet

**Comment by ldecoursy** [comment]
We may need to re-assess this one. @HPaulJohnson @KevZawacki @kgorr

**Comment by ldecoursy** [comment]
Closing, as this is outdated.
