### ISSUE TITLE
Provide copy for "Tools" page of site

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#171]
After June 19th, Teach.m.o will become the main entry point for Thimble and X-Ray Goggles, as well as serving as an entry point for the new Webmaker.

We need to write copy for a /tools page on the Teach site. Should provide a brief explanation of all three tools, as well as any others that we want to point to.

**Comment by ldecoursy** [comment]
Here's a first draft: https://teach.etherpad.mozilla.org/toolscopy 

cc @HPaulJohnson @chrislarry33

**Comment by HPaulJohnson** [comment]
My edits in etherpad
