### ISSUE TITLE
Develop partner/setting-specific Clubs kits

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#172]
Create customized Mozilla Clubs on-boarding kits as useful resources for partners and others. 

[x ] Afterschool + Libraries @anmechung
[ ] Classroom/during the school day @gmillener 
[ x] Community Meet-Up @soapdog and @ldecoursy
[x ] Neighborhood with low connectivity @soapdog and @Saallen 
[ ] Higher Ed / Uni Campus @thornet and @smithisgeneric 
[ ] Living Room @ldecoursy
[x ] Existing program @Saallen 

Each kit will contain the following elements:
- Definition - what does a Mozilla Club look like in this particular context?
- Value 
- Audience/target participants
- Learning motivations 
- Steps for getting started
- Support networks
- User stories/case studies

**Comment by chrislarry33** [comment]
Love this!!!!

**Comment by ldecoursy** [comment]
Initial drafts here: https://docs.google.com/document/d/1Ye0u3Fu6m3VTSGCCag3UxdHt2cb2b5Aww-sQ2FDpI7E/edit

**Comment by hannahkane** [comment]
Taking this out of the June 5th milestone, so we can close the milestone.

**Comment by ldecoursy** [comment]
@amirad Let me know if/how this fits into existing guides currently in development for Clubs

**Comment by amirad** [comment]
yes, going to github the ones currently created and share them with the guides. But we can probably close this for now.
