### ISSUE TITLE
Prepare Javascript module for TeachDOT

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#173]
We'll be testing in parallel, but as this module was authored and tested by @mickfuzz, the new "Quacking Javascript" module is ready for review/posting to TeachDOT. Modifications to the curriculum won't affect teachDOT.

@ldecoursy copy is original from @mickfuzz - we may need a rewrite to match style and voice on teachDOT.

**Note: We will need to clear image usage with @mickfuzz and/or original author(s). Also,
Mick included facilitation notes, as did @smithisgeneric on the privacy module. We don't yet have a place for extended resources, but should consider them for future teach site iterations. http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/#teachnotes

index page for easy access (not for public): http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/

cc/  @hannahkane @thornet @chrislarry33 

---
# Quacking Javascript

Learners get familiar with writing Javascript in this fun, five-part module. Together we discover the foundations of the text coding by being creative and making our own web pages. These activities are designed to be used in Clubs, as guided session for learners of all ages or as a self-directed online course. 

The learning objectives underpinning each activity are informed by Mozilla's [Web Literacy Map](https://teach.mozilla.org/teach-like-mozilla/web-literacy/). Complete the activities in sequence, or mix and match for your learners. Need help? Visit our [discussion forum](http://discourse.webmaker.org/category/clubs) to get help and share your experience.
# Section 1: Reading the Web

These introductory sessions are focusing on the use of variables, different data types and how they can be used to output simple statements to the page. 
## [What's in a Name](http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/jsession01-whats_inna_name.html)

Introduction to Javascript Code and Variables: A fun start to look at what variables are and why they are useful when we are creating webpages using Javascript. 
Image: http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/images/rubberduck_square.jpg
## [Magic Numbers](http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/jsession02-magic_numbers.html)

Maths and Operators in JS: Using the hidden parts of web browsers to find out more about numbers, maths and Data Types in Javascript. 
Image: http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/images/chocolate-chip-cookies_publicdomain.png
# Section 2: Writing the Web

 Here we start to learn some of the tools needed to create more interesting web pages. 
## [Cooking the Web](http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/jsession03-sequences.html)

To make web pages we need to learn some of the language of the net and then take steps one after the other. 
image: http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/images/dora_the_explorer_square.jpg
# Section 3: Participating on the Web

These activities take you into more advanced areas of coding. Here we start to think about code that can save us time. 
## [Daddy or Chips](http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/jsession04-selection.html)

Selection and If statements in JS: Let's find out how to make decisions in coding. 
## [Going Loopy](http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/jsession05-iteration.html)

Iteration and For Loops in JS: Sometimes writing web pages means repeating things, we can find out how to do that easily.

**Comment by ldecoursy** [comment]
Hi - Very exciting to have this in such great shape! 

I suggest we keep this on the Github wiki for at least one round of testing before we post on teach.mozilla.org. 

Also @hannahkane and our dev/design folks are working to redesign the Teaching Activities page (will be inclusive of what's currently there plus what's on the Clubs Curriculum page) during this heartbeat, and once that's done we can move towards a smoother process for adding new, tested content.

**Comment by mickfuzz** [comment]
Sounds good, When I get time. I'll write a quick update with my own thoughts on improvement. 

One of those would be it could be improved with greater image / design continuity. 

Re image usage, I think it's 95% kosher CC images and my own screen graps in there. I'll have to check as I think there's one or two lazy steals still in there.

**Comment by ldecoursy** [comment]
Hi @mickfuzz Checking back on this, as we'd love to get this up onto teach.mozilla.org/activities. Have you had a chance to update any of the non-kosher images? ;) 

Let us know if this is the most up-to-date version that we could link to from the site: http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/

Thanks!

cc @hannahkane @omnignorant

**Comment by mickfuzz** [comment]
Hi there, 
I have gone through and sorted out those images so it is all CC-BY-SA as a minimum. 

That version is the most up to date. However, truth be told it would be good to get more feedback on the following lessons and also give some framing comments on the course.  

http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/js_loops.html
http://mozilla.github.io/webmaker-curriculum/QuackingJavascript/sequences.html

nice one
Mick

**Comment by ldecoursy** [comment]
Hi @mickfuzz apologies for the delay. @chadsansing is on the case, currently reviewing and will get back to you with questions/comments.

**Comment by chadsansing** [comment]
Working on a few contextual, meta review pieces that will help inform next steps here. Thanks for the patience, @mickfuzz & @ldecoursy .

**Comment by mickfuzz** [comment]
@chadsansing @ldecoursy Many Thanks!

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by ldecoursy** [comment]
Yes!
