### ISSUE TITLE
[TLM] Provide feedback and input to first TLM module

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#174]
With things popping up in #162 , I've been working on the first module for Teach Like Mozilla: Teaching and Learning in Open Spaces. I've produced this content in a Gitbook and I was thinking this would eventually be linked from the "Teach Like Mozilla" link on teachDOT.

I would love to have some feedback about both the content (images too!) and Gitbook as the delivery platform for Teach Like Mozilla. If we like this direction, we might work with @davidascher and team to implement the Webmaker theme plugin (which I couldn't get to work, [example here](http://book.webmaker.org)) as well as Gitbook interactive exercises, quizzes and some other features.

http://laurahilliger.gitbooks.io/teach-like-mozilla/content/

cc @omnignorant @ldecoursy @hannahkane @thornet @chrislarry33 @LauraReynal

**Comment by ldecoursy** [comment]
@LauraHilliger Some initial thoughts: I like the format given how content-rich this is (and looks like it can be easily downloaded/printed). The photos look great, but perhaps could be a bit smaller. 

I wonder if simpler/more descriptive headlines would be better - if the two current chapters are about pedagogy and practice, I'm not sure "Teaching and Learning in Open Spaces" and "Designing for Global Engagement" best articulate that. Also seemed like some content in the first section might be better fit in the second (Encouraging Diversity?)

I liked the section under Facilitating that talks about our approach being purposeful, participatory and playful - seemed like something to me that could be incorporated into the intro, as a way to help describe our value and how we're different/unique.

Where are you ultimately thinking the "module competencies" buttons will link to? Currently all linking to your open fluency blog post.

**Comment by LauraHilliger** [comment]
@ldecoursy, you rule. Thank you! I edited all the images to cut height down. I had filed #123 a while back, so would love more thoughts on the naming. Truthfully, pedagogy and practice are weaved throughout, just that the 1st chapter explains the theory more, and the second eases back a little and is more "how to". Perhaps Diversity should be split into multiple buckets...

I added purpose, participatory, etc to the intro and am thinking we need an image there too. 

Module Competencies – Yes, good question. I used the taxonomy to organize TLM content and learning objectives, but the framework doesn't actually exist. As I sort, the map shifts. [Current iteration is here](http://www.zythepsary.com/wp-content/uploads/2015/05/openweb-leadership.png), and I've been trying to iterate on this organizing structure with the community. Need to think more...leadership is a nebulous beast :japanese_ogre: 

Do feel free to comment further, very helpful to have input at this stage!!

**Comment by ldecoursy** [comment]
I like the simplicity of Understanding, Facilitating, Uniting :)

**Comment by hannahkane** [comment]
Sorry for the very delayed response. This is a ton of amazing content! 

Regarding the delivery platform: How do you imagine people will use it—is it meant to be a reference document, or a workbook that you make your way through over time? I'd like to see some visual or copy-based cues for the reader about how they might make use of all of this great content. It feels overwhelming to me, so I would want to see if broken down into smaller pieces with pretty explicit guidelines about how to get the most out of it.

**Comment by LauraHilliger** [comment]
@hannahkane this is great feedback. I would like to make the book more interactive, a workbook sounds like a good aim. Do you think I should make subchapters for each bit of content? So if we look at ["Making IS Learning"](http://laurahilliger.gitbooks.io/teach-like-mozilla/content/understanding/en/making.html), I break it up to be:

1.1 Making IS Learning (take action steps on this page, would you put "take action" in the title? Like "Making IS Learning: Take Action"?)
1.1.1 We are all Makers
1.1.2 Connected Learning
1.1.3 Web Literacy (probably would pull the actual web lit content in here)
1.1.4 Recap of Making IS Learning

That might make it more navigable, and I could remix the intro to explain "work through this book by..." 

I would also like to make it more interactive, by adding some quizzes or exercises that the user can do online, right in the book. That comes later though (as I'll need a _real_ dev to help me out). Finally, more images/drawings/illustrations. Need to get the structure usable first though :)

Thoughts on that kind of organizing structure?

**Comment by jgmac1106** [comment]
Headings always (usually) increase comprehension. The more predictable the
text structure the  better. Having the anchor links to the headings will
also be useful down the road if we want to link to the book.

**Comment by LauraHilliger** [comment]
Thanks @jgmac1106! I've started breaking it up more. 

I'm wonder if this structure might be more overwhelming (keep adding your thoughts!), but I will look into a plugin to make the ToC collapsible. http://laurahilliger.gitbooks.io/teach-like-mozilla/content/

**Comment by jgmac1106** [comment]
The structure looks good what makes it look overwhelming is a lack of
unified voice because this has been a curation of existing materials rather
than a remix of source material the voice can sometime be lost. In many
places I can talk to you in the text but other times it gets lost.

The book is good. it Is waaaay easier to critique a writing project of this
size rather than do the writing.

Is it possible to make the sidebar links anchor links so I can scroll
and/or use the links?

You  need stronger transitions between the section elements. I need to know
where I am heading and why.

Also the use of organized and unorganized lists seems to jump around. The
more you can make the text structure of each section and subsection match
the better.

The bulleted recap section is great. I think this is where you could embed
a form, blog prompts, or links to discourse threads for extended learning.

**Comment by ldecoursy** [comment]
@chadsansing Should we close this for now, or hold for when we pick up TLM plans?

**Comment by chadsansing** [comment]
Either works for me - we'll need to have some DARCI talk about where to begin. Maybe I'd say say close this since we have links to the GitBook elsewhere.
