### ISSUE TITLE
Write copy for /events page "pre-during" MP

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#175]
We need new copy for the /events page that incorporates:
- Updated messaging (can pull from blog post/Save the Date email)
- Updated workflow-what does the button say instead of "Sign up for Maker Party updates (I want to host a Maker Party!, Sign up for updates and to receive your Maker Party certificate?)
- Intro copy for three featured MP activities (see mozilla/learning-networks#169)
- Intro copy for MP case studies (see mozilla/learning-networks#137)

**Comment by ldecoursy** [comment]
Connected to this ticket in the teach.webmaker.org repo: https://github.com/mozilla/teach.webmaker.org/issues/843

**Comment by amirad** [comment]
Here's a first draft of text: https://teach.etherpad.mozilla.org/teachsite-eventspage

**Comment by ldecoursy** [comment]
Thanks @amirad! I just took a first pass at edits. 

@thornet @KevZawacki @HPaulJohnson can you take a peek too? @sabrinang will be working on designing the page in the next heartbeat.

**Comment by KevZawacki** [comment]
Sure -- shared my edits with @amirad on Wednesday.

**Comment by ldecoursy** [comment]
Closing this ticket, duplicated (and completed) here: https://github.com/mozilla/teach.webmaker.org/issues/843
