### ISSUE TITLE
Write transactional email for MP "sign up"

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#176]
We should create an email response for when someone submits their email to the "sign up" CTA. 

Could include a link to the survey, events resources page, or generic MP certificate. Still TBD, let's focus on one.

**Comment by HPaulJohnson** [comment]
@amirad not sure the status of this but do you want me and @KevZawacki to take a crack at this?

**Comment by amirad** [comment]
Just went onto BSD and saw that it redirects to a thank you url. Can we add text to this @ldecoursy?

Most likely this person will already be at teach.mozilla.org so it is worth adding text or relying on the site to have the best CTA's?

**Comment by ldecoursy** [comment]
@amirad Sorry, not clear on last comment here. Need to update the email folks receive when they submit their email on the new events page. Probably CTA to drive them to the standalone MP activities page we're creating (with an ask to tweet their MP plans?)
