### ISSUE TITLE
Prepare Clubs Captain orientation agenda

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#177]
By the next RC meeting, we want a vetted orientation agenda that RCs can run for their club captains. It should follow: 
1. Publish Your Story
2. Reflect Openly and Often
3. Find your Club Members
4. Prepare an Orientation / First Session
5. Repeat steps 1 - 4 with your Club Members

We should build from good existing agendas like: 
- Digital Corps training: https://docs.google.com/document/d/1-09gt0NzI4MNjdnLy6KkJRXa6X8YWLvAhc07z5bAP7Q/edit
- 1st Month as an RC: https://docs.google.com/document/d/1f7r94MfAXyaNgLoFWINjenx6MQYVJTSjCqMzTJTFqBY/edit
- Webmaker Mentor Training: https://michelle.makes.org/thimble/MTcxMDQ4OTYwMA==/webmaker-training-uganda-2014

cc @omnignorant @amirad @ldecoursy @simonaramkisson @LauraHilliger @soapdog

**Comment by LauraHilliger** [comment]
Braindumping to kickstart! The following would be 4.5 hours, which is a bit long, but it hits the points, encourages P2P accountability, quick start Captains knowledge of Clubs infrastructures.

Agenda could be:
- 10 mins [Intro](https://laura.makes.org/thimble/ttt-introductions-and-setup)
- 20 mins Learners mindmap their origin stories, bullet the story (actual writing could be a follow up)
- 10 Shareout in small groups, discuss ideas for writing style & tone
- 10 mins Club infrastructure overview (quickly show discourse, mention community calls, we're here to support each other, we publish via social/blogs/wikis/etc, team is here to help, Facilitator helps guide the discussion and prompts for future open reflection (e.g. "During this workshop, we're collaborating and discussing ideas. Online, we do this through language and Mozilla Clubs have x, y, z infrastructure...")
- 15 mins Small groups of learners get to know each other, share their blogs (if they have them), play in Discourse, find 1 topic to respond to.
- 45 mins Learner Profiles, groups doodle on paper, come to consensus on the profile they're building, then [remix activity](https://laura.makes.org/thimble/making-learner-profiles) [with Ani's template](https://theanimal.makes.org/thimble/ODI1NjIzMDQw/dc-learner-profile-template)
- 15 mins shareout
- 1 hour Recruiting Makes (e.g. brainstorm and start making posters, fliers, etc that they'll hang/spread in local areas, set up blogs – however learners want to start)
- 15mins [Speed geek](https://laura.makes.org/thimble/LTE3MzEzOTU1ODQ=/speed-geek-connecting) shareout
- 1 hour Club Curriculum review + remix + practice (have peers work together to understand the clubs curriculum, remix for their individual contexts and [teach in pairs](https://laura.makes.org/thimble/role-playing-teach-in-pairs)
- 10 mins Closing circle, group pledge making (by when will you post your story in discourse? By when will you start recruiting)

**Comment by thornet** [comment]
Thanks, @LauraHilliger for posting! 

In the first round of this orientation, we'll include a Maker Party CTA as well. Basically, each club will host one of their sessions during MP. 

Slight agenda remix:
- Intro. Why we're here. Quick icebreaker.
- Tell your story of self in pairs. Includes your personal goals for your club and the region. 
- Profile your club members. Includes how you'll contact them. 
- Playtest 1 of the activities. 
- Walk through the remainder of activities. Discuss how you'll apply in your club. Emphasize the importance of participatory learning and read/write/participate approach. 
- Conclude with how this group will stay in touch and support each other. Includes calendar of everyone's first three sessions.

**Comment by hannahkane** [comment]
Taking this out of the June 5th milestone, so we can close the milestone.
