### ISSUE TITLE
Update Maker Party certificate

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#178]
If we want to send folks a Maker Party certificate as part of the incentive for signing up, we'll need to update it and make a PDF/printable version. 

https://makerparty2014.makes.org/thimble/LTEzNDM3NTAxNDQ=/maker-party-love-bomb

cc @amirad

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by ldecoursy** [comment]
Yes, closing now.
