### ISSUE TITLE
Update Clubs Toolkit based on new Clubs fact sheet

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#180]
Noticed some outdated info in the Clubs Toolkit https://teach.mozilla.org/clubs/toolkit/ probably worth a re-read to make sure it's aligned with the updated Clubs ur-text. 

@amirad @thornet

**Comment by amirad** [comment]
We need to change the support url to teachtheweb@mozillafoundation.org 

What else did you see @ldecoursy?

**Comment by ldecoursy** [comment]
The "Name and Brand Your Club" section was what stuck out to me - should be removed or updated.

**Comment by amirad** [comment]
Ok filled three new tickets for updating this section
[Update support email address](https://github.com/mozilla/teach.webmaker.org/issues/966)
[Update link to curriculum](https://github.com/mozilla/teach.webmaker.org/issues/967)
[Edit text on club branding](https://github.com/mozilla/teach.webmaker.org/issues/969)

Anything else that should be updated or can we close this ticket? @ldecoursy @thornet

**Comment by ldecoursy** [comment]
@amirad OK to close?

**Comment by amirad** [comment]
yes!
