### ISSUE TITLE
[JS Module] Reorder the 2nd and 1st activity

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#187]
General consensus showed that the 2nd activity was more of an awe inducing "hello world" activity and should be re-sequenced to ease people into the JS curriculum.

**Comment by mickfuzz** [comment]
Almost done - I spotted the wrong order on the index still at the top.

**Comment by LauraHilliger** [comment]
Done! I swapped them @mickfuzz 

PR: https://github.com/mozilla/webmaker-curriculum/pull/211
