### ISSUE TITLE
[JS Module] Integrate Plotter Penguin as a sixth activity

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#188]
Review whether it should be integrated as the second or third activity, and remix to match template: https://theanimal.makes.org/thimble/LTE2MzExMjUyNDg=/logic-math-in-design

**Comment by mickfuzz** [comment]
Hi there, Penguin Plotter seems like a good activity for introducing the importance of sequencing in coding. I've put in a very similar activity into this third session 
http://mickfuzz.github.io/webmaker-curriculum/QuackingJavascript/sequences.html

It's a maze game. Let's evaluate if this does the job. I like it as it is quite self contained, uses block coding and most importantly then translates those blocks into simple javascript commands.

**Comment by LauraHilliger** [comment]
oh great! We'll ask for testing of the next two activities in future curriculum calls [this week's agenda](https://teach.etherpad.mozilla.org/curriculum-calls). Let's put this issue on ice until we hear how the community responds.

**Comment by amirad** [comment]
@chadsansing can you review this ticket and either keep it in your scope of work or close it?
