### ISSUE TITLE
[JS Module] Integrate Hey French Toast

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#189]
https://mousemeredith.makes.org/thimble/MTU5MzU3MzM3Ng==/javascript-takeover-hey-french-toast-activity

Should look at if 7 activities is too much and which we would swap out

**Comment by mickfuzz** [comment]
I've got a suggestion on this one. 

The activity could be split into 2 main parts and act as a French Toast sandwich for the beginning and end of the course. 

One is a discovery activity with a good WOW factor, great at the end of the first lesson. 

The second is quite in depth as it requires a fair amount of delicate cutting and pasting and interacting with quite a lot of code. 

In terms of swapping out, we could get rid of the current activity - T-shirt shop at the end of Magic Numbers for the first part. And for the second part offer it as an exploratory task at the end of for the last session.

**Comment by amirad** [comment]
@chadsansing can you review this ticket and either keep it in your scope of work or close it?
