### ISSUE TITLE
Finalize survey for people that "pledge to teach the web"

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#190]
Getting ready to add a low-bar CTA on teach.mozilla.org to "pledge to teach," and we need to finalize the brief survey that will be sent to them following the submission of their pledge/email. 

Our goal is to gather initial information to better understand our audience and their needs, so we can share most relevant resources/opportunities, and use some of those learnings to inform overall strategy. Short survey aim to better understand location, learning contexts, and reach. 

Draft is here: https://docs.google.com/forms/d/1_841Ri_H_ID-G-TXDa60in08hvFpP0YbvQ3xKaeRcqg/edit#

@chrislarry33 @thornet @hannahkane @amirad Please let me know of any questions/suggestions/changes.

**Comment by amirad** [comment]
Notes:
•The text at the top seems kind of long - might suggest cutting that first paragraph as your important info on why your asking questions is below it. 
•Organization name or affiliation - does that have to be mandatory? What if it's just an individual person?
•Tell us more about how and where you teach - what about library? makerspace? community space?
•Should we add sections for how long have I been teaching or who do I teach with?
•Potential to have another open verbatim box on where they can use support in their teaching?

**Comment by hannahkane** [comment]
Looking good.

+1 to @amirad's comment about the intro text being too long. 

How would we use information about who they teach with?

Some things:
- "State/Territory" might be a more inclusive field label
- Do we need their postal code?
- I feel like the "how many learners will you reach?" question needs a timeframe, like, "How many learners will you reach this year?" or something. A professional educator might teach thousands over their career, but that's not what we mean, I don't think.
- Age range. Do we care about distinguishing older adults? Seems like it would be useful to know if people are teaching people age 60+, as opposed to 24-year-olds.
- Overarching note: the pledge is all future tense, so, in theory, not everyone who takes it is currently teaching the web. Should we make the language in the survey more inclusive of that possibility?
- Needs a contact email at the bottom

**Comment by amirad** [comment]
Oh the last time we ran one of these surveys you would be surprised at how many people teach seniors so I would definitely provide more age ranges and account for this. 
Contact address can be teachtheweb@mozillafoundation.org

**Comment by anmechung** [comment]
+1 on age ranges:
how about 6-13, 14-24, 24-34, 34-44, 44-54, 54+ (otherwise very slanted to youth)

in the list of "We'd like to know more about the things you're interested in" and "who and where to teach" why they want to teach is missing.  Seems like we should care why they want to teach digital literacy skills.  i.e. for jobs, participate in social media, news and current events, protect the internet, etc.

**Comment by chrislarry33** [comment]
Like @anmechung age breakdowns. +1 on a "why" question

**Comment by ldecoursy** [comment]
Thanks all for the smart feedback. Here's the latest: https://docs.google.com/a/mozillafoundation.org/forms/d/1_841Ri_H_ID-G-TXDa60in08hvFpP0YbvQ3xKaeRcqg/viewform

**Comment by chrislarry33** [comment]
Could we change the image? I don't have obvious replacement in mind

**Comment by chrislarry33** [comment]
Also thanks for all this work, excited to test this

**Comment by ldecoursy** [comment]
@chrislarry33 do you prefer one of these?
![screen shot 2015-06-05 at 9 42 56 am](https://cloud.githubusercontent.com/assets/4885898/8007088/62598e16-0b67-11e5-85dc-d86d3c668961.png)
![screen shot 2015-06-05 at 9 38 01 am](https://cloud.githubusercontent.com/assets/4885898/8007089/639c2bc6-0b67-11e5-89d5-b34db5803f21.png)
![screen shot 2015-06-05 at 9 37 37 am](https://cloud.githubusercontent.com/assets/4885898/8007093/6a6ca80e-0b67-11e5-9154-b3117846b12a.png)

**Comment by chrislarry33** [comment]
The third one I like a lot

**Comment by ldecoursy** [comment]
Updated: https://docs.google.com/forms/d/1_841Ri_H_ID-G-TXDa60in08hvFpP0YbvQ3xKaeRcqg/viewform

**Comment by hannahkane** [comment]
This is done.
