### ISSUE TITLE
Create a Context Mapping Rubric

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#191]
We need to document a flexible rubric for curriculum. We need to define some design constraints for ourselves, and then update the rubric as new contributions come in. 
- The who, what, where, when, why and how (see #144 and RC docs for this piece)
- Clubs, classrooms, conferences, etc. (see #172 for this piece)
- Audience, age level, expertise, geolocation, community, etc. (should start with clubs curriculum, including indeas brought forth in #184)

**Comment by amirad** [comment]
Seems outdated. Going to close.
