### ISSUE TITLE
Update MP assets for MoCo channels

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#192]
Following up with comments from [this issue](https://github.com/mozilla/teach.webmaker.org/issues/869). We need special sized images for Firefox sharing.  

Waiting for @KevZawacki to advise on size.

**Comment by KevZawacki** [comment]
Just followed up with MJ to clarify what changes are needed.

**Comment by KevZawacki** [comment]
MJ notes we no longer need to meet the <20% text requirement. 

So, the only specs to meet:

Facebook (FB) 1200x627 px. 
Twitter (TW) graphics 1760x800 px.
