### ISSUE TITLE
[Basics II: Privacy] Develop activity for "the world before the web"

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/learning-networks#194]
The Protecting your Data modules needs prior knowledge assessment and privacy context development in a (or several) fun activities. Feedback from the curriculum group was:
- CORE POINT: What is a web identity AND who gets to know it???
- We need to hook into those things they care about in the world. It might be fun to use these to challenge "what they think they know about the web".  Because (kids I teach anyway) feel they know a lot, are fooling everyone (reference to fake accounts), and can't be touched.  +1
- We probably need a whole module before basics even that really explores web prior knowledge and identity.
- TOR as a useful tool for human rights activists in other parts of the world - A story or case study to could bring this to life. 
- History of Privacy + history of online privacy
- can't advocate if you don't have something to lose – What was the world like before the web?!?!?! a big part of this is also understanding how social infrastructure has changed over the last 10 years. ...which is tricky if you're 10 years old.

**Comment by dkuropatwa** [comment]
I'm interested in seeing what you put together.

FWIW, here are links to some presentations I've done with kids, teachers, and parents over the last few years that touch on some of these issues:

http://www.slideshare.net/dkuropatwa/the-fourth-screen-v3

http://www.slideshare.net/dkuropatwa/children-see-children-do-v1

http://www.slideshare.net/dkuropatwa/you-your-kids-and-your-phones-v1

http://www.slideshare.net/dkuropatwa/why-is-she-smiling-v2

Hope it helps some. Slides without the narrative aren't always self-explanatory. Ping me if you want to talk. ;-) @dkuropatwa

**Comment by chadsansing** [comment]
Pocketing this for now in light of https://github.com/mozilla/learning-networks/issues/278.
