### ISSUE TITLE
Finalize activity descriptions for MP activities

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#195]
Starting at line 19 of this etherpad (https://teach.etherpad.mozilla.org/teachsite-eventspage), we've sketched out the MP Activities page, but key bits of content still need to be provided including 1-2 sentences on the learning objectives, and brief descriptions of each activity.

**Comment by hannahkane** [comment]
Who should do this one? @amirad @ldecoursy?

**Comment by amirad** [comment]
I added in descriptions that we had and made some tweaks. 

Still waiting on info and link to Webmaker app activity. Also reached out to @LauraReynal about using a better version of the app brainstorm activity she has - so link might change there.

**Comment by lauradereynal** [comment]
cc / @secretrobotron

**Comment by hannahkane** [comment]
This is looking good, @amirad. I made a couple edits and added a Learning Objectives section (following the same format as the Web Lit Basics and Protect Your Data modules). @ldecoursy - any edits?

Is there an ETA on the Webmaker activity?

**Comment by hannahkane** [comment]
@ldecoursy - can you take a look at this today and see if you have any edits? This is blocking the creation of the MP Activities page, which I think we want up pretty soon.

**Comment by ldecoursy** [comment]
Made some suggestions in the pad. Tried to condense the copy a little bit. 

My understanding is July 1 for the Webmaker activities, so might want a "Coming Soon" placeholder if this will launch before then.

**Comment by hannahkane** [comment]
Wondering if we should shoot for July 3 as the release date for this page. Might be easier all around, rather than doing a placeholder. Is there a communication planned around this?

**Comment by lauradereynal** [comment]
I have 3 acitivities on google docs
that needs to be adapted to these needs / made beautiful 
But I hope it's not a blocker for you, the content is there. 

Mobile brainstorming would be this design workshop remixed for copy  : https://docs.google.com/document/d/1X9utIdD9dN9fA9O1ZNGjMsqo312ky-EJIbO8IV1-8bg/edit#

This one is also pretty cool from Chicago with teens https://docs.google.com/document/d/1MnKa_frV0grPE_DqfKzRuoYBinUZ3acQ4ac7Rq08nUk/edit

And you can use this picture https://instagram.com/p/14gVTKJZMO/?taken-by=lau_nk
I have tones of pictures - need to share. 
The content creation we did would be this one , where the paper prototyping is very short, and then people make on the phone: 

https://docs.google.com/document/d/1MnKa_frV0grPE_DqfKzRuoYBinUZ3acQ4ac7Rq08nUk/edit

--- cc / @secretrobotron

**Comment by amirad** [comment]
Cleaned up the pad. Couple things to note, @LauraReynal and Bobby are updating the Mobile App brainstorming kit so will have a new one by end of Whistler. 
Also, I'm really not sure about the souktel curriculum dates (it actually makes me a little nervous) so we really need to decide whether we should wait for this or have a backup

**Comment by hannahkane** [comment]
It feels unlikely that we'll get to this week, so I'm going to suggest we table this until right after Whistler. Maybe some things will have shaken out by then. Thanks for the edits, @ldecoursy, and the links @LauraReynal.
