### ISSUE TITLE
Define content for "Community" page on teach.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#196]
We've agreed that we want a Community page on the site (accessible via a top level nav item), but we need to decide exactly what we want on that page. (Initially, it can link directly from teach.m.o to Discourse, but I don't think that's ideal for the long term.)

Ideas include:
- very brief introductory text describing the community forums 
- links to relevant community policies
- feed of recent discussion activity
- feed of popular topics
- specific threads we want to highlight - e.g. introductions, maker party, etc.

cc @amirad @ldecoursy @thornet to advise on the content and @toolness to verify that I'm not lying about any of the above being possible

**Comment by ldecoursy** [comment]
I think there will def be ways to explore this more in Whistler. Might be some streamlining of community calls (which I think would be good to link from here) and other developments that drive ideas for content here.

**Comment by ldecoursy** [comment]
@hannahkane Should we close this one?

**Comment by hannahkane** [comment]
Yup.
