### ISSUE TITLE
Update Webmaker logo on Mozfest website

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/learning-networks#197]
@hannahkane @Saallen 

I am not sure if this is the right place to post this, but as I was hanging out on the beautiful MozFest Website I saw that there is the old Webmaker logo on this page https://sendto.mozilla.org/page/s/mozfest-2015-save-the-date
It is in the footer. 

![screen shot 2015-07-01 at 18 25 19](https://cloud.githubusercontent.com/assets/8261945/8460716/e387f560-201e-11e5-8576-14a346ec085d.png)

**Comment by hannahkane** [comment]
Thanks, @LauraReynal. Closing this, but opening a new issue in the MozFest repo: https://github.com/mozilla/2015.mozillafestival.org/issues/137
