### ISSUE TITLE
GitHub Tutorials

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#198]
Did the MLN publish any GitHub tutorials for RC's and club captains? 

I went to remix the story of us curriculum and not sure if I am doing it correctly. I hit the fork button and then do I just make the changes?

Is there anywhere I can find a how-to guide on forking teaching kits and learning activities?

**Comment by thornet** [comment]
@jgmac1106 great q! cc @omnignorant who's also been thinking about this. 

We started some documentation here: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Webmaker-Club-activities

Would love to hear what you think of those instructions (acknowledging some of it is slightly out of date) and how we could make it better! +1 to having tutorials to improve the process as well.

**Comment by jgmac1106** [comment]
I will try it with the curriculum I am remixing.

One thing I noticed in tutorial,  "How do I finish? Publish?" In other
words once I finish does the page go live? How?

**Comment by chadsansing** [comment]
@thornet, @jgmac1106, @omnignorant: later, in another thread, would be great to discuss how to build a GitHub module. Lots of opportunity right now to think through what audiences would need to be successful there & w/ similarly complicated methods/UI/file structures (as compared, to say, 'hellow, world' or 'remix').

**Comment by thornet** [comment]
cc @soapdog who's been playing with Github as tooling for curriculum and
brief documentation on how to use it.

On Fri, Aug 21, 2015 at 8:23 PM, Chad Sansing notifications@github.com
wrote:

> @thornet https://github.com/thornet, @jgmac1106
> https://github.com/jgmac1106, @omnignorant
> https://github.com/omnignorant: later, in another thread, would be
> great to discuss how to build a GitHub module. Lots of opportunity right
> now to think through what audiences would need to be successful there & w/
> similarly complicated methods/UI/file structures (as compared, to say,
> 'hellow, world' or 'remix').
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/learning-networks/issues/198#issuecomment-133522105
> .

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by soapdog** [comment]
Hey friends,

Our current work is at https://github.com/RioMozillaClub/activity-template, I still need some better CSS there and more documentation or even a little video tutorial how to use it.

**Comment by ldecoursy** [comment]
@amirad @Carotejada @soapdog Is this something covered in one of the Clubs guides?

**Comment by chadsansing** [comment]
Curious to know the same. Participation & Open Science also have GitHub guides completed or in the works, so maybe also check with them to avoid duplicating work. This should also be part of the H1 leadership curriculum since fellows programs and staffers use GitHub.

**Comment by amirad** [comment]
@Carotejada is covering it briefly in her training program but it's not in-dept. It will be wise of us to point to those guides Chad mentions for those who want to go in-dept.

**Comment by amirad** [comment]
@chadsansing do you have links to those guides you mentioned?

**Comment by chadsansing** [comment]
@amirad, from Emma Irwin: http://emmairwin.github.io/

**Comment by amirad** [comment]
Gracias @chadsansing
