### ISSUE TITLE
Update Google+ Webmaker page

### ISSUE THREAD

**Issue by KevZawacki** [mozilla/learning-networks#199]
We need to rebrand the Webmaker Google+ page (https://goo.gl/lQugVm). To figure out:

-Will it become a page for the new Webmaker app, or a Learning Networks page?
-Once determined, swap in new logo + copy

@ldecoursy @HPaulJohnson Thoughts? 

cc @xmatthewx re: https://github.com/mozilla/webmaker-launch/issues/38#

**Comment by chrislarry33** [comment]
Or just nuke them? isn't G+ going away anyway?

**Comment by ldecoursy** [comment]
I just updated the page, linking to teach site, using image from mozteach twitter, etc. Short-term solution, given that this channel is pretty inactive.

**Comment by KevZawacki** [comment]
Thanks, @ldecoursy!
