### ISSUE TITLE
Develop Webmaker app activity for Maker Party

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#20]
This issue has been migrated from mozilla/teach.webmaker.org#30.

We need to create an activity for Maker Party (one of three featured activities/CTAs) that features the mobile Webmaker app.
## RACI
- Owner: @amirad @ldecoursy 
- Decision Maker: @chrislarry33 
- Development Lead: @secretrobotron?
- Consulted @hannahkane @thornet 

Deliverables:
We need to create two pieces of content:
- One is the sample activity for a Maker Party participant to remix
- One is a teaching resource for facilitator (incl. learning objectives, materials, step-by-step instructions)

Note this can potentially be tested during the Maker Prom event in NYC on June 11.

Final content will live on teach.mozilla.org and be incorporated into MP comms/outreach.

Also see content strategy for Webmaker app: https://github.com/MozillaFoundation/plan/issues/428

**Comment by ldecoursy** [comment]
@chrislarry33 Just want to confirm before closing this that we will use content created by Souktel vs. creating our own Webmker app activity/lesson plan for MP.

**Comment by ldecoursy** [comment]
Tracking here: https://github.com/mozilla/webmaker-curriculum/pull/215#issuecomment-120980832
