### ISSUE TITLE
Create CC Welcome guide and pledge contract 

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#201]
Package resources together to create a kit that can be sent to CC when first on-boarded.

**Comment by amirad** [comment]
Took a stab at a first draft based on our current toolkit, our fact sheet, info from legal and other resources. You can view it here: https://docs.google.com/document/d/1qQtPlPIEXcIQscy4ZAB4Hao4jogh4VODToUFbLj_SJc/edit?usp=sharing

@thornet @ldecoursy @soapdog @Saallen @simonaramkisson comments welcome!

**Comment by thornet** [comment]
Thanks! Added comments in the doc. Most important suggestion: let's structure this document as "Your First Month as a Club Captain". Using the steps listed in "Starting your club", use the materials you collected to support and guide each step. 

Should feel like a checklist that gets them through their first month.

**Comment by chrislarry33** [comment]
added a few comments, do we have a sense of where/how this will live? Also soon we need a plan for how we make all these great resources into one thing in service to MLN, these guides, mp guides, hive cook book etc...we have most of an amazing MLN guide

**Comment by amirad** [comment]
@chrislarry33 thanks! @thornet has included it in some of the github resources pages that have important documents for Regional Coordinators. 
I'm on a guide-spree right now but soon want to package them all together into a so-called clubs cookbook and hopefully soon into an MLN full guide. Maybe a project for August-September when MP starts to slow down?

**Comment by hannahkane** [comment]
Removing from July 17 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by thornet** [comment]
@amirad is restructuring the gdoc and will update this ticket with her edits. The pledge is ready, though!

**Comment by amirad** [comment]
Reformatted the doc to be for your first month. https://docs.google.com/document/d/1qQtPlPIEXcIQscy4ZAB4Hao4jogh4VODToUFbLj_SJc/edit?usp=sharing

@thornet - thoughts?

**Comment by thornet** [comment]
Did some more rewriting and formatting to make the Your First Month" aspect clear. Think we're good now.
