### ISSUE TITLE
Need a list of the classes used in GitHub Curriculum pages

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#202]
Is there a quick cheatsheet of the css classes (not sure if that is correct word....the css stuff) used in the curriculum pages? I am trying to create a teaching kit and I am hoping I guess correctly when switching classes such as buttons.

**Comment by jgmac1106** [comment]
I was working on a curriculum remix and dug into the stylesheet. It seems there isn't a css class for each competency. We only have them for the competencies used in Basics I and Basics II. We should add all competencies to the stylesheet so they will be there when RC's and CC's remix curriculum.

**Comment by thornet** [comment]
@jgmac1106 I've used http://mozilla.github.io/makerstrap/demo/#/ to help with the CSS in the curriculum. Does that help?

**Comment by jgmac1106** [comment]
What I learned, after trying, is there is not a css class for each
competency. Only those for which curriculum is being developed. We may want
to add a class for every competency into the style sheet.
