### ISSUE TITLE
Make a tutorial about how to use Central Station

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#203]
For #200.

In progress: http://mozilla.github.io/learning-networks/clubs/central-station.html

**Comment by thornet** [comment]
cc @simonaramkisson @ldecoursy @amirad @soapdog @Saallen 

Would you all mind taking a look at this tutorial and seeing if it helps you understand how to use Central Station?

**Comment by Saallen** [comment]
@thornet I just had a look through central station and referencing the tutorial. It seems pretty clear to me.
I do have a question on the Unassigned club captains- we dont remove them from the sheet just copy across to our own tabs (if I am an RC)- how will the new unassigned captains be seen? at the top of each section or the bottom?

**Comment by ldecoursy** [comment]
I added new ones to the bottom in the most recent export, but can add them at the top of each country/region moving forward if we think that's easier. We don't remove them so we have a central place to track if they're approved or denied (bc one of us will need to switch them from pending to approved or denied on teach.mozilla.org).

**Comment by simonaramkisson** [comment]
Just took a look and super straight forward from my end. This will definitely be super useful with RC conversations. Thanks for this.

**Comment by thornet** [comment]
Thanks all for reviewing and @ldecoursy for making your first Github edit. Closing this now, but let me know if you find more things to improve.
