### ISSUE TITLE
Finalize the email templates for RC to schedule interviews with CC

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#204]
In progress: https://teach.etherpad.mozilla.org/clubs-signup

**Comment by amirad** [comment]
The final copy is here: https://docs.google.com/a/mozilla.com/document/d/12mBzoXtRgC1-AV-6ZqweOiUDMzBRUQIV-whEEisrnak/edit?usp=sharing

@thornet are we good to close this ticket?

**Comment by hannahkane** [comment]
Removing from July 17 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?

**Comment by amirad** [comment]
I think it's done unless @thornet or @ldecoursy thinks we need to add more

**Comment by thornet** [comment]
These look great to me. Closing!
