### ISSUE TITLE
Club Curriculum Should Also be on Thimble

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#206]
Once Thimble Launches I think the curriculum should be hosted there as well as in Git.

Forking from Git may require more skills and resources than most club captains have. I just tried it for my first time and it took quite a bit. I wasn't really sure what I was doing: http://sandbox.jgregorymcverry.com/webmaker-curriculum-remix/WebLiteracyBasics-I/keepcalm.html

I think RC's and club captains would be better served if the curriculum was easier to remix. Not every club would have access to server or they may be like me and not have the skills to pull it off.

**Comment by thornet** [comment]
@jgmac1106 thanks for the experiments and feedback! with the improvements to thimble, including the ability to host files, i do think it's a more viable option to host the curriculum there. 

cc @omnignorant about how we could explore this

**Comment by hannahkane** [comment]
+1. woot!

**Comment by jgmac1106** [comment]
There was actually a comment on Discorse today askibg where the old teaching kit and learning activities went. (They got confused by the beta.webmaker.org. redirect). 

Since we are designing teaching kits for new Thimble why not design those kits on new Thimble?

My other thought was the community remixes would be on Thimble and then RCs and volunteer and paid contributors could curate and edit this into formal,  MoFo approved curriculum in Git Repo. 

This also allows you to control brand as the CSS for Git could be different than that on Thimble. Currently I could host low quality lessons on my server. To the average person they will see the Mozilla Learning Network brand and not the url.

**Comment by chrislarry33** [comment]
"My other thought was the community remixes would be on Thimble and then RCs and volunteer and paid contributors could curate and edit this into formal, MoFo approved curriculum in Git Repo."

I agree with this @jgmac1106 

Could then have a remix button on "official" curriculum that opens it into Thimble

**Comment by hannahkane** [comment]
Just curious about what advantage the github pages have over the Thimble makes (I wasn't around for those conversations).

Would also like to think about l10n. What's the best format for localizing curricular content?

/cc @alicoding

**Comment by alicoding** [comment]
we will discuss this on vidyo and will document them here after.

**Comment by chadsansing** [comment]
@hannahkane, @alicoding: any documentation as yet? Would love to see the remix button back on the GitHub pages.

**Comment by chadsansing** [comment]
@jgmac1106, @chrislarry33: yeah - if there's a way to remix from GitHub into Thimble, then I think community members will have good access to the curriculum.

**Comment by alicoding** [comment]
@chadsansing I can't remember why we didn't document this, but there was a complication in doing localization with github pages and Thimble in general, so I don't think there is an automate way like we're currently doing in other apps. The only way that's currently possible here would be to let community members translate English copy and make a Thimble make or github pages for that and submit them.

**Comment by ldecoursy** [comment]
@hannahkane Wondering if this ticket (re: remixability and l10n) is addressed by any of the curriculum database work? If so, can close here.

**Comment by hannahkane** [comment]
Yeah, this is what we're doing in https://github.com/mozilla/teach.mozilla.org/issues/1538.
