### ISSUE TITLE
Discourse Spam

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#207]
Can anything be done about the Discourse spam? There was this discussion: http://discourse.webmaker.org/t/we-need-some-mechanism-to-remove-the-spam/1604

Some of the Mozilla Clubs are using Discourse as a primary communication channel. It is also getting a ton of spam.

**Comment by chrislarry33** [comment]
good spot @jgmac1106 We talked about this today....investigating now

**Comment by ldecoursy** [comment]
Still working on this - we're getting closer, hoping to have resolved today.

**Comment by jgmac1106** [comment]
The server error message is still up. Would it be easier to just wipe Discourse and install a fresh instance? The category taxonomy needed a reboot anyways.

I would hope the data would be archived somewhere but it would be nice to have Discourse back up and running as clubs onboard. I noticed Discourse still running across other parts of MoFo, so if we could just reinstall. I say reinstall and be intentional in aligning the category taxonomy.

**Comment by ldecoursy** [comment]
@jgmac1106 We're in the process of doing all of the above and aim to have it up by end of this week. We've started a fresh instance with updated categories, and will be migrating over data we were able to recover over time. We have access to all of the posts, but unfortunately lost some user data in the process so many will show as authored by "anonymous." We'll also need to go through the old data and see where it fits best within the new category taxonomy but that will take more time. We'll have a note pinned to the top explaining the above, but agree at this point we want to have the forum available for the community to connect and grow ASAP.

**Comment by ldecoursy** [comment]
Apologies for the delay on this. 

I'm going to close this ticket which was initially about spam. We're now working to relaunch Discourse (without the spam). Have run into a few tech difficulties but we're close, we have an updated category taxonomy and will be migrating over recovered data over time.
