### ISSUE TITLE
Create a report based on learnings from the post-pledge survey results

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#208]

**Comment by hannahkane** [comment]
Captured July data here: https://docs.google.com/a/mozilla.com/document/d/1uxPjkKycMe2sfzfFphTE5p8I54QJaMb2W5HWKGjqOq8/edit?usp=sharing

Needs analysis

**Comment by ldecoursy** [comment]
@hannahkane posted here http://hannahgrams.com/2015/08/19/pledge-to-teach-survey-results-first-month/ I'll edit/re-post on Webmaker blog

**Comment by hannahkane** [comment]
@ldecoursy - should we close this?

**Comment by ldecoursy** [comment]
Or move to next heartbeat so we can update based on Aug data?

**Comment by chrislarry33** [comment]
i would like to see august data

Chris Lawrence
Mozilla Hive Mentor Network
clawrence@mozillafoundation.org mailto:clawrence@mozillafoundation.org 
http://www.clawrence.org http://www.clawrence.org/
@chrislarry33
SKYPE: chrislarry33
Mobile: 718-757-0843
G+ http://bit.ly/gclaw33 http://bit.ly/gclaw33

**Comment by ldecoursy** [comment]
Data was updated in the summary doc. Closing.
