### ISSUE TITLE
Determine engagement strategy for pledgers (after Maker Party)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#210]
- [x] What's our next CTA, once Maker Party is over? 
- [ ] Draft email
- [ ] Send!

/cc community participation team: @amirad @jvallera can't find Elsa's github handle
/cc @ldecoursy

**Comment by hannahkane** [comment]
Possibilities:
- Could be something about Clubs/RCs or MozFest, but those might be too specific. Perhaps better to have something that _anyone_ can do, preferably soon.
- Asking ppl to test a new activity might be good (should be something kind of exciting and novel)
- Could be related to launch of new Thimble 
- Could ask people to share/submit their favorite teaching activity

**Comment by ldecoursy** [comment]
I like all of these ideas! I might prioritize Thimble since we'll also have some updated activities in conjunction with new features. I also like the idea of people submitting fave web lit teaching activities - perhaps we manage that via a string on Discourse.

**Comment by jvallera** [comment]
I also like the idea of people submitting their favorite web lit activities.  We could share the Webmaker activity "would you rather" activity Robert tested this week and/or the working open matrix Elsa and Simona started.

**Comment by amirad** [comment]
Clubs/RC/Mozfest seem too specific (and we are in overload right now) so I would lean more towards Thimble or Discourse. Will we one day be able to tag resources on our site to the map? Because then Discourse would be cool. I'm leaning more to THimble now though.

**Comment by hannahkane** [comment]
Not sure I follow the "tag resources on our site to the map." Is there a map on Discourse?

**Comment by hannahkane** [comment]
I feel like this ticket needs an owner to drive it. Anyone want to volunteer? :)

**Comment by amirad** [comment]
(hand) I can own. I want to get down a roadmap for emails to all community and pledges for the rest of the year.

**Comment by chadsansing** [comment]
Pledge remix on new Thimble? 'This year, I am going to a, b, c for the Open Web?'

**Comment by amirad** [comment]
cc: @HPaulJohnson @KevZawacki tagging you here based on our convo on how to keep the ball rolling here

**Comment by hannahkane** [comment]
Moving to current milestone

**Comment by hannahkane** [comment]
As discussed in recent email thread:

Let's replace the survey CTA with these awesome new projects courtesy of @chadsansing:
- Homework Excuse Generator - https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4487/
- My Six-Word Summer - https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4493/
- Remix My Schedule - https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4498/
- School Around the World -  https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4500/

If others like this idea, we'll just need updated email copy. (For reference, the current copy is on line 23 of this pad: https://teach.etherpad.mozilla.org/clubtransactionalemails)

**Comment by chrislarry33** [comment]
I like!

**Comment by HPaulJohnson** [comment]
great - we can start work on email copy now.

is this an email that goes out BSD? specifically, is the email format HTML and can it support images?

**Comment by amirad** [comment]
works! Let's change the cta AND email those who already pledged with the activities.

**Comment by hannahkane** [comment]
will ask @mmmavis about the email platform, because I'm not 100% sure. Regardless, we should be sure to include tracking code so we can see how engaged ppl are with this content!

**Comment by mmmavis** [comment]
@HPaulJohnson 

> is this an email that goes out BSD? specifically, is the email format HTML and can it support images?

Yup yup, it'll be the same as how you prepared and sent Webmaker and Thimble launch emails.

**Comment by HPaulJohnson** [comment]
Here's a copy draft for this email. Tried to pull in all the elements from the winning split of the Thimble launch email. 

@hannahkane @amirad @ldecoursy take a look and add any questions, comments or edits: https://docs.google.com/document/d/17nxlz-_AWrcTQ-9-eObwQK286vYmbs-xcTjQ6vQ5RsA/edit

Once we have a working draft, I'll set up in BSD for another final round of testing.

**Comment by hannahkane** [comment]
draft looks good. added a couple comments.

**Comment by ldecoursy** [comment]
Thank you thank you @hpauljohnson! I also just added a few comments/suggestions.

**Comment by HPaulJohnson** [comment]
Changes made. Everyone (@hannahkane, @ldecoursy, @chrislarry33) good with this? If yes, give me a day to setup and test in BSD and then we'll start sending.

**Comment by hannahkane** [comment]
+1

**Comment by ldecoursy** [comment]
+1

**Comment by ldecoursy** [comment]
+1

**Comment by mmmavis** [comment]
@HPaulJohnson 

To edit the copy of the transactional email
1. go to BSD
2. Signup forms
3. search for "mentor signup"
4. you will see 2 forms: (plz update both to avoid confusion, thanks!)
   - **Mentor Signup Form (for Teach site STAGING, testing purposes)** -> the form used on staging
   - **Mentor Signup Form** -> the form used on production
5. Scroll down and edit the fields
   <img width="640" alt="screen shot 2015-09-22 at 4 07 29 pm" src="https://cloud.githubusercontent.com/assets/2896608/10034343/8e2d9a2c-6144-11e5-8dbe-c9b6e317c315.png">

**Comment by HPaulJohnson** [comment]
thank you @mmmavis - looks like we haven't been using HTML and when turning that on there's no way to send sample emails for testing (like there is with regular BSD emails). Because BSD can be tricky to setup the HTML for, we'll need to test. Is the staging site still setup in a way that would allow me to test there first before moving to main site?

**Comment by mmmavis** [comment]
@HPaulJohnson I've never tried sending HTML transactional emails on BSD.  I just had a quick look... other than the not horizontally resizable super narrow HTML editor it seems like there's no easy way to preview it either :sob: :angry: 

<img width="1122" alt="screen shot 2015-09-23 at 11 18 24 am" src="https://cloud.githubusercontent.com/assets/2896608/10054327/5b31a6bc-61e5-11e5-912b-184315fd33d2.png">

I guess what we can do is either
- use the staging form to sign up and check the confirmation email in your inbox :mask: 
- or create a temporary form to sign up and check  :mask: 

I have time today to help on this.  If the content is ready I can help you turn it into HTML.  Let me know.

**Comment by HPaulJohnson** [comment]
thanks, @mmmavis. The content is here: https://docs.google.com/document/d/17nxlz-_AWrcTQ-9-eObwQK286vYmbs-xcTjQ6vQ5RsA/edit. If you could turn it into HTML that would be awesome (I'll need the whole template in the HTML as well, as there are no template options in the recurring setup process either). 

I'll test using the staging form - what's the URL for that?

**Comment by mmmavis** [comment]
This is the staging form: https://sendto.mozilla.org/page/s/mentor-signup-for-teach-site-staging-testing (don't worry about the look of that page)

It seems like we don't have the option to apply email template to transacitonal emails(I couldn't find that option anywhere).  I opened a ticket on BSD's help desk just to confirm.  Let's wait for their response.

**Comment by mmmavis** [comment]
@HPaulJohnson 

response from BSD

> "Mavis, unfortunately we don't have templates in use on those emails. You'd have to insert your content directly in to that response body field."

:crying_cat_face: 

I added the updated content in, feel free to test the staging form and let me know how to proceed.

**Comment by HPaulJohnson** [comment]
Great, tested and it looks pretty good even without the template. 

I changed some copy ("back to school themed" changed to "classroom themed") to give it a longer shelf-life. 

Also need to link the image and the button to the landing page, using this URL: 

https://thimble.mozilla.org/?ref=PledgeToTeach_Signup&utm_campaign=PledgeToTeach_Signup&utm_source=teach.mozilla.org&utm_medium=email

I was going to add the tag myself but didn't want to mess up the rest of your beautiful HTML. So, if you could add that link to those two places, I think we are good to go and can copy it over to the production version of the form.

**Comment by HPaulJohnson** [comment]
This is done and live on production.

**Comment by hannahkane** [comment]
woohoo!

**Comment by amirad** [comment]
AWSM!

**Comment by mmmavis** [comment]
:tada:
