### ISSUE TITLE
Clubs Pledge- requesting first name info on Pledge

### ISSUE THREAD

**Issue by Saallen** [mozilla/learning-networks#211]
The information we receive from potential CC filling out the club pledge form is incomplete.
As in we recieve their webmaker name but not their first name- which makes initital outreach harder.
Can we add this as a field on the pledge form @hannahkane ?
cc @thornet @ldecoursy @soapdog @simonaramkisson @amirad @simonaramkisson - would you prefer full name ?

**Comment by hannahkane** [comment]
We can definitely do this. I'll want to watch the numbers closely and see if it causes the rate of Pledges to drop (or rise!). 

Let me know if you want one field for "First Name," one field each for "First Name" and "Last Name" (or "Surname"), or simply one field for "Name" (and let the user decide).

**Comment by Saallen** [comment]
I think one Field for name should surffice- let the user decide how much info they want to give. Thanks :sake:

**Comment by hannahkane** [comment]
Wait...just realized I'm confused. Are we talking about the Pledge to Teach form:
![screen shot 2015-07-28 at 11 56 24 am](https://cloud.githubusercontent.com/assets/8389648/8940627/c161a2ea-351f-11e5-8aef-4f90d27ebd26.png)

Or the Apply to be a Club form:
![screen shot 2015-07-28 at 11 57 32 am](https://cloud.githubusercontent.com/assets/8389648/8940651/df2994d6-351f-11e5-9866-2f9ac3ffc249.png)

Or something else?

**Comment by Saallen** [comment]
For the apply to Club form- I dont think we need it for the pledge....

**Comment by hannahkane** [comment]
Ah, got it. Filed a ticket in Teach site repo: https://github.com/mozilla/teach.webmaker.org/issues/1137

**Comment by Saallen** [comment]
:candy:
