### ISSUE TITLE
Template for a letter of recommendation for captains and coordinators

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#212]
We should provide a template for a letter of recommendation to help Club Captains and Regional Coordinators. This is a way to acknowledge their involvement, help with getting jobs and into universities, etc. 

We need to:
- [ ] Write an template letter
- [ ] Create a process for people to request and send their custom info

cc @amirad

**Comment by omnignorant** [comment]
Why don't we vouch for them as mozillians? are we already doing that?

**Comment by amirad** [comment]
@omnignorant we aren't, and I believe a good chunk of them aren't on Mozillians.org. It's a good step to make them internally feel included but individuals are still looking to get something they can show others and use for employment or school etc.

**Comment by jgmac1106** [comment]
Yes, I never even knew about mozillians.org until I saw this ticket. I just
it was the mentor and super mentor badges.

**Comment by amirad** [comment]
Did a template here: https://www.dropbox.com/s/ifft1qg9awv2kqx/Club%20Captain%20Reference%20Letter.pdf?dl=0 
Thought this lived best in a pdf so not as widely shareable. 

Next step would be determining process of who and how they get it. My suggestion would be only for CC's who have hosted 5 or more club events and are on the site. We might have to put somewhere in the clubs pages that this is available and to inquire within. 
@thornet thoughts?

**Comment by chadsansing** [comment]
@amirad, thinking of a macro CC badge that could be leveled up (bronze-->silver-->gold-->Mozilla red) as CCs complete more & more on-boarding activities, meetings & events w/ micro sub-badges. Worth pondering in another ticket?

**Comment by chrislarry33** [comment]
Big yes to levels of CC
Big yes to usher folks at a certain level into mozillians.org
Big yes to templates of collateral (like rec letters) that provide external value to CC (and others)

**Comment by amirad** [comment]
So that's a yes @chrislarry33??? ;)

Would love to have up-leveling badges which we can scope in another ticket (though may be dependent on badge plans that I don't know) @chadsansing 

Based on feedback from @jgmac1106 have added mozillians.org to first month as a club captain guide http://bit.ly/1U5kWyS (fyi - went to go vouch for your profile and noticed you didn't have one yet!)

**Comment by chrislarry33** [comment]
yes

**Comment by chrislarry33** [comment]
yeah badges obviously blocked....any update on that @hannahkane

**Comment by hannahkane** [comment]
Spoke with contractor for the first time this morning. Contract is being signed, but I don't have a start date yet for this particular project.

**Comment by jgmac1106** [comment]
Thx @amirad I had no idea about mozillians.org until a week or so ago. My
profile might still be blank.

I only thought there were webmaker mentors and super mentors.

Will go back to profile so you can vouch away.

The template is important for letters of rec and they look good (though RCs
should be encouraged to personalize).

**Comment by anmechung** [comment]
+1 to leveling up of badges.  Note that we have opportunity to hire full-time person dedicated to badges/credentials.

**Comment by hannahkane** [comment]
@sabrinang and I +1 the idea of the micro-badges (sounds similar to "achievements," which is a model we've been talking about). Please include us on the separate ticket you file. Thanks!

**Comment by amirad** [comment]
Going to close this since technically the letter is done
