### ISSUE TITLE
[Tracking ticket] Improvements to curriculum content, tooling, and partciipation

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#213]
A collection of projects, edits and ideas to improve our curriculum offering. 

Very much in progress: 
# Content
- Review Thimble activities (back to school themes): http://bit.ly/1gr28xo [ @hannahkane @chadsansing ] 
- Review existing curricular content: http://teach.mozilla.org/activities [ @omnignorant @chrislarry33 @chadsansing  @thornet]
- Update Clubs modules (Web Lit Basics, Protecting Your Data) [ @chadsansing ]
  *\* Curriculum queue: http://mozilla.github.io/webmaker-curriculum/
  *\* Curriculum sorting sheet: https://docs.google.com/spreadsheets/d/1VHj-89BhI4HtUQfXOW9jKlSGLx-FXV9Er1G86HKvtZU/edit#gid=0 [ @thornet @ldecoursy] 
- Teach Like Mozilla content: [ @anmechung @amirad Sam Leah @chadsansing  ]
  *\* Outline: https://teach.etherpad.mozilla.org/tlmcontent
  *\* Consider how/where to add info from local Hive PDs (Chi, NYC, CHA...)
  *\* Focus on leadership development
- Curating curricular resources from Hive portfolios to add to teach.mozilla.org
  *\* Scroll to bottom of this page for Hive links: https://teach.mozilla.org/activities/
  *\* Team: Leah, Julia, Sam, Robert, Lindsey, Simona, Hive Pitt
# Tooling
- Help make final decisions re: curriculum tooling: https://etherpad.mozilla.org/curriculumtech [ @hannahkane @thornet @chadsansing ]
- Play with @soapdog's Github/Markdown experiments
# Participation
- Prepare brief l10n sprint to for Web Lit Basics. 
- Surfacing/packaging other examples of good teaching
  *\* For instance, anything here to turn into teaching kits? https://etherpad.mozilla.org/thimbleuserstories

**Comment by jgmac1106** [comment]
Most of the testing notes are in two places: The etherpad from the
club/curriculum calls and on Discourse (which is down for some work under
the hood).

**Comment by thornet** [comment]
- a million to @jgmac1106. Just wanted a place to cross-reference it, since a few folks had gathered feedback elsewhere.

**Comment by anmechung** [comment]
One of the outcomes of the web literacy focus group thus far, is a group of people who are interested in providing further feedback on curriculum.  Hannah and I have been thinking about this as a way to capture data as baseline and for continuous improvement on a regular basis and as part of the research plan.  Should we do a call with Michelle, Hannah etc to align efforts?

**Comment by chrislarry33** [comment]
Quick note: Discourse is in the shop, going forward for immediate future use the etherpad/other ways until we dubug it

**Comment by jgmac1106** [comment]
**Apologize for going beyond scope of ticket** @anmechung I also think this could be something where we could leverage the old crew Belshaw had organized. Especially when the new curriculum hire is in place. Revising the old curriculum, writing new curriculum, and evaluating community submitted kits might be a good next step for the team. Had a rather large and well organized community around drafting the map, you should try to channel that now into operationalizing the map in terms of curriculum.I dropped a note about this into the curriculum etherpad but thought I would mention it here.

@chrislarry33 In terms of testing artifacts we won't be able to get many off of discourse (though I am going to miss learning how to say different body enhancements in Chinese) but much of the data also exists in club/curriculum etherpads. If I remember correctly you will have to check three different pads: the club pads, the curriculum pads, and then the 1-2 instances of the  combined pads.

There is also the pre-post Google Form attached to each of the activities that might provide some insight in revising the curriculum.

**Comment by chrislarry33** [comment]
@jgmac1106 Discourse will be back, but the Spam issue was bad and it signaled some other issues.

**Comment by jgmac1106** [comment]
I fully understand taking Discourse offline. The spam was awful (IMO the
entire site needed major spring cleaning to align to MLN...but that's
another ticket). Was just noting places where we had curriculum testing
data.

**Comment by ldecoursy** [comment]
Adding @chadsansing to some of the items above

**Comment by jgmac1106** [comment]
In terms of TLM content check with @sunnydeveloper her work on the Leadership stuff for participation seems very similar to the content wanted for TLM.

**Comment by chadsansing** [comment]
Need to get in touch w/ @soapdog re: l1on & other a few other stakeholders re: the odd item; work on other items is underway. Will split into several curriculum topics/tickets for reporting/feedback beginning week of 8/23/15.

**Comment by thornet** [comment]
Closing this tix now that @chadsansing has the amazing, way better organized #233.

**Comment by soapdog** [comment]
Will schedule a talk with @chadsansing to help with L10N. Sorry for mix ups during this week. With 3 events I got overwhelmed.

**Comment by chrislarry33** [comment]
@chadsansing @soapdog Can I be included in a kick-off call? I have some ideas programmatically that I think would be fun to play with and test here.

**Comment by chadsansing** [comment]
@chrislarry33 we're talking this afternoon (9/3) at 1 PM ET; can do a recap or reconvene after Labor Day, or postpone if you'd like. Please advise :)

Really just looking for a demo/explainer session to have a better idea of what L10n does at this point.

cc @soapdog
