### ISSUE TITLE
Review and migrate Acccessibility curriculum module to Github Pages

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#214]
Via @smithisgeneric: 

https://hivetoronto.etherpad.mozilla.org/AccessibilityDesign

As you may recall....
1) We adapted from @Maker_Mark (Julia and Karen went to his session at OpenEdJam and got his permission to remix)
2) Hive Toronto piloted the activity at a Maker Party last week  
3) Hive Toronto is using this for a National Maker Party in Ottawa in October

This is a perfect module to review and migrate to Github Pages / publish on teach.mo.org when we're ready. 

cc @omnignorant and Chad when he add his Github account to this repo. ^_^

**Comment by smithisgeneric** [comment]
I have a couple of photos of designs for this curriculum piece.  I'll add links here when I get them uploaded.

Here are the links: 
https://www.flickr.com/photos/karenlouisesmith/20263891065/in/dateposted-public/
https://www.flickr.com/photos/karenlouisesmith/20263889745/in/dateposted-public/
https://www.flickr.com/photos/karenlouisesmith/20075877250/in/dateposted-public/

**Comment by omnignorant** [comment]
Let me know how I can help. Would love to see if I can demo this with kids this fall at least.

**Comment by thornet** [comment]
cc @soapdog this would be a great module to test your awesome github/markdown tool with

**Comment by chadsansing** [comment]
Noted & appreciated, @thornet & @smithisgeneric. Will bring it up in on-going convos re: curriculum queue.

**Comment by soapdog** [comment]
Yes, that is the perfect test. I will build a version of it and paste here so that we can iterate over it.

Should I create a repo under the mozilla learning org or my own personal account (we can always migrate later)?

**Comment by smithisgeneric** [comment]
Hive Toronto is using the curriculum at a national MediaSmarts hosted Maker Party on Oct. 22 and we'd like to have the module live and online by Oct. 15 for pre-sharing and promotion.  

cc: @simonaramkisson

**Comment by chadsansing** [comment]
@smithisgeneric (cc @ldecoursy):

Karen, is this etherpad - [https://hivetoronto.etherpad.mozilla.org/AccessibilityDesign](https://hivetoronto.etherpad.mozilla.org/AccessibilityDesign) - the entire module right now?

**Comment by smithisgeneric** [comment]
Yes, the etherpad is the draft activity.  We piloted the activity at a Hive Toronto Maker Party in July and the entire activity took about 1 hour and was well received.

**Comment by chadsansing** [comment]
I dig it, @smithisgeneric - I love MaKey MaKey :) 

Would Hive Toronto rather work it up for Thimble so it can be more accessible/remixable for you and your audiences than it would be on GitHub? Otherwise, I think we can work it into an activity template, and you can edit it with GitHub/pull requests as needed for future events/users.

cc @ldecoursy

**Comment by smithisgeneric** [comment]
I'd prefer that it go on GitHub.

**Comment by ldecoursy** [comment]
@soapdog Have you been able to turn this into a Github page yet using your markdown app (or otherwise)? If so, please post the link. If not, let us know if you'll have time to do this in the next week or so. 

In the meantime, I'm adjusting the milestone.

**Comment by soapdog** [comment]
Working on it. Will finish before the end of this week.

**Comment by soapdog** [comment]
Did a first pass on this one. We need to fix the content, specially the aside bar on the left. 

Live page at: http://soapdog.github.io/activity-accessible-gaming/
Github Repo at: https://github.com/soapdog/activity-accessible-gaming

You can create issues with content changes at https://github.com/soapdog/activity-accessible-gaming/issues or send pull requests with new content.

I created this under my own personal account because I didn`t knew where this should go. We can fork this repo using the mozilla account if we want.

The README file explains how this work and I can be reached on email, Telegram or Skype to talk about this if there is any doubt.

**Comment by ldecoursy** [comment]
Thanks @soapdog! 
@chadsansing @smithisgeneric can you take a look and let us know of any changes?

**Comment by chadsansing** [comment]
Looks good - thanks, @soapdog!

In the intro, maybe we should link to a definition of accessibility, define accessibility, or pose discussion questions that would help our audience of beginning critical thinkers come up with a working definition of their own.

cc @ldecoursy, @smithisgeneric

**Comment by soapdog** [comment]
@chadsansing,

Do you want me to transfer this repository to our org? Do you want me to add you as an admin there?

**Comment by chadsansing** [comment]
@sopadog, yes to both, please -

**Comment by soapdog** [comment]
@chadsansing added you as a collaborator and then transferred to:

https://github.com/mozilla/activity-accessible-gaming

but I don`t see the _settings_ option on the sidebar anymore so I think I might no longer be an admin after transfer. Can you double check you still have access to the repo?

**Comment by chadsansing** [comment]
@soapdog, I do not see settings, either, but can edit files, like readme.md.

**Comment by chadsansing** [comment]
@smithisgeneric, can you provide copy for a definition of accessibility and/or discussion questions?

**Comment by chadsansing** [comment]
@soapdog, @smithsgeneric, @ldecoursy - if users are satisfied, I'll close this issue.

**Comment by smithisgeneric** [comment]
It looks like I missed some @ questions directed to me about 2 weeks ago.  My apologies, I didn't see the notifications until today's came into my inbox.  I've gone through the activity page at: https://github.com/mozilla/activity-accessible-gaming/blob/master/data/activity.md and it covers off the need for a linkable activity for the Oct. 22 event.
