### ISSUE TITLE
Change wording on the header of RC description from "job" to "contribution"

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#215]
Hey Friends,

I was reviewing the RC page here with a new coordinator and he pointed out that the word "job" carry a strong meaning and people might not agree with it. In the website header we read:

> Mozilla Clubs: Regional Coordinator -- Volunteer Job Description

I would like us to consider a change to:

> Mozilla Clubs: Regional Coordinator -- Volunteer Contribution Description

or

> Mozilla Clubs: Regional Coordinator -- Volunteer Work Description

I am not really sure about which word to use but I think that "job" carries expectations and commitments that do not match volunteer work.

Any thoughts?

**Comment by chrislarry33** [comment]
I tend to agree

I like: "Mozilla Clubs: Regional Coordinator -- Volunteer Work Description"

**Comment by thornet** [comment]
Updated!
