### ISSUE TITLE
Change the email generated when you sign up for Mozillians.org account

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#217]
This morning I signed up through Mozillians.org and selected teaching. At some point the automated email needs to relfect the change of the old webmaker evolving into Mozilla Learning Networks and the list of tools changed. 
## Not sure how active the channel is for recruiting for MLN  but thought I would file the issue. Here is the text of the email:

Thanks for your interest in helping Mozilla teach the web! 

Mozilla Webmaker promotes web literacy through hands-on making and sharing. We’re an open source project powered by makers, mentors and community leaders. We’d love you to get involved. 

Our teaching guides, tools and community events allow webmakers to not only create the content that makes the web great, but — perhaps more importantly — understand how the web works. 

Teaching & Learning
Learning through making is a core part of Mozilla's mission. We provide starter projects, templates and event guides to inspire teachers and learners at every level to create on the web and share their knowledge with others. We consider web literacy a critical skill just like reading, writing and math. 

Tools
Creating the web is the heart of our work. We build tools like Thimble, X-Ray Goggles, Popcorn Maker and Appmaker that allow people to create amazing content while peeking under the hood of the internet, getting familiar with all the moving parts and getting their hands dirty with foundational elements like HTML, CSS and JavaScript. 

Community
We recognize that innovation can come from anyone, anywhere, so we bring together people with diverse skills and backgrounds — teachers, filmmakers, journalists, hackers, youth, artists, scientists policy-makers and more — to collaborate online and at events around the globe. 

We are so glad you are interested in helping us teach the web. Get started today by creating a Mozilla Webmaker account. Feel free to email or tweet to @webmaker if you have any questions. We’re looking forward to seeing what you create. 

Want support to get started? Check out the Mozilla Guides Community, particularly the section on Teach the Web! You can chat with other new contributors and experienced Mozillians about how you can take the next step on your Mozilla journey. 

All the best,
The Webmaker Team

**Comment by ldecoursy** [comment]
Good catch @jgmac1106! Thank you - we'll work on getting this updated ASAP.

**Comment by HPaulJohnson** [comment]
thanks, @jgmac1106 

@ldecoursy would love to help think about what this welcome message should be. 

cc @KevZawacki

**Comment by ldecoursy** [comment]
Yes please! Also in figuring out how/who to submit the change ;)

**Comment by KevZawacki** [comment]
I think the gist is still there — we just need to tweak some wording. So:

## 

Thanks for your interest in helping Mozilla teach the Web!

Mozilla Learning promotes web literacy through hands-on making and sharing. We’re an open source project powered by makers, mentors and community leaders. We’d love you to get involved.

Our teaching guides, tools and community events allow educators and learners to not only create the content that makes the Web great, but also understand how the Web works.

Teaching & Learning
Learning through making is a core part of Mozilla's mission. We provide starter projects, templates and event guides to inspire teachers and learners at every level to create on the Web and share their knowledge with others. We consider web literacy a critical skill just like reading, writing and math.

Tools
Creating the Web is the heart of our work. We build tools like Thimble, X-Ray Goggles and Webmaker that allow people to create amazing content while peeking under the hood of the internet and getting their hands dirty with foundational elements like HTML, CSS and JavaScript.

Community
We recognize that innovation can come from anyone, anywhere, so we bring together people with diverse skills and backgrounds — teachers, filmmakers, journalists, hackers, youth, artists, scientists, policy-makers and more — to collaborate online and at events around the globe.

We are so glad you are interested in helping us teach the Web. Get started today by creating a Webmaker account. Feel free to tweet us @MozTeach if you have any questions. We’re looking forward to seeing what you create!

All the best,
The Mozilla Learning Team

**Comment by ldecoursy** [comment]
WFM, although I think we can take out the "Mozilla Guides Community" mention. That leads to a Discourse instance that is separate from our own. I might just lose the last paragraph altogether. 

And should it be signed The Mozilla Learning Team?

**Comment by ldecoursy** [comment]
@KevZawacki If you agree I can file the ticket and share with Lucy, who can help us make the changes.

**Comment by KevZawacki** [comment]
+1, works for me. Good catch — we definitely need to update the signature. Just updated the above text.

**Comment by ldecoursy** [comment]
Filed a ticket in bugzilla to change this: https://bugzilla.mozilla.org/show_bug.cgi?id=1193760

Thanks again!
