### ISSUE TITLE
[Clubs] Add "how did you hear about us" to interview intake form

### ISSUE THREAD

**Issue by thornet** [mozilla/learning-networks#218]
We need to add a question in the club intake interview form "how did you hear about us?"

cc @amirad @ldecoursy @Saallen

**Comment by ldecoursy** [comment]
@amirad @hannahkane Is this something we can still consider adding to Clubs application workflow?

**Comment by hannahkane** [comment]
Do you mean the "Apply to be a Club Captain" modal on the /clubs page? We can add it there. Would you want it to be a text field (allows for more specificity), or would the user choose from a list (easier to group into actionable data)?

This could also just be a part of the RC interview process. Adding fields to forms tends to reduce completion rate. 

Let me know what you want to do.

**Comment by ldecoursy** [comment]
Good point @hannahkane. I think adding to RC interview process is better. Does that mean it would be added to q's sent after someone applies to be a club captain?

**Comment by amirad** [comment]
+1 to interview process though we are embedding the interview questions into the auto email to be sent to club sign-ups.

**Comment by amirad** [comment]
This seems outdated and not so important anymore. I'm going to close.
