### ISSUE TITLE
Links to Research from teach.mozilla.org

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#220]
I was looking for links to recent publications (white papers, @LauraReynal's et al., ethnographies) and I could not find them on teach.mozilla.org.

If they are not on the site (the in-house writing and research should be) there should at least be external links.

**Comment by ldecoursy** [comment]
The Web Literacy whitepaper is linked at the bottom of the page here on teach.mozilla.org: https://teach.mozilla.org/teach-like-mozilla/web-literacy/ 

You can find Laura's research reports on the Webmaker blog: https://blog.webmaker.org/category/research which is also linked from the teach.mozilla.org homepage

**Comment by jgmac1106** [comment]
Thank you @ldecoursy! Just what I needed, though IMO there should be a place for the research on teach.mozilla.org or a link to the research category on the webmaker blog.

**Comment by ldecoursy** [comment]
cc @hannahkane to see if/where this content might fit in the roadmap. I'll also check if there are plans to add the research to webmaker.org (the research was in service to the development of the app), where it might make even more sense.

**Comment by lauradereynal** [comment]
I was working on creating a place to put all the research online. Something like mozilla.github.io/research but I have not made tones of progress yet. I will see if I can speed this up. 

Ideally, it would be good to have some sort of space where not only we could link the reports, but also the methods and other assets. People have been asking for this. I will keep you posted on the decision. 

Thanks @jgmac1106 for pointing this out !

**Comment by hannahkane** [comment]
Research papers is on the list for potential content to include in Teach Like Mozilla, though I don't know if it would naturally include the Webmaker research. I like the idea of linking to a feed of blog posts tagged with "research."

**Comment by chadsansing** [comment]
I recommend reviewing Open Science and HIVE research, etc., as well, such as 

http://hiveresearchlab.org/2015/04/13/on-ramps-lane-changes-detours-and-destinations-new-community-developed-white-paper-on-supporting-pathways-through-brokering/

for inclusion in the Teach Like Mozilla (TLM) research space.

Would be happy to lead/help.

**Comment by jgmac1106** [comment]
You could add a "research" link to (either page or feed) in the footer, but
that would make seven links and I know folks love their symmetry.

**Comment by chadsansing** [comment]
As this shapes up, would also recommend adding Webmaker research reports, e.g. Chicago, India, Bangladesh, Kenya -

**Comment by ldecoursy** [comment]
Closing this - I believe @LauraReynal  is close to getting a research site up and live, then we can address where links live.
