### ISSUE TITLE
Create Blogging, Social Media, and PR Guides for Clubs

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#221]
Building off the guides @KevZawacki created for Webmaker launch we are going to create some marketing guides specifically for clubs to use in their area.

Here's the templates:
https://docs.google.com/document/d/1OYov_IFXV0o5BeBlY1SOPZeoZfjO9Jp646og1ef8U8U/edit
https://docs.google.com/document/d/1LYAqg2dD8x9fdWzGJr9h29AHZ-NK4b3bEYQhyEdA0fw/edit
https://docs.google.com/document/d/13Ie2_xMYw2iqb_m3uHCqGSkSWFE_yH6jceYwzOHDPiY/edit

**Comment by jgmac1106** [comment]
I would caution on advising strong English skills as I see many people
blogging with trying to improve their English skills as a goal. Just try to
get across, "Tell your story in the fewest words and the most pictures
possible."

**Comment by jgmac1106** [comment]
Hey @amirad These are great ideas as I just had time to really look at webmaker templates. I want to ping @chadsansing as I think these could be a curriculum kit as well as a club guide. Think about a "hello world" kit that would cover all of these for a new club.

**Comment by chadsansing** [comment]
@amirad @jgmac1106 so noted; would also think of them as train-the-trainer activities for RCs helping CCs and as capstone activities for modules around advocacy and organizing.

**Comment by amirad** [comment]
Good note @jgmac1106 - @KevZawacki let's be sure to add that note about pictures in the text.

How can we turn them into activities? Or even pair them with activities? The idea is to create a hello club kit with guides on marketing, fundraising, partnership, running a club etc. Would love to have your eyes and expertise give things a look as we develop it @chadsansing

**Comment by jgmac1106** [comment]
I would also hope the Club guides do not explicitly ask people to adhere to
"basic Mozilla brand and messaging guidelines." I am assuming the webmaker
template was meant for more internal folks rather than volunteers.  You can
suggest it as a resource, "Make sure to check out Mozilla brand and
messaging guidelines here." Suggesting rather than "adhering" just sits
better with me.

**Comment by KevZawacki** [comment]
Hi all, here are copies of the Webmaker guides that we can repurpose for clubs. Feel free to edit away:

Blogging guide: https://docs.google.com/document/d/15pw9ihno5DzIxiyMxqzcGY_z1lSEPJCE_oA94bB3t_4/edit

PR guide: https://docs.google.com/document/d/1bqpO6uZ6o1l4DftqvFdV97j1eyhE6fbOKUnp16rcteU/edit

Social media guide: https://docs.google.com/document/d/1UIukayevaotjBNtn_sRO3ozPPvlrghFs6mGbHjhTCs0/edit

**Comment by amirad** [comment]
Update from the call 09/01/15 - Kevin/Paul to take another look at guides with new user and give it an edit before review!

**Comment by ldecoursy** [comment]
@KevZawacki @HPaulJohnson any update? We can also get Kristina to help...

**Comment by KevZawacki** [comment]
@ldecoursy Hey, Paul and I will be revisiting the guides late this week/early next. Revisions coming soon!

**Comment by KevZawacki** [comment]
@ldecoursy @amirad @HPaulJohnson I've updated our three guides for Clubs -- feel free to drop in comments and suggestions:
- [Blog guide](https://docs.google.com/document/d/15pw9ihno5DzIxiyMxqzcGY_z1lSEPJCE_oA94bB3t_4/edit)
- [PR guide](https://docs.google.com/document/d/1bqpO6uZ6o1l4DftqvFdV97j1eyhE6fbOKUnp16rcteU/edit)
- [Social media guide](https://docs.google.com/document/d/1UIukayevaotjBNtn_sRO3ozPPvlrghFs6mGbHjhTCs0/edit)

**Comment by ldecoursy** [comment]
@amirad @KevZawacki Is there a preferrred due date/milestone for this?

**Comment by amirad** [comment]
We should set a date on this...currently waiting for revised copies from @KevZawacki - Kevin, when should we milestone this for? By Mozfest?

**Comment by HPaulJohnson** [comment]
@ldecoursy @amirad we'll commit to getting these done by Mozfest. I may jump in to get them to the finish line as @KevZawacki has his hands full at the moment. I'll work to have the next drafts for review by early next week.

**Comment by amirad** [comment]
Great thanks @HPaulJohnson! Set milestone accordingly

**Comment by amirad** [comment]
Friends, can I get some help wrapping these up before end of year. Would really like to end with them being done - @HPaulJohnson @KevZawacki 
I also asked Kristina to help take a look

**Comment by HPaulJohnson** [comment]
thanks for the reminder, @amirad. will make sure this is wrapped up before leaving on pto next week.

**Comment by HPaulJohnson** [comment]
@amirad these have been updated per your comments. If you have any additional feedback we can do a final pass before the break.

**Comment by amirad** [comment]
Thanks so much! Added edits straight into the doc and included comments @HPaulJohnson @KevZawacki

**Comment by amirad** [comment]
Thanks to @KevZawacki and Kristina for some last minute edits. I think we're about good here. I'm going to close and we can move to githubing these guides.
