### ISSUE TITLE
Developing curriculum guidelines

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#222]
Thinking of ways to help the entire community better understand and design for the differences between 'canonical' curriculum, curated community kits and activities, and inspiring makes.

Do these sound like useful categories for assessment and feedback (y-axis of a rubric)?

```
 Accessibility, Equity, Licensing/Openness, Pedagogy, Quality, Technology, Tone
```

Do these sound like useful descriptors (x-axis of a rubric)?

```
 To be curated for curriculum, To be curated for the community, Under development
```

All feedback and help with blindspots is greatly appreciated.

**Comment by anmechung** [comment]
Y-axis: all really important. I wonder if some of these are overused words that have lost their impact and may need to have their meaning defined within the context of our work?
x-axis: like these - together is is something like: ongoing curation of curriculum by and for the community?

**Comment by jgmac1106** [comment]
Can we start by just defining each of the three before creating a rubric to
judge the quality? Or is the matrix just to be a visual in defining the the
three?

**Comment by hannahkane** [comment]
I like both of these axes. I keep getting a little bit confused by terminology, though. "To be curated for curriculum" feels self-referential (curriculum curated for the curriculum?) Could we say "Clubs Curriculum" and "Community Curriculum"?

**Comment by jgmac1106** [comment]
Agree. I just posted to another issue I am confused on out naming of the
different types of curriculum, modules, activities, kits, etc.

**Comment by chadsansing** [comment]
@anmechung - yes, we should avoid over-use fatigue and find bright terminology/definitions. As a rubric shapes up, we can think of where definitions go to help contributors.

**Comment by chadsansing** [comment]
@jgmac1106, @hannahkane - the headers surely need work. Generally, I'm thinking of the curriculum as the canonical curriculum and of everything else something from MLN staffers or a community contribution that we curate /spotlight - or else let be. 

We could use 'Clubs Curriculum' and let everything else remain a teaching kit, activity, or make/remix. I worry about confusion between 'Clubs Curriculum' and 'Community Curriculum.' Does that make sense?

**Comment by hannahkane** [comment]
Makes sense to me.

**Comment by chadsansing** [comment]
Closing this as we move on to other areas of feedback [over here](https://github.com/mozilla/learning-networks/issues/230).
