### ISSUE TITLE
Curriculum module & activities review

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#223]
Reviewing the content, design, and embedded practices of modules and activities. Please send along or point me towards any feedback you consider essential. Feel free to add feedback below, as well, and/or to share any feedback not yet back on Discourse.

**Comment by jgmac1106** [comment]
@chadsansig I am a little unsure of the workflow (how things move from Git
to the curriculum cue) so if what I say makes no sense disregard. This
might be better to set up as one of those meta-issues that has the check
boxes and links to one issue for each teaching kit and the activities (also
what is the final language we want to use kits, activities, makes?)
contained within that kit.

So we would have a heading for Basics II Privacy and then links to an issue
for all of  the privacy activities in that kit/module.

If we try to review all of the activities in this one issue it might get
unruly for you to track.

**Comment by chadsansing** [comment]
Thanks, @jgmac1106 - learning the ropes. I'll come back to this later today and figure out a better way forward. I appreciate the help.

**Comment by chadsansing** [comment]
@jgmac1106, I'm going to close this and write a better ticket shortly.
