### ISSUE TITLE
Mozilla Web Literacy Training at National Writing Project Annual Meeting (NWPAM15)

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#235]
## DARCI

**D** - Lainie  (cc @ldecoursy)
**A** - Chad 
**R** - Chad, Julia, An-Me, Carolina, w/ Christina, Andrea (NWP) (cc @anmechung, Julia, Carolina) 
**C** - An-Me, Robert  (cc @omnignorant)
**I** - Leah, Claw, Amira (cc Leah, @chrislarry33, @amirad)
## Opportunity
- Needs to produce a replicable output.
- Aligned with key goals in web literacy leadership development.
- Positive experiences working with NWP.
- Create a more polished day-long (building toward 2-day-long) PD for web literacy 'in a box.'
- New curriculum contributors, RCs, CCs, and mentors.
## Strengths
- We can interact with NWP site-leaders, teacher consultants, and staff, K-16.
- We can test out new MLN curriculum.
- We can build on prior work with NWP partners.
- We can build toward UWL curriculum within future NWP trainings.
## Weaknesses
- Concurrent planning for MozFest and NWPAM15.
- Short turnaround between MozFest and NWPAM15.
- Web literacy is inconsistently taught across NWP sites.
- It takes a lot of time to plan and organize.
## Budget
- Chad, Julia, and Carolina travel (An-Me?)
## PD Planning
- Logistics (Chad checks-in w/ Christina, NWP)
- Promotion (Lainie, Kevin) (cc @KevZawacki)
- Organize planning (Chad)
- Finalize agenda, including activities, deliverables (Chad)
- Create training materials (Chad, Julia, An-Me w/ input from Christina, Andrea, NWP)
- Co-facilitators run-through (Chad, Julia, An-Me? w/ Andrea, NWP)
- Create PD feedback survey (An-Me)
## Day of PD
- Co-facilitation (Chad, Julia, An-Me?, w/ Andrea, NWP)
- Documentation (Carolina)
- Logistics (Chad checks in w/ Christina, NWP)
## Post-PD Follow-up
- Evaluate participant deliverables for badging and/or curation (Chad, An-Me)
- Blog/documentation (Carolina)
- Shipping Web Literacy Training for other cities and events (Chad, Carolina, Amira, An-Me on QA)
- Follow-up with participants (An-Me and Christina, NWP)
## Questions
- How can work like this lead to UWL training in NWP summer institutes?
- Will participants receive badges?
- Should an introduction to badges be part of the training?
## Deliverables
- [x] Session title and description to Christina (Chad)
- [x] Agenda for September 25th, 2015, work sprint (Chad)
- [x] Schedule and agenda for follow-up planning and materials creation (Chad)
- [x] PD materials & training (Chad, Julia, An-Me, and Christina, Andrea, NWP)
- [ ] Participant survey (An-Me)
- [ ] Blog post/documentation (Carolina)
- [ ] Replicable day-long and 2-day-long Web Literacy PD training in a box (Chad, Julia, An-Me)

**Comment by chadsansing** [comment]
Planning pad:

https://teach.etherpad.mozilla.org/nwpam15-planning

**Comment by anmechung** [comment]
I'm fine being an R

On Aug 26, 2015, at 10:42 AM, Chad Sansing notifications@github.com wrote:

DARCI

_D_ - Lainie (cc @ldecoursy https://github.com/ldecoursy)
_A_ - Chad
_R_ - Chad, Julia, An-Me?, Carolina, w/ Christina, Andrea (NWP) (cc
@anmechung https://github.com/anmechung, Julia, Carolina)
_C_ - An-Me, Robert (cc @omnignorant https://github.com/omnignorant)
_I_ - Leah, Claw, Amira (cc Leah, @chrislarry33
https://github.com/chrislarry33, @amirad https://github.com/amirad)
Opportunity
- Needs to produce a replicable output.
- Aligned with key goals in web literacy leadership development.
- Positive experiences working with NWP.
- Create a more polished day-long (building toward 2-day-long) PD for
  web literacy 'in a box.'
- New curriculum contributors, RCs, CCs, and mentors.

Strengths
- We can interact with NWP site-leaders, teacher consultants, and staff,
  K-16.
- We can test out new MLN curriculum.
- We can build on prior work with NWP partners.
- We can build toward UWL curriculum within future NWP trainings.

Weaknesses
- Concurrent planning for MozFest and NWPAM15.
- Short turnaround between MozFest and NWPAM15.
- Web literacy is inconsistently taught across NWP sites.
- It takes a lot of time to plan and organize.

Budget
- Chad, Julia, and Carolina travel (An-Me?)

PD Planning
- Logistics (Chad checks-in w/ Christina, NWP)
- Promotion (Lainie, Kevin) (cc @KevZawacki
  https://github.com/KevZawacki)
- Organize planning (Chad)
- Finalize agenda, including activities, deliverables (Chad)
- Create training materials (Chad, Julia, An-Me w/ input from Christina,
  Andrea, NWP)
- Co-facilitators run-through (Chad, Julia, An-Me? w/ Andrea, NWP)
- Create PD feedback survey (An-Me)

Day of PD
- Co-facilitation (Chad, Julia, An-Me?, w/ Andrea, NWP)
- Documentation (Carolina)
- Logistics (Chad checks in w/ Christina, NWP)

Post-PD Follow-up
- Evaluate participant deliverables for badging and/or curation (Chad,
  An-Me)
- Blog/documentation (Carolina)
- Shipping Web Literacy Training for other cities and events (Chad,
  Carolina, Amira, An-Me on QA)
- Follow-up with participants (An-Me and Christina, NWP)

Questions
- How can work like this lead to UWL training in NWP summer institutes?
- Will participants receive badges?
- Should an introduction to badges be part of the training?

Deliverables
- Session title and description to Christina (Chad)
- Agenda for September 25th, 2015, work sprint (Chad)
- Schedule and agenda for follow-up planning and materials creation
  (Chad)
- PD materials (Chad, Julia, An-Me, and Christina, Andrea, NWP)
- Participant survey (An-Me)
- Blog post/documentation (Carolina)
- Replicable day-long and 2-day-long Web Literacy PD training in a box
  (Chad, Julia An-Me)

—
Reply to this email directly or view it on GitHub
https://github.com/mozilla/learning-networks/issues/235.

**Comment by chadsansing** [comment]
Met w/ Christina on 8/28/15 re: logistics, planning.

**Comment by chadsansing** [comment]
9/10/15: Christina sent an invitation email to NWP friends of Mozilla and the folks invited to participate in An-Me's NWP focus group earlier in the year.

**Comment by chadsansing** [comment]
Initial planning sprint achieved.

**MoPad**: https://teach.etherpad.mozilla.org/nwpam15-planning
**GDoc**: https://docs.google.com/document/d/13s1EWToIhH4-QoWiHwCOCZII0yDSwqdpEcM1l9RLdPQ/edit#heading=h.z6d26jtij6w5

### Updated DARCI

**D**: Chad
**A**: Chad
**R**: Andrea, Chad, Julia, Carolina (documentation), An-Me
**C**: Christina, Lainie
**I**: CLaw, Lainie, Amira, Robert

cc @ldecoursy, @jvallera, @anmechung, @chrislarry33, @omnignorant, @amirad, Christina Cantrill, Andrea Zellner

**Comment by amirad** [comment]
Adding @Carotejada to the thread
