### ISSUE TITLE
Complete k12online conference session about Web Literacy

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#237]
Hey all 

@wiobyrne and I had a proposal accepted to present about the web literacy map. We wanted to invite @chadsansing @thornet and @chrislarry33 and anyone else who might want to get involved in the project.

Since I think the web literacy working group (though I did not see the working group listed on the [wiki](https://wiki.mozilla.org/Learning) anymore) is releasing V2.0 at #mozfest I didn't know if there any key points you would like us to hit.

> Proposal: Web Literacy Map V 1.5: Read, Write, and Participate for a Better Web
> 
> The due date for your video submission is on or before Week 2 part of Strand B: Beyond the Core: Arts > and More:  due on or before October 12, 2015.
> 
> Your presentation will be accessible from the conference [blog](http://k12onlineconference.org/) as of  the  week of October 26 - October 30. We will be posting two presentations in each strand M-F of that week.
> 
> Please remember that you will be submitting one video file no more than 20 minutes in length, but at least 15 minutes long. We also remind you that all presentations are to be licensed Creative Commons Attribution -- Please note that this means you may not include external content in your presentation unless it is public domain or licensed CC BY. We also ask that you not post your proposals publicly before we air them. More details on this are available in the 2015 Presenter Introduction Letter.

 **If you have any questions or concerns, please do not hesitate to ask me. We want to do everything we can to make this experience a positive one for you. The official announcement of all selected presenters will go live on our conference blog on June 22.**

> Congrats on your selection. We look forward to learning from you as together we promote "Virtually Unstoppable.”

**Comment by anmechung** [comment]
@jgmac1106 - congratulations!  Iris Gill and I have been conducting focus groups for web literacy 2.0 and are wrapping them up this coming week.  @wiobyrne is working with us on drafting outline/paper. Will follow-up with you via email.

**Comment by jgmac1106** [comment]
Sounds good. I have been watching the focus group pads. Amazing how many
common patterns exist across stakeholders.

**Comment by wiobyrne** [comment]
Hi all, 

Here is the video we presented at K12 Online 2015:

http://wiobyrne.com/webliteracy/

In it we document the work on the web lit map up to version 1.5.

Enjoy.
-Ian
