### ISSUE TITLE
Suggested Age Ranges Don't match ToS

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#238]
After discussing the ToS with @hannahkane I went back to look at the suggested age in the webmaker curriculum. We generally used 8+ but asked people to use tools such as x-ray Goggles and Thimble.

Based on the ToS 13 should be the minimum suggested age range for any curriculum activity that uses tools or spaces of Mozilla Leaning Networks.

**Comment by chrislarry33** [comment]
Agree here, for a cavalcade of reasons we need to use 13.Of course it can be used for younger kids but that needs to be at the discretion of the individual educator/parent/mentor etc.

**Comment by ldecoursy** [comment]
@chadsansing Is this something you can help update? Perhaps there's a way to signal that certain activities can easily be adapted for younger audiences where appropriate.

**Comment by chadsansing** [comment]
@ldecoursy, @chrislarry33: I think the work I've done for, say, Thimble makes so far has all been migrated to repos administered by others. @hannahkane, can you find/replace 13+ for 8+ on the Web Lit Basics, Protect Your Data, and Thimble activities? I can also try to do pull requests, but it will take me a bit to clone all the relevant repos and find everything. I can work boilerplate "Preparation"  copy into our with suggestions for adapting activities for younger age groups. I'll also make any needed changes to Web Lit Basics II stuff under development in my repo.

**Comment by ldecoursy** [comment]
@hannahkane Is this easy for you to do, or has this already been taken care of?

**Comment by ldecoursy** [comment]
Closing this ticket - covered for Web Lit Basics II and will soon make some updates to WLB I.
