### ISSUE TITLE
Decide which Webmaker app content to feature on teach.mozilla.org/activities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#239]
Currently, we're featuring one Webmaker app activity on the Maker Party resources page (this one: http://mozilla.github.io/webmaker-curriculum/MobileWeb/create-webmaker-project.html), but we'd like to include on the main activities page too. 

We have one of two options:
- Content created by Webmaker team and consultants - 3 activities plus additional resources: https://github.com/mozilla/webmaker-curriculum/pull/215 (would likely 
- Singular Webmaker app teaching kit informed by the above and created by community member in Indonesia as a resource for running Webmaker App Workshops https://d157rqmxrxj6ey.cloudfront.net/rara/4349/

@chadsansing Can you review and let me know what you think? Then we can make a decision and file a ticket in the teach repo to have something added on the activities page. 

Thanks!

**Comment by chadsansing** [comment]
These are awesome.

Any reason why we wouldn't bundle @secretrobotron's activities into a module? 

E.g. **Publishing & sharing on the Internet** (with links to **Learning about the Internet** and **Setting Up Your Phone** as optional --> **Creating a Webmaker Project** --> **Design a Story for the Web**

Also link those to the glossary and facilitator pages as the project ideas page is linked throughout?

**Comment by ldecoursy** [comment]
Per a call last week, @chadsansing is helping to put this bundle together, to then post on the /activities page. Going to close this ticket (since we've decided what to package), while the sequence is being finalized here: https://github.com/mozilla/webmaker-curriculum/pull/215#issuecomment-140054539
