### ISSUE TITLE
Thimble multi-page project

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#241]
@hannahkane & @KevZawacki, would you take a look here

http://chadsansing.github.io/curriculum-testing/thimble-multi-page-project/

and here

http://chadsansing.github.io/curriculum-testing/thimble-multi-page-project/tutorial.

I've tried to put together a simple multi-page project for folks to remix in Thimble. If these resources work, I can put them in Thimble on my account or the same account that has the Back-to-School makes.

cc @ldecoursy, @chrislarry33, @amirad

**Comment by chadsansing** [comment]
@hannahkane, can we add this:

(Remix this Webmaker Android App storytelling activity for your community with Thimble!) [https://d157rqmxrxj6ey.cloudfront.net/rara/4349/]

to the bottom of

http://mozilla.github.io/webmaker-curriculum/MobileWeb/design-webmaker-project.html?

**Comment by jgmac1106** [comment]
Was talking to @chadsansing about the multipage project. I suggested a floating top navigation rather than a side navigation. 

Would if be best to add this as a table or can it be done through js?

**Comment by hannahkane** [comment]
These looks great to me. Would be best to post them from the main, shared account, I think. Once you have the links, I can file a ticket to get them added to the Thimble homepage as a featured project/kit.

**Comment by KevZawacki** [comment]
Hi Chad, these are fantastic! Many thanks. Can you let me know when they're ported to Thimble? I'll then start sharing with users.

**Comment by chadsansing** [comment]
@hannahkane, @KevZawacki, @jgmac1106: check out https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/10950/. Ready to share?

@hannahkane, can we implement a JS nav scheme? Not sure exactly what @jgmac1106 is suggesting, but it might work better than what I have. Not urgent, I think, unless others disagree. I'd be happy to noodle with it if someone can point me towards a tutorial.

Can close once live, I think.

**Comment by KevZawacki** [comment]
@chadsansing perfect -- thanks again!

**Comment by jgmac1106** [comment]
I just meant a nav menu that floated at the top not on the left. I will
fool around with remixing it when you take it live. It is great. These are
going to be huge for teachers and Clubs.

**Comment by hannahkane** [comment]
@chadsansing - should we create a teaching kit to accompany this, or just put it up as a solo project ready for remixing?

**Comment by chadsansing** [comment]
@hannahkane - solo for remix for now, though I will include it in a forthcoming Back-to-School Write the Web kit featuring the other makes (Homework Excuse Generator, etc.) within the next week and a half.

**Comment by chadsansing** [comment]
Can use proof-reading & testing on https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/11288/.

**Comment by jgmac1106** [comment]
While I know it is considered bad form, you may want to use a blank target to prevent this from happening: 

![Link within linkt](https://cloud.githubusercontent.com/assets/10534566/9921870/6757c87a-5cb0-11e5-8317-a7f903f81b80.png)

I  hit remix on the kit and then clicked on the project link in the left frame. Thinking a blank target would fix this.

**Comment by jgmac1106** [comment]
In the objectives you mention linking several webpages, but in the
description your say learners will link several websites together. While
both are technically true as you pull in content from across the Web you
may want to think about matching the learning targets in the description
and the objectives.

This sentence seems confusing. I am unsure of the steps you want the user to change:

> You may also wish to set up an account on teach.mozilla.org that you can share with your learners. This will save time later when they are ready to publish their remixes.

I think users will find this confusing. 
- A. Hopefully the sign in process isn't a bad experiences at any stage. 
- B. I do not understand how me having an account makes it easier for my learners to publish.

This seems overly complex and strays from the learning target:

> Explain that after students hit the Remix button, Thimble will show them the code for the all of the project's webpages, as well as the CSS, or styling code, that makes the webpage work. Explain that CSS stands for 'cascading stylesheet.' Explain also that HTML, the language of the Web, shapes the page while CSS tells the parts of the page how to look.

We use similar boilerplate language across all the curriculum. Instead we should be thinking about a logical progression. Many wouldn't start with this project.

I would leave the intro to html and css to other projects and focus on the key learning target of the file system and using multiple files. Laser focus the copy in that direction.

This one is more food for thought in terms of nomenclature.  

Recently we have been leaning away from the word "make" as a noun and referring to thimble "makes" as projects. 

Not sure if this holds true but I remember the click counting team noting that the word "make" had a horrible conversion rate on a bunch of tests and we have heard from non-English contributors that it doesn't translate well. You may want to take this into consideration.

**Comment by chadsansing** [comment]
@jgmac1106, made several edits. I appreciate the "make" context, but didn't see too many instances of it it here, nor the intro sections. Thanks for the feedback!

**Comment by jgmac1106** [comment]
I could have been mixing up the activities.

This was from @humphd:

> As an aside, whoever is working on that page should be escaping the <3 (should
> be &gt;3) throughout so it doesn't break the page's markup.>

**Comment by chadsansing** [comment]
Thanks. Also made the changes to &lt; -

Let me know if you see any I missed :)

**Comment by chadsansing** [comment]
Looking forward to seeing the next batch of activities go up on https://thimble.mozilla.org.

**Comment by hannahkane** [comment]
Check 'em out: https://thimble.mozilla.org/

**Comment by chadsansing** [comment]
W00t!
