### ISSUE TITLE
Need feedback on webby contributor guidelines prototype

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#243]
Check out

http://chadsansing.github.io/curriculum-testing/contribution-guidelines/

and please offer any feedback below. Copy is not set, but the focus of this ticket is on chunking - does it make sense to break up contribution guidelines by area so that readers see one category at a time and never more than 5 guidelines at once? Looking at how to webify guidelines in concise, useful ways.

**Comment by jgmac1106** [comment]
Can it be done with the expanding tables like the Web Literacy Map V 1.5
currently on teach.mozilla.org? There would be one for each of the the
components.

The checklist approach is way better than the rubric IMO.

**Comment by chadsansing** [comment]
@jgmac1106 - yeah, I think we can try that. Will move implementation to the next meta ticket.
