### ISSUE TITLE
Back-to-School Write the Web Kit prep

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#244]
@hannahkane, @ldecoursy: I collected the recent thimble makes into a "page content" doc we could use to make a kit for /activities. Let me know if this is something we'd like to move forward. We can collect feedback from Thimble users to iterate.

https://docs.google.com/a/mozilla.com/document/d/1Wj6xouojulb7r2PmHOVQAPdBYs84xxeLc0kYdtRNiKE/edit?usp=sharing

**Comment by hannahkane** [comment]
I love this idea. Added some comments to the doc.

**Comment by jgmac1106** [comment]
The current back to school activities such as  https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/32/  have links in the right sidebar to projects that do not exist. We need to either: a:) build those activities first b:) switch the try next to an existing project c:) remove the Try next link until a project is ready.

**Comment by chadsansing** [comment]
Maybe remove the link or link to another Thimble project. Artifacts.

**Comment by hannahkane** [comment]
Removed link from Current Events teaching kit. The other two kits link properly _to_ the Current Events teaching kit.

**Comment by chadsansing** [comment]
I'll file a ticket to move this to production, yeah?
