### ISSUE TITLE
[Plan] Spread/Scale Hungercraft to Hive Cities & Partners

### ISSUE THREAD

**Issue by leahatplay** [mozilla/learning-networks#245]
Hunger Games Mockingjay Part II releases on Nov. 20, can we document and test the Hive NYC Hungercraft workshop in time for a November 20 or late fall release on teach.mozilla.org?

Etherpad here: http://teach.etherpad.mozilla.org/hungercraft
@chadsansing SWOT analysis here: https://docs.google.com/a/mozilla.com/document/d/17viv6RoJkiyySuW1n8h1-cYp6PMqAfiZ9QjcRwy3NBw/edit?usp=sharing

Decision-Maker: @leahatplay
Accountable: @leahatplay
Responsible: @jvallera @ldecoursy  @chadsansing 
Consulted: @chrislarry33 @ Meghan McDermott
Informed: Mozteach

**Comment by ldecoursy** [comment]
@leahatplay Can you share an update here, specifically if there are relevant action items. 

One may be reviewing/supporting marketing communications efforts. cc @KevZawacki

**Comment by ldecoursy** [comment]
I know the event happened over the weekend, @leahatplay @jvallera can you share any relevant feedback/updates/next steps here if there are any? Otherwise think we can close.

**Comment by chadsansing** [comment]
@ldecoursy, let's close this and move 'lessons learned' conversation to developing the next Minecraft/web lit opp.
