### ISSUE TITLE
Reboot Curriculum Queue

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#247]
@hannahkane, can I get an assist migrating this and  - in the near future - making it look better, maybe with fixed-width columns, for example?

[Curriculum Queue](http://chadsansing.github.io/curriculum-testing/curriculum-queue/)

**Comment by hannahkane** [comment]
Sure. Where is it going to live?

**Comment by chadsansing** [comment]
Replaces http://mozilla.github.io/webmaker-curriculum/index.html.

**Comment by hannahkane** [comment]
added to Teach repo to prioritize amongst other product team tickets: https://github.com/mozilla/teach.mozilla.org/issues/1285
