### ISSUE TITLE
Exploratory design/early childhood Web Lit

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#248]
Prototyping "Playground Games that Teach the Web." Thinking of this as lite exploratory design work for an audience we don't usually address. 

I'd appreciate any feedback on [IP Hopscotch](http://chadsansing.github.io/curriculum-testing/playground-games-that-teach-the-web/ip-hopscotch.html).

Curious if this resonates with anyone - have other ideas (like, "Firewall, May I?"). If you're interested in co-designing, let me know.

cc @amirad 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by amirad** [comment]
Playground games that teach the web sounds super familiar! I remember seeing HTML puzzle games hacked with chalk and a sidewalk for kids in India. Do you know Gauthamraj? Might be cool to ask him what he thinks of this based on the previous sidewalk activity.

For the reflection section "Ask learners to explain how they were like Internet while they played IP hopscotch." might need more prompts or explanation of what we want them to get at for the educators.

**Comment by chadsansing** [comment]
Thanks, @amirad! Will be in touch with more soon - maybe in the next 2 weeks or so - and will also ask around for inspiration!

"See if learners can work towards explaining something like...," sounds like a good addition.

**Comment by anmechung** [comment]
@chadsansing I've done a fair amount of work with the early childhood folks.  Happy to share what I know and connect you with those who are on the ground and working with young children. Let's add this to check-in this week?

**Comment by chadsansing** [comment]
Wonderful - thanks, @anmechung!

**Comment by chadsansing** [comment]
Not a lot of heat here. Closing.
