### ISSUE TITLE
Get the Back-to-School Write the Web kit up on /activities

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#250]
Moving ahead from https://github.com/mozilla/learning-networks/issues/244.

Referencing https://github.com/MozillaFoundation/plan/issues/582.

cc @hannahkane, @ldecoursy

**Comment by hannahkane** [comment]
Added to current product milestone as a p2: https://github.com/mozilla/teach.mozilla.org/issues/1290

@chadsansing - can you add a couple details to the doc, please? We need the "Level" and the "Developed by" (unless I missed them elsewhere). Thanks!

**Comment by chadsansing** [comment]
Added info to mozilla/teach.mozilla.org#1290.

**Comment by chadsansing** [comment]
[Landed](https://teach.mozilla.org/activities/back-to-school-write-the-web/).
