### ISSUE TITLE
Testing a maker/seflie Thimble project

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#251]
Could use feedback and testing on this Thimble project that mashes up #makered and the selfie feature.

~~https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17617/~~

~~**SHINY NEWNESS:** https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17964/~~

**SHINIER NEWNESS:** https://d157rqmxrxj6ey.cloudfront.net/chadsansing/18245/ or https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17617/ (again)

Pls share widely! Thinking of this as a prototype for Web Lit Basics II module (needs activity page).

cc @hannahkane, @amirad, @jgmac1106, @ldecoursy, @omnignorant, @jvallera.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jvallera** [comment]
@chadsansing awesome! Not sure what you mean by "selfie feature". Is there an activity about selfies (i could just be missing something)?. 

A couple small things:
- Can the activities target a blank page rather than load in the same page as the Thimble project? 
- Do you want us to share publicly? If so, Can you start a thread on discourse and share link? I am happy to share on minigroup/social media.

**Comment by amirad** [comment]
Same question as @jvallera 

Also I have a small computer screen and the bottom text was cut off for me and I wasn't able to scroll down to see.

**Comment by jgmac1106** [comment]
@jvallera Some have mentioned that the blank target page isn't aligned with best practices in terms of accessibility. 

I am hoping you are thinking of reusing the instructables content (under CC-BY-NC-SA) rather than linking to the pages. A mobile slideshow mess with weird ads everywhere.

Looking for the web literacy links. Would it be in documenting and sharing their projects? Is it jreading the web in order to to use how-to technical manuals ina  variety of modes?

**Comment by chadsansing** [comment]
@jvallera & @amirad: added the blank targets. Let me know how the UX goes :) Can also add to Discourse soon, but would like an activity page ready, as well.

@amirad: will mess with the positioning today.

@jgmac1106: working with feedback from Hive members and research reports re: pre-basic skills (e.g. use the Web to build something before you build the Web) and cultivating users' motivation. Trying to answer a hypothetical question from a middle schooler like, "Why should I use the Web?", with this activity and others.  I think reading the Web content for new learning hits navigation, remix, and participation. Once there is an activity page, that will help instructors frame the activity within those competencies, I hope. 

Not super worried about Instructables (probably helpful to learn the differences between view options - slideshow, list view, and .pdf download), but would love to hear from others, as well. Adding that content would mean stretching this page or making a new one, which would then set a precedent for rewriting all the other activities. However, part of our stance is something like, "The Web is more than dot teach or Thimble or X," so I think it's important for us to broker to a variety of pages and helps users learn which are most helpful to them as learners and community members.

**Comment by chadsansing** [comment]
@jvallera, inside the project, above the preview window, click on the Tutorial tab and it will take you through the selfie-making process :)

**Comment by chadsansing** [comment]
@amirad, more responsive design now up at https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17964/.

**Comment by jgmac1106** [comment]
My other question is why use DIY meme maker when Thimble's meme maker was
so popular. It will need to ported over anyway.

I just worry we are going to dilute web literacy by connecting/conflating
it to the much larger competencies required in Maker Ed. While there is
much overlap, especially in terms of design and computational thinking a
better approach for Web Lit II ,in my opinion, should look at what
competencies in the map were not covered in Web Lit I.

Some competencies or skills, such as querying an API, would be held off
until the Intermediate Web Development module. I just think we should start
be deciding what competencies and skills we want to be developed through a
kit and building resources towards this goal.

Finding materials and then trying to figure out how to pigeon hole in
competencies doesn't seem like the correct approach.

**Comment by chadsansing** [comment]
@jgmac1106, thanks for the tactical feedback - I think you'll see more competencies addressed as more of the module gets scoped, tested, and used or not used. More and more of those conversations will be coming soon!

I think we need a both/and approach to give connect people to the Web through their motivations. I do not feel like it's pigeon-holing to say we want to help you read Web pages that might be of use to you in making something you want to make and find that the Web has communities of practice you can join that are not code-dependent. I feel like we can address competencies while also shifting from 'learn to code' to 'code to learn' - or an approach that clearly does both. I feel like the tutorial also addresses a new Thimble feature, image swapping, and opportunities for playing with CSS. 

This is an early prototype that speaks to concerns I've heard voiced on internal and community calls re:  pre-basic dispositions and motivations. That's where the activity started; the competencies were not tacked on after the fact.  I'm most interested right now in how it does on those merits, and more content will follow re: other activities and competencies.

I'd love more feedback on the topic and will also move a few pieces to Discourse soon.

**Comment by jgmac1106** [comment]
+1 on developing the dispositions. The topic of making is great, you have a
maze, a falcon, a meme, a foosball table, and a hologram. That is all cool
stuff.

**Comment by chadsansing** [comment]
Added an activity page (which will have visuals soon) & will migrate discussion to Discourse today or tomorrow -

http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session01-the-web-is-for-making.html

**Comment by chadsansing** [comment]
@amirad, @jvallera, @jgmac1106: [Discourse thread live](https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136)!

cc @ldecoursy, @chrislarry33, @leahatplay, @omnignorant, @simonaramkisson, @hannahkane

**Comment by jgmac1106** [comment]
What is going to be the curriculum workflow? Will it be done  on Git or on
Discourse? Is Discourse just for larger community feedback?

**Comment by chadsansing** [comment]
Discourse is another channel for feedback for folks not on GH. Will work between GDocs, Thimble, & GitHub to share stuff that has 'there there.'

**Comment by jgmac1106** [comment]
Sweet. All of the above

**Comment by chadsansing** [comment]
Using https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4440/.

**Comment by chadsansing** [comment]
Now using https://d157rqmxrxj6ey.cloudfront.net/chadsansing/4440/.

**Comment by chadsansing** [comment]
Closed & moved to https://github.com/mozilla/learning-networks/issues/278.
