### ISSUE TITLE
Testing a new mixtape Thimble project (w/ optional selfie)

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#252]
Sharing another prototype of a possible Web Lit Basics II activity.

**Welcome to My Mixtape**

Thimble Project: https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17517/

Activity page: http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session04-welcome-to-my-mixtape.html

Discourse thread: https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/8

cc @hannahkane, @amirad, @jvallera, @omnignorant, @jgmac1106, @chrislarry33, @ldecoursy, @soapdog 
[Back to issues.](https://github.com/mozilla/learning-networks/issues/)

**Comment by jgmac1106** [comment]
I really like this idea. Especially the optional art album cover. Though I
wonder if it would be better to build in two pathways for music ability:
a:) start with an easier path that has them building a mixtape by embedding
soundcloud clips, and then b:) making music.

The activity fits in perfectly with the kits theme of using the web for
making. Much of target audience uses the web for music so it fits there as
well.

I worried the bar was set high but then I tried online sequencer and I am
addicted.

**Comment by chadsansing** [comment]
@jgmac1106, excellent suggestion re: multiple pathways. Will work it into the next go-around. Students loved Online Sequencer last year; glad it hooked you!

**Comment by jgmac1106** [comment]
Loop1 is now my ringtone.....oooh ringtone maker there would be a fun hack
of this lesson as well.

**Comment by chadsansing** [comment]
Totes.

**Comment by soapdog** [comment]
I will try this activity on our next club meeting. Lets see how it goes! :D

**Comment by jgmac1106** [comment]
I will test it in my next class module as well. It begins on Monday.

**Comment by chadsansing** [comment]
Updated activity page URL: http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session04-welcome-to-my-mixtape.html

**Comment by chadsansing** [comment]
Now using https://d157rqmxrxj6ey.cloudfront.net/chadsansing/8544/.

**Comment by chadsansing** [comment]
Bridge/menu activity.

**Project Playlist**

Thimble project & tutorial - https://d157rqmxrxj6ey.cloudfront.net/chadsansing/9011/
Activity page - http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/bridge01-project-playlist.html 
Discourse thread - https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/59

**Comment by chadsansing** [comment]
Closed & moved to https://github.com/mozilla/learning-networks/issues/278.
