### ISSUE TITLE
Testing a New Fair Use Free-for-All Activity 

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#253]
Working up a new reverse-image search, fair use, open licensing, and copyright activity for Web Lit Basics II building off an idea from @ldecoursy and hitting lightly on investigative/gotcha ideas from @omnignorant, though, of course, all shortcomings in execution are my own.

The idea is that kids remix a webpage with three images. Each image is an example of fair use, open licensing, or copyright violation. Then kids switch computers and try to bust one another using reverse-image searching. Little check boxes help them evaluate each image. Finally, learners think, pair & share consensus about an/each image with the class.

**Thimble project:** https://d157rqmxrxj6ey.cloudfront.net/chadsansing/21823/
**Activity page:** http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session03-fair-use-free-for-all.html
**Slides:** https://docs.google.com/presentation/d/1eW9zUSjhXX8PkWR8Muwz4VAv_icpF6SWfp-gSbHG22s/edit#slide=id.p
**Discourse thread:** https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/13

Especially interested in whether or not definitions of fair use, open licensing, and copyright work, and whether or not the project and tutorial make sense/are fun. Do the reflection questions in the activity page keep the tone from being just, "Obey the law!" 

All feedback is welcome and appreciated! Would also welcome collaboration on any and all activities, especially re: design & language if others are interested in taking a run at remix.

cc @amirad, @soapdog, @jvallera 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jgmac1106** [comment]
This activity is awesome! I did it as a scavenger hunt but reverse
engineering is so much deepet.

Fair use is so complicated. Any document about usually begins with, "I am
not a lawyer so...."  Any help we can give  is great.

Yet it might be better just describing all the different types of licenses
available and having kids reverse engineer that (great idea).

Are fair use rules international?

**Comment by chadsansing** [comment]
Excellent question, @jgmac1106 - this activity would definitely need to be localized as "fair use" is a concept in US copyright law (unless I'm mistaken).

I like, "I'm no lawyer, but...," as an alternative title. After testing the idea of the activity, I want to run the language past internal folks who deal with these issues.

**Comment by hannahkane** [comment]
I love "I'm no lawyer,  but..." as a title. :)

Very small thing: Might be useful to mention the licensing policies of Thimble. According to our [Terms of Service](https://beta.webmaker.org/#/legal), submissions may be remixed by others. "You hereby grant every user of the Tools a non-exclusive, worldwide, sublicensable, royalty free license to use your Tools Submissions in connection with the functionality available through the Tools." Could be a lead-in to talk about the educational and cultural value of remix. (If that's too outside the scope of this activity, I totally understand.)

**Comment by chadsansing** [comment]
@hannahkane, that would be a great reflection prompt and bridge to other activities and follow-ups, I think. Like, "Did you know that when you used Thimble today, you 'agreed' to give every user of Thimble....' What do you think of that?"

**Comment by hannahkane** [comment]
Love it. Feels valuable to the learner, and like a responsible thing to do on our part!

**Comment by chadsansing** [comment]
How is this for a prompt?

"Did you know that when you use Thimble, like in today's project, you agree to terms of service that say you give every Thimble user " non-exclusive, worldwide, sublicensable, royalty free license" to use your work? That means other Thimble users can remix what you've made (and then remix the remixes) without ever paying you. What do you think of that? In your mind, how should a tool like Thimble handle "ownership" your work? Would it work if people had to pay to remix other people's projects?"

**Comment by ldecoursy** [comment]
Added one note in bold below to help learners consider the value/benefit of contributing open content.

"Did you know that when you use Thimble, like in today's project, you agree to terms of service that say you give every Thimble user " non-exclusive, worldwide, sublicensable, royalty free license" to use your work? That means other Thimble users can remix what you've made (and then remix the remixes) without ever paying you. **And you can remix other people's remixes too!** What do you think of that? In your mind, how should a tool like Thimble handle "ownership" your work? Would it work if people had to pay to remix other people's projects?"

**Comment by chadsansing** [comment]
Updated activity page URL: http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session03-fair-use-free-for-all.html

**Comment by hannahkane** [comment]
Looks really good.  I see a few minor typos and such (and one big one, which is that some of the Learning Objectives don't seem to correspond to the activity). @chadsansing - what's the best way to tell you about those? Want me to send you a list, or should I just get access and make the changes myself?

**Comment by chadsansing** [comment]
Either and :) I'll go back through shortly, as well.

**Comment by chadsansing** [comment]
Bridge activity.

**Who am I?**

Thimble project & tutorial: https://d157rqmxrxj6ey.cloudfront.net/chadsansing/9604/

Activity page - http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/bridge03-who-am-i.html

Discourse thread: https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/63

**Comment by chadsansing** [comment]
Closed & moved to https://github.com/mozilla/learning-networks/issues/278.
