### ISSUE TITLE
Review pre-post curriculum learning survey

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#257]
About to test curriculum from Web Lit II. During Web Lit I there was pre and post Google Form for curriculum testers to fill out. Need to decide if a:) we are going to use the form again; and b:) if it needs to change.

cc/@omnignorant @chadsansig

**Comment by omnignorant** [comment]
I remember Laura saying that it wasn't effective, i.e. people didn't complete the forms. However, without site analytics to back things up, it's not clear what percentage of visitors didn't complete them. If there were only a couple people who viewed/used the materials and only a couple people completed the forms, then that's a high response rate.

**Comment by chrislarry33** [comment]
Agree with @omnignorant. We didn't get right last time but need to try again. @chadsansing what say you?

**Comment by chadsansing** [comment]
Agreed, & can be part of iteration. Is there a way to make the post-feedback survey results automatically available to facilitators, as well, so their learners can do the survey and generate data for them locally? Incentivize reflective assessment & survey completion at once?

**Comment by chadsansing** [comment]
@chrislarry33, @omnignorant, @jgmac1106, @ldecoursy, @hannahkane - is this something we can replace/augment with social features in the curriculum database (like/share this recourse, etc.)?

Can we close this instance of the conversation and move over to the database issues?

**Comment by jgmac1106** [comment]
Yes but the older questions were quite specific in the outcomes they tried to measure. 

Having a more than starring review ability in the database makes sense.

**Comment by omnignorant** [comment]
social can augment, but there probably needs to be some way that we are collecting substantive feedback on our materials that doesn't require someone to have to create a new account, or push via their personal social, no? I should be able to tell you if your stuff works for me without having to log into discourse. Like reviews/ratings on Amazon, Airbnb, etc. or a comment stream on a blog even.

I was looking for butternut squash soup recipes this weekend and I landed on one blog where the comment stream was particularly rich. It was awesome to see people posting their personal recipe remixes right there as simple comments. I learned a bunch just scrolling through those after I read the post.

**Comment by chadsansing** [comment]
Sure - not defining any features, just suggesting we frame this conversation within the database work, since that will be a discovery vehicle.

**Comment by chrislarry33** [comment]
Its nice to know @omnignorant makes a good soup

Yes I agree let's move this as part of database conversation, but agree with @omnignorant and @jgmac1106 on some of their flags

**Comment by hannahkane** [comment]
agreed on all counts (soup, database, and that there may be other outcomes we want to measure that we won't get through database features)

**Comment by chadsansing** [comment]
Let's close this and open a soup-off issue?

**Comment by hannahkane** [comment]
You guys, you haven't lived until you've tried my lobster bisque.

**Comment by ldecoursy** [comment]
Spring cleaning! Looks like this should have been closed in soup-ier weather.
