### ISSUE TITLE
Testing a New Remix the Web with Handcrafted Stickers Activity

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#258]
This one is a biggie. Learners create their own pixel art stickers, remix them into an openly shared Thimble gallery, and then comment on the Web by inserting their stickers into Web X-Ray Goggles remixes. I'm thinking of this as the culminating Web Lit Basics II activity that bridges into an intermediate module.

Curious about length, complexity, chunking, and clarity and usefulness of the activity page and tutorial. Would appreciate feedback on anything, as well as testing.

Copy and technical issues go here; content, pedagogy, and philosophy on Discourse.

**Thimble project & tutorial:** https://d157rqmxrxj6ey.cloudfront.net/chadsansing/7048/
**Activity page:** http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/session06-all-the-stickerz.html
**Discourse thread:** https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/42

Look for a new thread in the near future with iterated materials and a suggested structure for the Web Lit Basics II module.

cc @amirad, @soapdog, @thornet (thanks for the kawaii inspiration), @anmechung, @leahatplay, @zee-moz, @ldecoursy, @omnignorant 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jgmac1106** [comment]
You need to define web stickers, not just pixel art. People will not know
what these are.

**Comment by chadsansing** [comment]
@jgmac1106 et al., would love suggested definitions.

**Comment by jgmac1106** [comment]
A web sticker, similar to emojis or emoticons, is a small image file that
captures an emotion, serves as a  reaction, or is used as a  metaphorical
symbol.

**Comment by amirad** [comment]
I clicked remix of the make to be able to edit the stickers and have some feedback:
•I kept strolling through the text at first and was unable to find where to go. Might need to add some information on how to click on the panel beside the tutorial to get to the stickers.
•Will also need instruction on how to change images. I found this really confusing and gave up and left the page. 
•The stickers appear small on the panel, is there info on how to zoom in?

**Comment by chadsansing** [comment]
@amirad, can you tell me more?
- When you scrolled through the remix text and could not find where to go, was that in the index.html file that automatically loads in the left window?
- Would the activity page help educators guide learners to the tutorial effectively?
- Was it confusing to find out how to change the images, or were the instructions in the tutorial unclear? Both?
- Which panel had the small stickers? They are 100x100px images, so they are not too large. The pixel art services in the tutorial all have default zoomed views.

Thanks for all the help!

Also, thanks for the suggested stickers copy, @jgmac1106!

**Comment by chadsansing** [comment]
Bridge activity live for testing.

**Pixel Portrait**

Thimble project & tutorial: https://d157rqmxrxj6ey.cloudfront.net/chadsansing/9438/
Activity page: http://chadsansing.github.io/curriculum-testing/web-lit-basics-two/bridge02-pixel-portrait.html
Discourse: https://discourse.webmaker.org/t/working-towards-a-web-literacy-basics-ii-module/136/

**Comment by ldecoursy** [comment]
Worked for me! https://d157rqmxrxj6ey.cloudfront.net/lainie/9516 

Two quick notes on the tutorial
- Step 1: any is incorrectly spelled as "anuy"
- Final paragraph: Now you can insert an image on any webpage you make or remix _in Thimble._

**Comment by chadsansing** [comment]
Thanks, @ldecoursy - resolved.

**Comment by chadsansing** [comment]
Closed & moved to https://github.com/mozilla/learning-networks/issues/278.
