### ISSUE TITLE
Quarterly campaign plan

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#263]
by Orlando!

**Comment by amirad** [comment]
@HPaulJohnson any updates on this? We should send clubs info for on-going campaigns like privacy month, encryption, int women's day etc.

**Comment by HPaulJohnson** [comment]
We have Q1 pretty well set, starting with the encryption campaign that will kick off around privacy day. When that campaign is a little more shaped, we should talk about the best way to package and send to clubs.

**Comment by amirad** [comment]
That would be great @HPaulJohnson would love to send something about encryption/privacy before end of month!

**Comment by ldecoursy** [comment]
@amirad @HPaulJohnson Can we close this?

**Comment by amirad** [comment]
Probs. We'll go ad-hoc with the Mozilla campaign strategy and can reconvene around this later in the year.
