### ISSUE TITLE
[Tracking Ticket] Create 20-30 githubbed guides for clubs 

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#265]
Idea is to develop guides for clubs to use and develop github pages. 

cc @hannahkane will use this ticket to track completed ones

**Comment by jgmac1106** [comment]
I saw this idea in Kristina's blog post on the update.

My question is more philosophical, "Why are we pushing clubs to github
versus using Thimble?"
- Is it a mobile first issue (which should be first decision issue) and
  github pages will look better on mobile than Thimble?
- Is it a technical debt issue. Rather host the pages on github than on the
  thimble servers?
- Is it just about leveling up CC's? Encouraging open practice?

You spent a solid year building an awesome text editor. It seems odd to me
making the work flow of the RCs and CCs outside of a MLN product when that
product does what you want. Especially with the new markdown support.

**Comment by amirad** [comment]
@jgmac1106 thanks for the q's! The main thing to point out is that we started making club pages (aka the fact sheet, pages on how to do things and guides) in github before we relaunched the editor. Since we started in one, it makes sense to continue in one instead of doubling up the work and switching back to Thimble. Unless we wanted people to remix the guides, which we don't. But yes, we do have a style that we like in github and the mobile access is a huge benefit for more global community members. The guides range in how to tell your story, use social media, organize your club, brand your club etc. Sharing open practices and resources to building a great club

**Comment by jgmac1106** [comment]
Amira I mixed up my tickets I think. The guides make sense in github. I was
more referring to this:
https://github.com/riomozillaclub/activity-template

> form new activities for Mozilla Clubs. Our goal is to use markdown to write content, use issues to handle discussions, use wiki to handle extra documentation, use github pages system to distribute content, ultimately making the process for creating new Club activities more efficient.

Sorry to mix up issues.

**Comment by amirad** [comment]
Ha! No worries. Activities are a different situation and not associated with this work!

**Comment by omnignorant** [comment]
Note – and I'd be happy to continue this thread elsewhere – that I like the idea of using GitHub. Why not? We should use a diversity of tools in tandem. That's how successful people work: by building up a toolset and picking the one that suits the problem. I think it's cool if @soapdog develops lessons in GitHub. Dem's my 2 cents...

**Comment by jgmac1106** [comment]
+1 makes sense, and I'll be able to lurk and learn.

**Comment by soapdog** [comment]
@jgmac1106 the activity template was developed before the new thimble was ready. The advantages of using github over thimble in this case are:
- Leveraging the issues tracker to give feedback on the activity itself and coordinate translation work
- Use the revision control system to enable us to rollback changes or try prototypes without loosing content.
- Use the wiki to add tips & tricks and other meta information about the activity
- Github URLs are more memorable than thimble URLs.

In my personal vision we'll combine github features, discourse threads and thimble experiments.
