### ISSUE TITLE
Update auto-responder email for new club signups

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#267]
Idea is to send new clubs who sign-up auto email (which we already do) with the club questionnaire (that Kristina has been sending them afterwards). 

I wrote this old copy for this email: https://public.etherpad-mozilla.org/p/teach.clubsignupemail

@ldecoursy - this ok to do right? Should the reply go to teachtheweb@moz? @kgorr does that pad reflect the questions in the email you send? 

Will also need to add #262 to the email.

**Comment by KGorr** [comment]
@amirad I added the email copy that I am currently sending to the etherpad so that you can compare. The questions are slightly different.

**Comment by amirad** [comment]
Thanks @KGorr - I did a mashup of both email copy in the pad. 

@ldecoursy thoughts? https://public.etherpad-mozilla.org/p/teach.clubsignupemail  Should we give them a deadline to send it in by?

**Comment by amirad** [comment]
@ldecoursy @HPaulJohnson would love feedback on that email template for new clubs that sign-up so we can automate the questionnaire process and update the text. 
cc: @hannahkane

**Comment by HPaulJohnson** [comment]
@amirad comments in the pad. if you have questions about any of them let me know.

**Comment by ldecoursy** [comment]
My minor comments are in the pad too :)

**Comment by hannahkane** [comment]
Do we have final copy for this?

**Comment by amirad** [comment]
@hannahkane final copy here at the top https://public.etherpad-mozilla.org/p/teach.clubsignupemail I thought it had been updated though?

**Comment by hannahkane** [comment]
Yeah, we did this on Nov 26. Sorry, closed related ticket in Teach repo, but missed this one.
