### ISSUE TITLE
Complete research findings for training/on-boarding with club programs globally 

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#269]
Carolina has been doing a deep dive into how other orgs train/onboard. 

Step 1) Research on other programs 
- https://www.skillshare.com/teach
- https://www.codeclubpro.org/ or https://www.codeclub.org.uk/start-a-club/volunteers
- http://www.cs-first.com/training/welcome-cs-first
- Some other affiliates https://docs.google.com/spreadsheets/d/1JvIm1nAVBqtbOTwEpwzc_WyGL11Sx3QG5zSGUy1SQk8/edit#gid=0

Step 2) prepare analysis of common ideas and themes across programs.

**Comment by amirad** [comment]
cc: @Carotejada

**Comment by Carotejada** [comment]
Here is the file in which I'm working https://docs.google.com/presentation/d/13-NJGahOHVx9OUusnVe9N_OP0kpL6GYXo1QXP1vR1ME/present#slide=id.p

**Comment by amirad** [comment]
Looks great....does it make sense to do reward and recognition for club attendees, club volunteers/instructors or both?

**Comment by Carotejada** [comment]
Sure! I think we can find No cost or Low cost rewards for all of them!. Here are some conclusions. https://drive.google.com/a/mozilla.com/file/d/0BxN5635WjvALenRjb2htdVhUdkU/view?usp=sharing
