### ISSUE TITLE
Prepare proposal for on-boarding/training CC and RC 

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#270]
- Step 1) Develop proposal for how to on-board/train RC's and CC's and what media we need to do for it
- Step 2) Create ^ system. Test. Test. Test

cc: @Carotejada

**Comment by Carotejada** [comment]
This is the folder in which we are going to have the info https://drive.google.com/a/mozilla.com/folderview?id=0BxN5635WjvALTjJySmdqbzV2Zzg&usp=sharing

**Comment by Carotejada** [comment]
This is a wide description of possible needs that our club's users (Cc - Rc - Members) might have. The idea is to start creating a system which includes all the tools, guides, and online-training that they require to create and run Clubs all around the world. The goal is to give them autonomy, keeping Mozilla's inclusive, participatory & collaborative way. 

[clubs_draft1.pdf](https://github.com/mozilla/learning-networks/files/21769/clubs_draft1.pdf)

https://drive.google.com/open?id=1bsIE3Tjg6DjKQmK2txBaS20wBPg4DeXAQK275Xmjpgk

We are considering the suggestions that Rc and MoFo Staff members shared with us, and also some good practices from other organizations tat we found in the research.

**Comment by amirad** [comment]
Awsm. Thanks @Carotejada - feel free to continue to update links and tag me here!

**Comment by Carotejada** [comment]
First draft for Cc training modules template. 
[training templates.pdf](https://github.com/mozilla/learning-networks/files/23404/training.templates.pdf)

cc: @soapdog @amirad

**Comment by soapdog** [comment]
This template is awesome! 
:smiley_cat:

**Comment by ldecoursy** [comment]
Lookin good @carotejada!  

cc @hannahkane, as we should probably align with the design work underway for the curriculum templates (see https://github.com/mozilla/teach.mozilla.org/issues/1360 )

**Comment by hannahkane** [comment]
This is awesome! I've been following along on this ticket, but wonder if we could set up a time to go through all of these materials together and talk about how they might be presented on the site. 

Should we plan a meeting for post-MozFest?

**Comment by Carotejada** [comment]
Yes @hannahkane ! It would be great to have your help here :dancers: :dancer: :fireworks:

**Comment by amirad** [comment]
post-mozfest would be perfect.

@Carotejada let's focus on content for now then and loop back on design when we talk to Hannah. P.s. that template rocks!

**Comment by Carotejada** [comment]
Hey team,

During Mozfest I got a good suggestion from the Club Leader Zarah (Robert's wife) about a free online platform that she uses to manage her groups and students.

The platform  www.edmodo.com is the world's largest social learning community, and it  has good options for our clubs.

If you want to take a look of it, please email me to use my credentials.

Please let me know your thoughts about it.

![20151116_133540](https://cloud.githubusercontent.com/assets/14875631/11191344/c61f9fa8-8c68-11e5-9dd8-eed30e3a628f.jpg)

**Comment by amirad** [comment]
Hmm @Carotejada would this be for training or for club reports?

**Comment by Carotejada** [comment]
@amirad This would be for all the Clubs network, it would help us to connect MLN Staff, Cc & Rc. It would also help Cc and Rc to manage their groups, schedule activities, upload content and information, share makes, contact with other communities about Computer Science around the world.

**Comment by hannahkane** [comment]
Hey @Carotejada and @amirad - Edmodo looks awesome. It's very feature-rich, and I can see how it would be super useful to the Clubs network.

I have a bunch of questions. I'd love to be a part of a call if you're planning to meet about this soon.

**Comment by chadsansing** [comment]
Dittos to what @hannahkane said - would love to talk about channels for clubs & curricula.

**Comment by omnignorant** [comment]
FYI, I've been using to run my secret but not-so-secret Mozilla club as part of a larger student program. I'd be OK with letting one of you join as an instructor if you'd like to observe what it's like. I've been learning/working on my strategy for it too.

**Comment by ldecoursy** [comment]
I think they've been under fire re: data policies in the past, but definitely worth exploring further.

**Comment by chadsansing** [comment]
They did not protect sessions w/ SSL as recently as 2013, and they are [big money](http://hackeducation.com/2012/07/19/edmodo-25-million/). I'm curious to hear more from Robert. We used Edmodo in the mid oughties, so my perspective is likely dated.

**Comment by amirad** [comment]
Will set up a call for Friday at 11am ET and invite @hannahkane @chadsansing @Carotejada 
If anyone else wants to join just let me know.

**Comment by ldecoursy** [comment]
Happy to join too!

**Comment by amirad** [comment]
Cool. Added you to invite @ldecoursy

**Comment by ldecoursy** [comment]
@amirad @Carotejada Any updates or can we close this ticket?

**Comment by Carotejada** [comment]
Still open. Will add updates next week.

**Comment by ldecoursy** [comment]
OK just updated the milestone.

**Comment by ldecoursy** [comment]
I know @Carotejada is out - should we move this to next heartbeat?

**Comment by jgmac1106** [comment]
I use Edmodo as well but transitioned over to Known withknown.con as an
open source social network.

It is our club stream. They can be public or private.

We have discourse.webmaker.org as well could figure out ways for clubs to
use that with greater frequency.

**Comment by jgmac1106** [comment]
That being said clubs should drive their betwork choices at local level.
You want to use WhatsApp, Telegram, Facebook, Edmodo or wherever because
your audience is already there it makes sense.

**Comment by Carotejada** [comment]
Here is a synthesis of the work we are doing in order to build a system for Mozilla Clubs. 

https://drive.google.com/open?id=0BxN5635WjvALbXhtSFU5NUIxMzA

In collaboration with other teams (Curriculum, Design, Community members) we are creating resources, improving our media, and creating tools to train and give autonomy to our leaders (Cc and Rc). 

The greatest challenges are related to localization and web development. Since clubs are hugely diverse: geographically, culturally, etc...   we need to develop more tools for virtual interaction, as well as localized content to fulfill both universal and local needs.

**Comment by ldecoursy** [comment]
@amirad @Carotejada Can we close this?
