### ISSUE TITLE
l10n comms materials

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#277]
We need to draft and finalize the following materials to kick-off this campaign!

[ ] Blog post announcing campaign (@ldecoursy and @chadsansing)
[ ] Social media copy (@kgorr)
[ ] Other promo copy/emails/etc for targeted outreach (@ldecoursy)

Related ticket: #271

**Comment by ldecoursy** [comment]
Draft blog post is here for @chadsansing review/additions: https://public.etherpad-mozilla.org/p/wlbl10nblog

@soapdog can you also take a peek to make sure the step-by-step instructions are correct/clear?

**Comment by KGorr** [comment]
@ldecoursy Just added a bunch of tweet drafts to the etherpad below the draft blog post. I also added a couple of thoughts on the blog post and fixed a few typos.

**Comment by chadsansing** [comment]
@ldecoursy - done.

**Comment by ldecoursy** [comment]
Thanks @chadsansing. @soapdog, would love if you can review too.

cc @kevzawacki @HPaulJohnson @chrislarry33 In case you have time to review blog post above...

**Comment by HPaulJohnson** [comment]
@ldecoursy added some small comments to the pad. overall looks good and i'm excited we are doing this!
