### ISSUE TITLE
2015 MozFest Club's sessions 

### ISSUE THREAD

**Issue by Carotejada** [mozilla/learning-networks#281]
What does being participatory & playful in a learning setting look like?
https://docs.google.com/document/d/1gHj0oA_OnVVRmKeJkDptxiwBQjw9T9yRiroFPrOEnBg/edit?usp=sharing

**Comment by Carotejada** [comment]
How to increase digital literacy with women globally through on-going programs
https://docs.google.com/document/d/1GbVSf1McqppgfqHjiNHRaOYrWrdP9HK7SuHfgXMnJVA/edit

**Comment by Carotejada** [comment]
Teaching Web Literacy in the Open 
https://docs.google.com/document/d/1n4XjY7P7x_FuILO5bOq5TfVy2eLtzOg2MkpluLnBYnU/edit#

**Comment by Carotejada** [comment]
From participation to collaboration
https://docs.google.com/document/d/1BiJGy73w1npNe4PRgGgJQ39aaFS_EZPcqY7XnJkuRz0/edit?usp=sharing

**Comment by Carotejada** [comment]
Retaining and growing communities online and offline
https://docs.google.com/document/d/10iUdhPgsayyqCdPSkiervz3k7RT2DQkwMFFmDd3TfZQ/edit?usp=sharing

**Comment by ldecoursy** [comment]
Are these also being cross-posted on Medium or in a blog post anywhere?
