### ISSUE TITLE
Update Clubs logo link in welcome kit 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#285]
Per https://github.com/mozilla/teach.mozilla.org/issues/1415

Mozilla Clubs logo remix is now avail in new Thimble

cc @Carotejada @kgorr

**Comment by Carotejada** [comment]
Great! Thanks @ldecoursy

**Comment by amirad** [comment]
Awsm! Thanks @ldecoursy - updated the link/image on the Clubs fact sheet.

**Comment by amirad** [comment]
Also updated the logo in the Club Captain first month guides.
