### ISSUE TITLE
Follow Up Survey to the #TeachTheWeb Pledge Result???

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#286]
[Given that 81% of respondents](http://hannahgrams.com/2015/08/19/pledge-to-teach-survey-results-first-month/) in the first month said they want to turn to MLN for Professional Development we should drill down into the content more. 

Not sure if this should be a follow up survey link embedded in the first newsletter or direct contact with a random sample.

An open online PD experience will give users what they want and drive greater participation onboarding for MLN.

**Comment by ldecoursy** [comment]
Apologies for delay! Definitely working towards more polished PD offerings in 2016 :) Recently ran a web literacy leadership session at the National Writing Project's annual conference, and continuing to iterate on that with NYC DOE teachers as part of their structured PD program this winter. Both of those are in-person examples, but agree we can explore what an online experience looks like as well. cc @anmechung @chadsansing @Carotejada @jvallera

**Comment by jgmac1106** [comment]
Closing this as it seems there are many items in the work related to this issue. Looking forward to exploring it in 2016.
