### ISSUE TITLE
[Testing] [Intermediate Web Lit] CSS Circles

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#287]
Looking for bugs and typos in [CSS Circles](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/16686/).

**New:** [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session03-css-circles.html)

Content discussion on [Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-circles/375).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
Hey @chadsansing, this tutorial also has the weird formatting going on for me. It makes it hard to read since the words are smooshed together in some places, so ping me when it's fixed and I'll gladly do a read through.

**Comment by chadsansing** [comment]
@kgorr - thanks! It's a stylesheet bug that @flukeout is tackling.

**Comment by KGorr** [comment]
@chadsansing This still has weird formatting, but I went through it.

Thimble Tutorial:
Very 1st sentence “learn style the color,” the “style” shouldn’t be there.
jump links not working for me (nor back to navigation links)
Step 1
-paragraph 3 typo “sepcial”
Step 2
-paragraph 4 typo: “pafe”
Step 3 
-paragraph 2 typo :”three colore” and “differe”
Step 4
-paragraph 2 typo “circlees” [typo can be found twice]
Step 5
-paragraph 2 typo “circlees” 
-Relevant bullet “than to only the entire page.” is written awkwardly
4th paragraph typo “gthe”
-bullet #1: “a absolute” should be “an absolute” (again in paragraph 7)
-paragraph 7 typo “indepdently”

Teaching Kit
Mixing Color section
-#2 “a spossible” should be “as possible’  and also, 3rd sentence needs capitalized
-#5 typo “pissible”
Remixing color online section
-paragraph 2 typo “linke” and “classwebpage”
-paragraph 3 typo: “ablse” and “broswer”

**Comment by chadsansing** [comment]
Done. Thank you, @kgorr.
