### ISSUE TITLE
[Testing] [Intermediate Web Lit] CSS Blocks

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#288]
Looking for bugs and typos in [CSS Building Blocks](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/15991/) and its [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session04-css-building-blocks.html).

Content discussion on [Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-building-blocks/376).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
Minor typos found:

Thimble Tutorial:
Step 1 
-TL;DR typo “A .css stylesheet files” = “files” should be singular
-2nd paragraph typo: “(a sepcial label),”
Step 2: 4th paragraph typo: “pafe” should be “page”
Step 3 paragraph 3 typo: “wherver” and “verically” and “alwys”
paragraph 4 typo: “defauly”
Step 4 2nd paragraph typo: “l;ast “

Teaching Kit
6 block scramble section
-#6 typo: “nymber
Positioning Blocks section
-typo in paragraph 2: “shorten this “linke“  and “classwebpage “
-3rd paragraph: “ablse” and “broswer”
4th reflection bullet: “vertical” should be capitalized.

**Comment by chadsansing** [comment]
On the case, @KGorr - thank you!
