### ISSUE TITLE
[Testing] [Intermediate Web Lit] CSS Pyramid

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#289]
Looking for bugs and typos in [CSS Pyramid](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/19784/).

**New:** [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session01-css-pyramid.html)

Content discussion on [Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-pyramid/377)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
Here ya go @chadsansing:

Dino Drawing Template: “instructions” is misspelled in the header (will also need to upload the image embedded in the teaching kit

Thimble Tutorial:
None of the jump links are working for me
Step 1
-There’s an extra s after CSS in the subhead
-3rd paragraph typo: “broswer” and “stylsheet”
-4th paragraph “your” should be “you”
Step 2
-paragraph 3 typo “stylsheet”
-paragraph 4 typo “partof”
-6th paragraph “line 32 of index.html” is referring to the wrong line
-Also, this: “HTML:<div id="levelOne" class="textRow"></div>” is not exactly how it is showing up in the code… the CSS one is good though!
Step 3
-paragraph 3 typo “broswer”
-paragraph 4: check line references
Step 4 
-paragraph 3 & 4 typo “broswers”
Step 6
-paragraph 1 typo: “broswer“
-assuming this: “h2 or h2” should say two different things…
Very last sentence of the page typo “maniuplating”

Teaching Kit:
Drawing Dinos section:
-#7 typo: “diosaur”
-#10 typo: “thr group”
Reversing a Pyramind section
-1 st paragraph typo “made to back” should be “made it back”
-2nd paragraph typo: “stylsheets”
-3rd paragraph typo: “shoirten” and “linke”
-4th paragraph typo: “ablse” and “broswer”
-bullet #2 has an extra period at the end
Last reflection question typo: “HTNL”

**Comment by chadsansing** [comment]
@flukeout - similar issue here. External links won't work from the tutorial.

**Comment by chadsansing** [comment]
@kgorr - I appreciate the stellar assist. #notetoself: auto-find-and-replace stylsheet & broswer or invent them.

**Comment by flukeout** [comment]
@chadsansing The external links to MDN work for me from the tutorial in both Firefox and Chrome, not for you?

**Comment by chadsansing** [comment]
@flukeout - here I think it's the internal ones - sorry. The nav scheme.
