### ISSUE TITLE
[Testing] [Intermediate Web Lit] Webotron and the Scrambled Divs

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#290]
Looking for bugs and typos in [Webotron and the Scrambled Divs](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/17148/) and its [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session06-webotron.html).

Content discussion on [Discourse](https://discourse.webmaker.org/t/testing-intermedite-web-lit-webotron-and-the-scrambled-divs/378).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
Hey @chadsansing, the Scrambled Divs link doesn't go anywhere.

**Comment by KGorr** [comment]
Also, the step-by-step instructions are all kinds of wonky, in terms of formatting. 
![screen shot 2015-12-11 at 11 24 45 am](https://cloud.githubusercontent.com/assets/14793388/11749125/ec470bb8-9ff9-11e5-8c99-2fcf3dc1f1cf.png)

**Comment by chadsansing** [comment]
@kgorr, tutorial bug sent to the Thimble team on IRC. Thanks!

**Comment by chadsansing** [comment]
Fixed links from GH to Discourse. Thanks, @kgorr.

**Comment by KGorr** [comment]
I found a few more typos on this one, @chadsansing: 

Thimble Tutorial:
The jump links (and back to navigation links) still aren’t working 
Step 2 #3 typo: “horozontally”
Step 3 line call outs are incorrect
Step 4 paragraph one typo: “style.sss”
Check Step 5 line call out

Teaching Kit
Puzzling Out section
-#1 typo “elements and jusin”
-#6 typo, “compelted puzzle.”
Unscrambling section
-2nd paragraph typo “shorten this linke “
-3rd paragraph typos: “They will be ablse” & “broswer”
-Reflection bullet 5 typo: “CSS stylsheet”

**Comment by chadsansing** [comment]
Thnx, @KGorr! Working on it now. The link to the Scrambled Divs will be awesome one day.

Asked after the links on IRC a while back. No fix yet? @flukeout - any reason why internal nav schemes with anchors won't work in Thimble tutorials like this one?

**Comment by flukeout** [comment]
@chadsansing No fix unfortunately, yet - it's filed here https://github.com/mozilla/thimble.webmaker.org 
I'll see if in the interim, there is some kind of workaround.
