### ISSUE TITLE
[Testing] [Intermediate Web Lit] External CSS tutorials

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#291]
Curious about folks responses to [CSS Diner](http://flukeout.github.io/) (by @flukeout!) and [Flexbox Froggy](http://flexboxfroggy.com/). Particularly, would these work as next-to-last activities in a CSS module before a final, cumulative, user-designed 'final' project?

**New:** [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session07-external-css-tutorials.html)

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jgmac1106** [comment]
I have been playing with CSS Diner and Flexbox Froggy. I like them both. I
think they fall right in the spectrum of Intermdiate Web Lit or the start
of Intermediate Web Lit II or Advanced Wed Lit II.

I can play the games but being a novice myself I am not totally ready to
use these tools in my projects.
