### ISSUE TITLE
[Testing] [Intermediate Web Lit] CSS Fonts

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#292]
Looking for bugs and typos in [CSS Fonts](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/20997/) and its [lesson plan](http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session02-css-fonts.html).

Content discussion [here](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-fonts/401).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
A few things from me, @chadsansing 

Thimble Tutorial:

-jump links aren’t working
Step 2 
-paragraph 2: can you define “websafe” in case the reader doesn’t know what that means?
-1st bullet “Adobe Edge wbefonts” has typo
Step 3
-2nd paragraph typo “asnapshot”
-#3 has a different “replace this” link than what is actually in the code
step 4 
-paragraph 2 typo “HTNL”
-paragraph 3 typo “let's use decide”
-paragraph 5 line reference may be incorrect
-paragraph 6 “steylsheet.”
Step 5 1st paragraph typo “fontson”

Teaching Kit:
Word Wall 
- #5 typo : “taack”
- #7 typo: “fel”
  Using Webfonts section
- paragraph 3 typo “linke” and “classwebpage”
- paragraph 4 typo “ablse” and “broswer”

**Comment by jgmac1106** [comment]
You may want to put all the images into a folder to clean up the file tray.

**Comment by chadsansing** [comment]
New Thimble doesn't do folders...yet?

**Comment by hannahkane** [comment]
It does! Right-click in the file tree. We need to make that more clear, but it's there.

**Comment by chadsansing** [comment]
Sweet.
