### ISSUE TITLE
[Testing] [Intermediate Web Lit] CSS Decoration

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#293]
Tracking bugs and typos for the [CSS Decoration](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-decoration/409) activity currently under development.

Content discussion over on [Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-css-decoration/409).

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
@jgmac1106 et al., how would you teach this one? What kind of maker, participatory, and/or social activity would help either review basic CSS styling or help concretize text-decoration, text-transform, text-shadow, and box-shadow?

**Comment by jgmac1106** [comment]
I was thinking something like this but don't have time to fix it up. https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/12197/

This isn't right. I couldn't seem to center the inner div. It would need more spans to show inline decoration. But a fun t-shirt project would be cool.

I also think we could adapt the old movie poset make. That seems perfect for text decoration. 

Was thinking if we went with a Privacy t-shirt, billboard or bumper sticker, we could connect it to the upcoming campus campaign and Privacy campaigns in general.

Possible even tie in a much larger contest where the top ten picks are chosen by staff  are voted upon and top three are added to the gear store.

**Comment by jgmac1106** [comment]
Maybe a my three heroes project. Just trying to think of an organic situation when to use things like box shadow.

**Comment by chadsansing** [comment]
Will keep working towards that fun/organic/relevant center of the Venn diagram :) Thnx, @jgmac1106.
