### ISSUE TITLE
[Testing] [Design needed] Event Reporter

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#298]
Here is an event reporter built from @Carotejada's notes on how she structures documentation and reporting. It's built with a grid, rather than a table, but still needs design love, maybe some branding, and feedback, in general. 

Also, name?

GitHub version: http://chadsansing.github.io/curriculum-testing/documentation-and-reporting/index.html
Thimble version (~~soon~~ now with helpful tips!): https://d157rqmxrxj6ey.cloudfront.net/chadsansing/23644/ 
- https://d157rqmxrxj6ey.cloudfront.net/chadsansing/before.html
- https://d157rqmxrxj6ey.cloudfront.net/chadsansing/during.html
- https://d157rqmxrxj6ey.cloudfront.net/chadsansing/after.html

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chrislarry33** [comment]
Tagging @Saallen @edrushka

**Comment by stephwright** [comment]
Would it be useful to include link to any curriculum resources used?  Just thinking about ways to surface those while also getting an idea for how they get used.  

I like the layout and highlight questions!

**Comment by edrushka** [comment]
Are there any notes on what else is needed for this event reporter? Any additional context would be super useful.

**Comment by Carotejada** [comment]
This is the guide https://docs.google.com/document/d/1VyZPrFdcMK2Hr6-Tf_FiraiOi5o296kBYsa9QBD0SHE/edit?usp=sharing

This is a sample made in WordPress https://iteachtheweb.wordpress.com/2015/11/23/nwp/

And this could be a template on Thimble. https://d157rqmxrxj6ey.cloudfront.net/carot/24151/

**Comment by anmechung** [comment]
Love this!

**Comment by hannahkane** [comment]
@Carotejada - was your version created specifically for Clubs? asking because, if so, we can use it as a template for the event reporting aspect of the Clubs Portal.

**Comment by Carotejada** [comment]
@hannahkane It was created to report training events, but definitely applicable for our clubs.

**Comment by chadsansing** [comment]
@stephwright -links area sounds right.

This version (built from the guide) - https://d157rqmxrxj6ey.cloudfront.net/chadsansing/23644/ - needs design love. 

We can also move forward with this version - https://d157rqmxrxj6ey.cloudfront.net/carot/24151/ - if that's the consensus. Though if we move to design an event reporter with a curriculum template, it might be worth exploring how the new template works as a reporter, too.

**Comment by Carotejada** [comment]
+1 @chadsansing. That template for curriculum needs design love (and branding) to evolve in a report template.

**Comment by chadsansing** [comment]
Not sure where to go with this...or close? @Carotejada, @amirad, @hannahkane

**Comment by Carotejada** [comment]
@chadsansing I know this template can be muuuuuch more cute, but we can try to test it. I think we need to improve the code and create the tutorial.  Once we are sure it works we can request for help again.

https://d157rqmxrxj6ey.cloudfront.net/carot/25752/

What do you think?

**Comment by chadsansing** [comment]
Sure; I would continue working with design to refine the template. This design is reminiscent of a curriculum template from 2 or 3 iterations back and might cause confusion about which one we're using now. Otherwise, if it captures what clubs wants to capture, awsm.

**Comment by Saallen** [comment]
Hey lovely people, I played around with both templates over the last week and this morning. Loving the last version updated- found it easier to remix and made more sense as a reporting tool for events.  I found the new layout easier to work with and the flow was well mapped. 

I was confused though by the expectations for this doc- 
My expectations was this was a place for me to record my event- so I added the name, date, and some more details.
I did get a little flustered at the last Materials and links piece- as I felt that my materials were my lesson remixes or curriculum pieces I used during the event. So when I saw the links bit.. I didnt know if this was for what I or audience built during the class or if this is where I added the webpages I used during the class. As it would be very cool to have a place here I could link to the class makes for future reference.
When I reviewed the page once I was finished the first line of the latest doc threw me-
![screen shot 2016-02-01 at 13 01 59](https://cloud.githubusercontent.com/assets/10194015/12718084/10992a4c-c8e4-11e5-9139-49fff3fea8b7.png)
Is this page supposed to be used pre event?

There are a couple of other small additions I would recommend for this if its used post event
- Having the key learnings/ areas you would change for the next event as a separate paragraph
- Instead ask as highlight 3, describe something that happened that you were not expecting or that required you to think on your feet or remix your agenda. I like having these highlights as somewhere to map out what actually happened before I then take time to review what worked on the day or not.

Sorry my feedbacks late and hope it makes sense. You can see my remix [here](https://thimble.mozilla.org/user/saraha/109344)

:cake:

**Comment by chadsansing** [comment]
@Saallen, can you ship the URL of the published project instead of the editing screen? I can't seem to get the remix to load :( Thanks for such thorough feedback!

**Comment by Saallen** [comment]
Sure can [Try this one](https://thimble.mozilla.org/user/saraha/109344)

**Comment by Carotejada** [comment]
Love you @chadsansing and @Saallen

**Comment by amirad** [comment]
@Saallen definitely post-event recap. Also, I can't seem to get either of those links you posted to work :(

**Comment by Saallen** [comment]
@amirad try this one https://d157rqmxrxj6ey.cloudfront.net/saraha/29243
:question:

**Comment by amirad** [comment]
It works! Thanks @Saallen

**Comment by chadsansing** [comment]
@amirad - is there an mvp? Can we close?

**Comment by amirad** [comment]
We can close. I'll list this one as a resource for clubs https://d157rqmxrxj6ey.cloudfront.net/carot/25752/
