### ISSUE TITLE
Update text for teach.com/clubs

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#304]
Need to revise and update text here: https://docs.google.com/document/d/1UCVBy4X5Tl4mX4GDdSNwCcR8WzGu3cUyHv40FilqFZM/edit

**Comment by ldecoursy** [comment]
@amirad Still need this ticket?

**Comment by amirad** [comment]
Yup....we do!

**Comment by hannahkane** [comment]
Closing since copy is finalized.
