### ISSUE TITLE
[Rio Mozilla Club Report 2014-2015] How The Venues Changed

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#305]
This issue is a part of the Rio Mozilla Club report that is being tracked by the #299 meta bug. It is tracking a section of the final report called **How The Venues Changed**.

What happened to the venues originally visited by our team? How  their users changed after our initial report?  

This will be done through a series of interviews with LAN House owners, employees, clients, our volunteers/facilitators and staff.
## 

Data needed:
- [x] Create interview questions
- [x] Interview with volunteers
- [x] Interview with staff
- [x] Interview with owner, employees and clients from **Super X Rio** Lan House
- [x] Interview with owner, employees and clients from **KauMath** Lan House
- [x] Interview with owner, employees and clients from **CID Matrix** Lan House
- [ ] Interview with non-participating LAN Houses

**Comment by soapdog** [comment]
## Tentative interview questions

All interviews will include basic data such as name, age, location...

## Volunteers
- What is Web Literacy for you?
- Why is it important?
- Why are you a volunteer?
- Why Mozilla?
- Has this program changed you? How?
- What is your favorite story so far?
- What could be improved?

## Staff

Why Mozilla clubs?
What opportunities for web literacy and leadership development do you see in our program?
What is your favorite part of the program?
What could be improved?
What is your favorite story so far?
What is our strength?

## LH owners
- Has this program changed the way you approach technology? How?
- Do you see any difference/change in the way the club members/LH users approach the internet? Please explain.
- What do you think about the program?
- What is the program strength?
- What could be improved?
- What is your favorite story so far?
- Did the program changed anything related to how you conduct your business?

## LH clients
- Why do you come to the club meetings?
- What is your opinion about the program?
- What do you like the most about it?
- What could be improved?
- What you dislike about the program?
- Has the program changed the way you approach technology and the internet? How?
- What has been your favorite moment?
- What you've learned that impressed you the most?
- Have you told/taught what you learned here to someone elsewhere?
- Would you recommend Mozilla Club to your friends/family ?
- What do you think about the Web? Is it important to you? Why?

## 

CC @amirad @Carotejada what do you think of those questions?

**Comment by amirad** [comment]
@soapdog added edits to the questions below (and sorry for the accidental slip and close of ticket!)

Tentative interview questions

All interviews will include basic data such as name, age, location..._add job/position/work if applicable_

Volunteers

```
What is Web Literacy for you?
Why is it important?
Why do you choose to volunteer?
Why Mozilla?
What have you learned from this program? How have you been impacted?
Do you have a favourite teaching or learning moment to share?
How do you think the program can grow and improve?
```

Staff

Why is Mozilla clubs important in Rio?
What opportunities for web literacy and leadership development do you see in our program? Have you felt this impact directly?
Do you have a favourite part of the program or way that the program impacts you directly?
How do you think the program can grow and improve?
Do you have a favourite teaching or learning moment to share?

LH owners

```
Has this program changed the way you approach technology? How?
Do you see any difference/change in the way the club members/LH users approach the internet? Please explain.
Do you think the program has value? In Lan Houses?
What is the program strength?
How do you think the program can grow and improve?
```

Do you have a favourite teaching or learning moment to share?
    Did the program changed anything related to how you conduct your business?

LH clients

```
Why do you come to the club meetings?
Do you see value in club meetings?
What do you like the most about it?
What could be improved?
What you dislike about the program?
Has the program changed the way you approach technology and the internet? How?
What has been your favorite moment?
What have you learned that impressed you the most?
Have you told/taught what you learned here to someone elsewhere?
Would you recommend Mozilla Club to your friends/family ?
What do you think about the Web? Is it important to you? Why?
```

**Comment by soapdog** [comment]
Still want to interview some more Club members...

**Comment by soapdog** [comment]
First batch of interviews are here: https://docs.google.com/a/mozilla.com/document/d/1UvWQWc40HKsjLauMpybVP5gEZHzuL8afaN8EJe39DjY/edit?usp=sharing

We still interviewing some more Club members and facilitators but thats the initial 10 interviews. Already more than 15 pages of material.

**Comment by soapdog** [comment]
How each venue changed over the year: https://docs.google.com/a/mozilla.com/document/d/1VCSs4XSYaRDRA8ySB7iUQBc2W344WPvcLLK5RKWwnow/edit?usp=sharing
