### ISSUE TITLE
[Testing] [NWP Letters to the Next President 2.0] Letters to the Next President template

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#310]
Everything is up for comment - typos, bugs, content.

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24389/letter-template.html

cc @ldecoursy, @KevZawacki

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by anmechung** [comment]
Perhaps @ldecoursy and @KevZawacki are planning to add already, but some kind of general intro paragraph with who and why would be helpful, and perhaps some examples of what people could include in the template/madlib? We did something like this with NWP in the past - will unearth if I can find it and share.

**Comment by ldecoursy** [comment]
I like it! @anmechung We're planning to build a landing page that will lead to this and other activities, so we'll definitely have some added context there.

**Comment by chadsansing** [comment]
@anmechung, @ldecoursy, & @KevZawacki: any better?

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24389/

Updated the landing page for the letter template. Happy to collaborate on copy!

**Comment by KevZawacki** [comment]
@chadsansing Looks great! One very small tweak to the landing page:
- Add a period to the last sentence of the last paragraph

**Comment by chadsansing** [comment]
Thanks, @KevZawacki!

**Comment by ldecoursy** [comment]
I heard back from NWP - they think it's important for this activity to have a tutorial. Can we maybe remix the tutorial from the 6-word summer activity? https://thimble.mozilla.org/anonymous/3826fec7-fe95-4dba-aee2-09ddd4a04ca5/2500

**Comment by anmechung** [comment]
@ldecoursy make sense and what kind of tutorial are they looking for? i.e. what's the purpose of it? make a poster, a campaign slogan to go along with the letter?

**Comment by ldecoursy** [comment]
@anmechung An embedded tutorial in the activity so teachers/learners know have the step-by-step instructions for what to do with the remixable letter.

**Comment by chadsansing** [comment]
@ldecoursy & @anmechung - done ([intro page](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/24389/)) and done ([letter template](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/26231/)). Feedback appreciated.

**Comment by jgmac1106** [comment]
It might just be my display size but I see the background image not filling
leaving me with a white bar down the right and they your two div box with
the quote bleeds over. I am sure most students will be working on a smaller
display so it may be a non-issue.

**Comment by jgmac1106** [comment]
The tutorial is great. The only issue is line numbers after we tell them to
edit line 44. If they add more than one line all the other line numbers in
the tutorial are off.

Maybe something like:

The letter is separated into paragraphs. Paragraphs open and close with the
p tag. In the first paragraph which starts on line 44 you...

In the next paragraph you...

You already have these in the html comments maybe just duplicate this or
connect the two chains of thought.

**Comment by chadsansing** [comment]
@jgmac1106 - I think switching from fill to cover solved the background image problem. Will mull line breaks, maybe default to paragraphs, but each element takes up a line. For example, each paragraph is a line. If a user adds a paragraph or deletes one, then we'll run into issues.

**Comment by jgmac1106** [comment]
Yeah I have never figured out the best way to suggest line numbers for when
the content starts moving.

**Comment by chadsansing** [comment]
I guess there are anchors, names, etc. for that, but it would be cool to pin a line.

**Comment by jgmac1106** [comment]
The anchors and names then make a simple project just a little more complex. You could also leave extra line spacing in the index file but thats bad practice. Still always willing to break a few rules to support learning.

Being able to pin and click from tutorial yeah be a cool feature for down the road if it is technically possible.

**Comment by anmechung** [comment]
@chadsansing intro page and letter template look good to me.  For sense of purpose, can there be some kind of explanation for youth as to how these letters get to the Presidential candidates, whether they should expect a response, what kind of impact it might have (example from past efforts?).  Also, I may have missed this, but what is the 2.0 of Letters of President 2.0 mean?

**Comment by chadsansing** [comment]
@ldecoursy - ideas/suggested copy re: purpose? 

@anmechung, "2.0" = second time they've done the campaign.

**Comment by ldecoursy** [comment]
Purpose q's might be something to check with NWP on - maybe we can add a note to share their published links with #nextprez as one way to find finished letters.

**Comment by chadsansing** [comment]
@ldecoursy, @KGorr, @anmechung, @jgmac1106 - simple quote project to complement the letter' campaign poster and Goggles annotation activities forthcoming.

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/29280/

Feedback appreciated.

**Comment by KGorr** [comment]
Nice job, @chadsansing - I love it!

Two teensy things: 
The 1st Creative Commons link has a typo, and thus not working.
Step 4 has a typo: Beccause

**Comment by Carotejada** [comment]
Buenísima! That´s my Candidate.

**Comment by chadsansing** [comment]
[Campaign poster](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/29290/) also taking shape, @ldecoursy, @KGorr, @anmechung, @jgmac1106.

@flukeout, my positioning skillz are lacking; how can I stick the slogan div to the bottom of the poster div so it doesn't slide up in smaller viewports?

**Comment by flukeout** [comment]
@chadsansing There is actually a typo in your CSS, you're missing a semicolon at the end of the `position: realative` line which is causing it to get ignored, that's why the slogan styles aren't taking.

Additionally, for the `.slogan` you can use `bottom: 0` instead of `top: 650px` - that will put it 0 pixels from the bottom of the `.poster` so even if your poster gets taller, it will render as expected.

Screenshot of the busted rule from the Firefox inspector panel...
![image](https://cloud.githubusercontent.com/assets/25212/12725412/6c9aaaae-c8c7-11e5-925e-4d6bc824711c.png)

.

**Comment by chadsansing** [comment]
Yeah; I did the top thing since the bottom one wasn't working; oh, semicolon; how dastardly art thou; aren't thou? Thanks, @flukeout -

**Comment by anmechung** [comment]
@chadsansing like the poster very much, but I would perhaps choose a photo/animal that is more party neutral.

**Comment by chadsansing** [comment]
@anmechung, Socks is gone; meet Candidate Kitteh: https://d157rqmxrxj6ey.cloudfront.net/chadsansing/29280/.

**Comment by flukeout** [comment]
Hey @chadsansing  I have a cool CSS rule for you to try- **calc()** for the `header` width. It does a calculation based on what's inside of the parentheses.

```
header {
  background-color:#fff;
  border: 4px solid #070201;
  border-radius:10px;
  opacity:.8;
  padding-left:1em;
  width: calc(100% - 200px);  /* <-- the calc() */
}
```

This will make the header always leave the same amount of space for the Remix button, at any width of the browser. When you set it to 90%, it sometimes leaves enough room but sometimes not. Anyway, it's a cool way to do widths and heights!

I'm not sure if 200px is the right width, just using it as an example - try it out and let me know if it's helpful.

**Comment by chadsansing** [comment]
Swag, @flukeout. Will implement here and in a few other makes, as well.

**Comment by anmechung** [comment]
:)

**Comment by chadsansing** [comment]
Closing for now as we have several templates and activities in-hand.
