### ISSUE TITLE
Publish l10n campaign blog post 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#311]
@kgorr Let's publish this once the links are live on teach.mozilla.org per https://github.com/mozilla/teach.mozilla.org/issues/1537

**Comment by KGorr** [comment]
Great! Draft is up on WordPress, and I will update copy as needed once links go live.

**Comment by ldecoursy** [comment]
Published! https://blog.webmaker.org/web-literacy-basics-i-now-available-in-11-languages
