### ISSUE TITLE
Outline plan for disseminating localized content 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#312]
cc @amirad 

Let's figure out best ways to share localized web lit I localized content with Clubs and the network at large

**Comment by amirad** [comment]
That would be great! All I have so far to share is the dashboard https://d157rqmxrxj6ey.cloudfront.net/andregarzia/17163/

**Comment by ldecoursy** [comment]
@amirad can we close this?
Blog has been posted, think @soapdog is sharing with Reps, and we've shared with RCs, CCs, right?

**Comment by amirad** [comment]
Good to close!
