### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Update copy

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#315]
Revise the Thimble workshop curriculum copy to face IPPD audience.

@chadsansing, @anmechung 

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ldecoursy** [comment]
Moving milestone date, we set internal deadline of Feb 5.
