### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Update OER page 

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#316]
Update the OER page to incorporate Smithsonian materials.

@anmechung 

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ldecoursy** [comment]
Moving milestone date, we set internal deadline of Feb 5.

**Comment by ldecoursy** [comment]
@anmechung Any update here?

**Comment by anmechung** [comment]
same as my other response - yes

**Comment by anmechung** [comment]
@chadsansing could you remove National Writing Project from 3rd line from the top, and change the time in the 5 min button on the right to 15 min? https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/oer.html

**Comment by chadsansing** [comment]
@anmechung, should be correct now.
