### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Finalize Thimble workshop curriculum

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#318]
Finish revising and updating the [Mozilla Web Literacy Leaders workshop curriculum](https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22146/) in Thimble.

@chadsansing

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by chadsansing** [comment]
[New 'Hack the News' with new Goggles](http://chadsansing.github.io/curriculum-testing/spring-2016-ippd-training/new-hack-the-news.html).

**Comment by jvallera** [comment]
Here are some ideas I have for spectogram prompts that may be more specific to these folks (although I think the prompts we already have on in the thimble would work fine too: 
1. Grade school learning environments are being transformed by technology.
2. Using the internet brings creativity into the classroom
3. It is important to teach kids to code
4. My lesson plans and curriculum should be available online for other teachers to access and use freely.

**Comment by chadsansing** [comment]
These look good - mix and match with @anmechung until you have your favorites?

**Comment by chadsansing** [comment]
@jvallera re: your GDoc comment, I believe we have moved on to https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/ for the site and https://docs.google.com/presentation/d/1oeVBR-oC5c18es5bhhB4YFtHkCUjTGEsSkbLBkm9kDk/edit#slide=id.g1189e13553_0_0 for the introduction preso.

**Comment by jvallera** [comment]
Great. Thanks! The header image doesn't seem to be loading for me here https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/

**Comment by jvallera** [comment]
The links in the privacy activity don't work for me. Is it just me? https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22516/

**Comment by chadsansing** [comment]
@jvallera - no header yet. Do you have a favorite NYC DOE picture to use? The links were blocked by a div element that I removed. Page is a little broken, layout-wise now, but not too bad.

**Comment by jvallera** [comment]
Here are some good ones from the last IPPD we did: 
https://www.flickr.com/photos/newyouthcity/16304513515/in/album-72157650350884885/
https://www.flickr.com/photos/newyouthcity/16118666097/in/album-72157650350884885/

**Comment by chadsansing** [comment]
@jvallera, cool to use these? All rights reserved by HiveLearningNYC.

**Comment by chadsansing** [comment]
Updated reflection & next steps page. Closing for now.
