### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Food

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#319]
Arrange breakfast and lunch for the workshop.

@jvallera, @jazoulai

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jazoulai** [comment]
@jvallera are we still thinking bagels/coffee for breakfast and pizza for lunch?

**Comment by jvallera** [comment]
Yes, perfect @jazoulai with some OJ for breakfast and seltzer/soda for lunch

**Comment by jvallera** [comment]
Breakfast arriving at 8:30 
Lunch arriving at 12 noon
