### ISSUE TITLE
Plan message arc to 4000 contributor list and write first copy

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#32]
This issue has been migrated from mozilla/teach.webmaker.org#65.

It was originally written by [amirad](https://api.github.com/users/amirad) on Wed Feb 18 2015 and had the following description:

> Once we group the 4000 contributors in Q1 we need to dive into a plan on when we will be communicating messages to them and what the CTA will be. Should have rough copy ready for Q2 and launch of club material. 

On Wed Feb 18 2015, [amirad](https://api.github.com/users/amirad) commented:

> **@****HPaulJohnson** - we should plan out the arc and plan for rough copy

On Wed Feb 18 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> **@****amirad** let's schedule a time to discuss and invite **@****KevZawacki**

**Comment by ldecoursy** [comment]
Outdated, closing.
