### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Finalize space logistics 

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#320]
Work with Ariam at Global Kids to finalize space arrangements and firm-up set-up and tear-down times.

Ariam, @jazoulai

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ldecoursy** [comment]
@jazoulai  Can you share updates here when you have them?

**Comment by ldecoursy** [comment]
@jvallera @jazoulai Can you please add details here re: what time we can arrive to set-up? Anything else we need to keep in mind or plan for?

**Comment by jvallera** [comment]
We can set-up at 8:15AM, Ariam can get there early to let us in. We need a list of participants to send in advance to give to security guard. @Carotejada maybe you can get us the RSVP list end of next week? They have markers and poster paper we can use. They also have 10 laptops.

**Comment by Carotejada** [comment]
@jvallera por supuesto. I'll send it to you then.
