### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Print agenda and scoresheet

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#321]
Print the workshop agenda, including bit.ly links for the  curriculum and survey. Copy the privacy game scoresheet on the back.

@ldecoursy 

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ldecoursy** [comment]
@jvallera Unfortunately our new printer hasn't arrived yet. If things are ready to be printed next week, would you mind sending along to Park Slope Copy - you can submit online and they'll deliver (unless you know a place closer by).

**Comment by jvallera** [comment]
@ldecoursy sure. I want to make sure I have the correct list of things to print:
1. Tag Tag revolution cards
2. This Page (agenda): https://docs.google.com/document/d/1CeGjpvU99lGgrfKU9LJL4sZL2_1SUZSiCCZIVYLj7w4/edit?pref=2&pli=1 (35 copies w bit links)
3. Bit links for curriculum and survey (on agenda)
4. Scorecard for Privacy activity: http://chadsansing.github.io/curriculum-testing/spring-2016-ippd-training/privacy-game-scoresheet.pdf

@anmechung @chadsansing anything else I am missing to print?

**Comment by chadsansing** [comment]
@jvallera - looks right. Let' use this **NEW** URL for the workshop & bit.ly links:

https://d157rqmxrxj6ey.cloudfront.net/chadsansing/31650/

Maybe the agenda and scoresheet can be front/back.

Would love to see at least the above URL and the Discourse URL on the agenda sheet.

cc @ldecoursy

**Comment by jvallera** [comment]
[PRINT - MozillaWebLiteracyLeadersKick-OffAgenda.pdf](https://github.com/mozilla/learning-networks/files/136886/PRINT.-.MozillaWebLiteracyLeadersKick-OffAgenda.pdf)
@chadsansing @anmechung Here is the agenda I will print. does this look good to you?

**Comment by anmechung** [comment]
+1

**Comment by chadsansing** [comment]
Thanks, @jvallera - looks sound to me!

**Comment by jvallera** [comment]
great! will send to print this week.
