### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Print Tag-Tag-Revolution cards

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#322]
Print tag-Tag-Revolution cards for the workshop.

@jvallera 

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ldecoursy** [comment]
@jvallera Same here re: printer (if we don't have one, Park Slope Copy is a good bet)

**Comment by jvallera** [comment]
printed at P.Slope copy. picking up on Monday.
