### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop - Develop assignments and CTAs between events

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#324]
Develop assignment prompts and CTAs for participant engagement on Discourse between the workshop and closing celebration.

@anmechung, @jvallera 

[Back to IPPD meta issue.](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by jvallera** [comment]
Idea for assignment - three things:
1. Complete one of the following assignments or propose your own:
   Remix Hack the news or incorporate into an activity/lesson plan (i.e. have students create a newsletter for school)
   Remix letter to the next president activity and incorporate into an activity/lesson plan.
   Use thimble to create concept poster for your classroom and/or an assignment & have students remix it.
   Create at least one OER activity that uses what they learned in this workshop.
   Remix this workshop and use it to teach peers and/or students. 
2. Participate in at least one follow up call (time TBD) in between workshop and celebration. 
   option 1: Time, date
   option 2: Time, date
3. Provide at least two updates in the discussion (discourse) between the workshop and the celebration.

@anmechung thoughts?

**Comment by anmechung** [comment]
@jvallera Looks great. you are awesome!

**Comment by ldecoursy** [comment]
@jvallera @anmechung 

Here are two things we listed as requirements in the IPPD program overview: 
- Develop at least one remixable open education resources (OER) (activity + lesson plan) using Thimble, that connects web literacy and 21st Century skills with your subject area
- Participate in discussions by sharing at least three posts in our community forum–one about planning or process, one with useful feedback to someone else’s post, and a final reflection, sharing testing data and/or feedback from students.

Seems like there are a few discrepancies with the assignment you detailed above. Also, did you discuss how/when/what to send to participants in Discourse during the period between the kick-off and celebration? Additional prompts to spark discussion, or encourage them to collaborate/share feedback with each other... I think we should have a cadence (1x/week or every other week) with specific dates to intentionally check in, have a CTA, encourage engagement, etc. 

LMK what you think or what else you've discussed.

**Comment by anmechung** [comment]
I think we've actually broaden what we required in the program overview and given people more opportunity to be innovate and creative. We can certainly get more specific by requiring 3 posts, and if you see in what Julia has written we did plan to have specific dates for check-ins.   Don't worry - I know you are away next week, but it will all be done.

**Comment by jvallera** [comment]
ok. Updated here to incorporate @ldecoursy suggestions...discussion prompts are flexible, just threw some out there as placeholders, but we can adapt week to week. 

Assignment:
**1. Complete one of the following assignments or propose your own:**
-Remix Hack the news or incorporate into an activity/lesson plan (i.e. have students create a newsletter for school)
-Remix letter to the next president activity and incorporate into an activity/lesson plan.
-Use thimble to create concept poster for your classroom and/or an assignment & have students remix it.
-Create at least one OER activity that uses what they learned in this workshop.
-Remix this workshop and use it to teach peers and/or students.

**2. Participate in at least one follow up call (time TBD) in between workshop and celebration.**
option 1: Time, date
option 2: Time, date

**3. Provide at least three updates in the weekly discussion (discourse) prompts between the workshop and the celebration. These updates can be about planning or process, useful feedback to someone else’s post, a final reflection, sharing testing data and/or feedback from students.**

Week 1/Prompt 1: What are you most interested in/excited about working on in the coming weeks?
Week2/Prompt 2: What assignment did you choose to work on and how do you plan to implement it?
Week 3/Prompt 3: What challenges have arisen so far? Do you have any adaptations or suggestions based on what you've experimented with?
Week 4/Prompt 4: TBD
Week 5/Prompt 5:  T

**Comment by chadsansing** [comment]
@jvallera, could we provide Hack the News and the letter as examples of OER, but make the assignment about creating a new one, which might be a web literacy workshop for peers?

Maybe Week 4 could ask about plans for testing and Week 5 could be about where teachers plan to share their work in the open?

Other thoughts?

cc @ldecoursy, @anmechung

**Comment by jvallera** [comment]
Sounds good to me @chadsansing

**Comment by anmechung** [comment]
+1

**Comment by anmechung** [comment]
added everything here for eventual upload to thimble page: https://docs.google.com/document/d/1MrtbllDpJrfeEgLVGCBwvtrV5eeSH8a9dnA691xc8fg/edit

**Comment by chadsansing** [comment]
@anmechung, @jvallera - any more work here, or are we ready to close?

**Comment by jvallera** [comment]
@chadsansing yes, we are finished. As long as you have all you need for the thimble page. ;)

**Comment by chadsansing** [comment]
I think so. Many thanks! Closing.
