### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Workshop: Hive NYC blog post

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#325]
Post short blog on hivenyc.org to promote last week for IPPD sign-ups, including info about our program.

@jvallera or Joey

**Comment by jvallera** [comment]
@ldecoursy gotcha. focusing on the web lit training curriculum and outcomes? what day do you think it should be published?

**Comment by ldecoursy** [comment]
I think it can be more like a call for signups. A blog post version of the program one-pager with a reminder that there's still time to sign up. Maybe post on Monday or early Tues.

**Comment by ldecoursy** [comment]
#313

**Comment by chrislarry33** [comment]
Yeah, basically a cut/paste job

**Comment by ldecoursy** [comment]
Posted! http://hivenyc.org/2016/01/21/free-web-literacy-training-with-mozilla/
