### ISSUE TITLE
Spring 2016 IPPD Web Literacy Leaders Training - Acceptance Letters

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#326]
Prepare and send necessary acceptance/rejection materials.

@jvallera 

[Back to IPPD meta issue](https://github.com/mozilla/learning-networks/issues/313)
[Back to issues](https://github.com/mozilla/learning-networks/issues/)

**Comment by ldecoursy** [comment]
Draft from previous session: https://docs.google.com/a/mozilla.com/document/d/1O2C1zXJHhbyYumwpwUjhSxMyWbQyJxzB5vFYP2T915Q/edit?usp=sharing

**Comment by ldecoursy** [comment]
Here's an updated version of the acceptance letter: https://docs.google.com/document/d/1sc_LpIcJMKAPHOMc49ygmMmcn6yRpW2xOqddae9WhAo/edit

**Comment by ldecoursy** [comment]
Letter is updated and ready to go. @Carotejada to send and mark on the master IPPD spreadsheet that we're accepting all applicants.

**Comment by Carotejada** [comment]
RSVP application sent https://www.eventninja.io/e/web-literacy-leaders-winter-ippd-2299
