### ISSUE TITLE
[Community Engagement] Set up a YouTube account/channel for Mozilla Curriculum Workshop

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#327]
@kgorr, can you create a YouTube account for the curriculum workshop webcast and share the keys with me and @KevZawacki?

cc @ldecoursy

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
@chadsansing, @ldecoursy and I are working on getting the proper credentials to make this happen. Will update you as soon as we can. Thanks!

**Comment by chadsansing** [comment]
See also [#330](https://github.com/mozilla/learning-networks/issues/330).

**Comment by chadsansing** [comment]
Looping in producer @ohnopauloh.

**Comment by jgmac1106** [comment]
Okay total snark but the trying to get back the YouTube credentials has
been such an ongoing storyline I have to admit to giggling a little bit.

I think MLN should just make their own account.

**Comment by KGorr** [comment]
We're blocked on the official YouTube account, so I created another and have provided the info to those who need it. Testing will start next Tuesday!

**Comment by ldecoursy** [comment]
Closing this for now. Tracking progress on official account here https://github.com/MozillaFoundation/plan/issues/715
