### ISSUE TITLE
Add teach.mf.org to desk.com

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#328]
We're ready to transition teach.mf.org emails into desk.com. @adamlofting has agreed to help :)
@kgorr and I have access to the recipient list via Google Groups.

@stephaniemcv offered to help get macros set up - we can open a separate ticket for that once the emails are being forwarded.

**Comment by ldecoursy** [comment]
@adamlofting Are you still able to help add teachtheweb@mozillafoundation.org to desk.com?

**Comment by adamlofting** [comment]
I've setup the rules and filters in desk.com now,

If you can start forwarding the emails to: teach@webmaker.desk-mail.com this should be good to go.

**Comment by ldecoursy** [comment]
Belated thanks @adamlofting :) Closing now.
