### ISSUE TITLE
Compare online training platforms

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#331]
Investigate 4-6 training platforms and compare based on the following factors:
- cost
- mobile friendliness
- user-friendliness, customer reviews
- localization options
- integrated login options
- features

/cc @amirad @Carotejada @flukeout

**Comment by hannahkane** [comment]
Question for @amirad and @Carotejada - are all of the training modules meant to be self-directed? That is, do students start and end whenever they want, as opposed to, for example, having certain modules that are only available during a specific time?

**Comment by jgmac1106** [comment]
I also question if these have to be a separate product. I have been fooling
around with trying to develop all of my classes in Thimble

I link to:
Syllabus https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/24508/
Class (only first two modules released)
https://d157rqmxrxj6ey.cloudfront.net/jgmac1106/25881/

I also use Known (FOSS) as my class stream. This works very well.

What is not built in would be the learning analytics or assessment
capabilities that may come with other full blown training platforms....but
I don't always agree with the types of learning these instruments currently
surface.

Much better to have learners reflect on their own learning and present some
type of portfolio we could credential.

**Comment by Carotejada** [comment]
Hola @hannahkane!!! modules should be available for a specific time once you start them. 

@jgmac1106 you are mastering Thimble! I can tell all the work behind those creations. 

Regarding the platforms, we are currently trying to define which tools work better for each type of content. For example, we are using **Thimble** for club's remixable activities; **Github** for non remixable club site pages and guides; and we are hoping to find a "**Ready to Use Online Platform**" for the training modules.

Why do we believe a platform like this is needed? Different reasons: 
- Our audience: is "out of the classroom", and it is also massive and geographically disperse. So we need the analytics.
- Friendly CMS: we want to upload content easily (no coding skills needed). 
- Easy and interactive activities: ready to use platforms offer activities which can be easily created.  

We have played with [Versal](https://versal.com/), and we want to compare it with a few more. 

Would appreciate your feedback on this reasoning! All we expect is to deliver the content in the most appropriate way.

**Comment by jgmac1106** [comment]
We use Versal to train all our student workers on campus. It is really easy
to  use for both IDs and learners.
Tophat is another one I have played with that works desktop, android, ios.
Canvas form instrucutre is not bad but that is a full blown LMS and maybe
beyond your needs.
If FOSS is a requirement there is always Moodle....but its Moodle.

I know that folks over on Participation Team have some project started
called the Software Lab where they are trying to categoize all the needs
for softward across MoFo/MoCo. Might be worth pinging them is Discourse or
GitHub

**Comment by Carotejada** [comment]
Thank you @jgmac1106

**Comment by chrislarry33** [comment]
While FOSS isn't a requirement, it would be welcomed. Moodle does sort of suck, but could be woth investigating. We also maybe missing an open source solution/project we could help augment with a use case, users, brand partnership and dev/design interaction.

**Comment by chrislarry33** [comment]
Here is a list of open source(ish) options. Anyone have any experience with the non-obvious ones? I thought Ilias and ATuder looked interesting. Also we could probably get a Google account that gives access to Classroom. Anyone use it? I haven't. 

http://blog.capterra.com/top-8-freeopen-source-lmss/

**Comment by amirad** [comment]
_runs and hides from blackboard and moodle_ used them both back in the day though so they've probably developed a lot since then. 

That's a good list @chrislarry33 thanks! @Carotejada might be worth looking at a few of those and we can review which ones we like in our call Monday?

@jgmac1106 thanks for the advice! If you were to pick your top one in regards to engagement and ease of use which would it be? Do you have a favourite? Also that course in Thimble deserves a serious high-five!

**Comment by amirad** [comment]
@Carotejada take a look at https://teachable.com/ I think you might like it! Customizable, optimized for various devices, easy to use AND is the only platform I've found that is multi-language supported.

**Comment by hannahkane** [comment]
Teachable looks awesome - seems to meet all of the requirements and isn't super expensive. (Versal also looks good, though. Curious to know, @Carotejada, if you've found anything you don't like other than the lack of integrated sign-on.)

Also wanted to follow up on one point. We'd talked about these not needing human intervention—there would be quizzes that could be graded by the system alone. But looking through the training module outlines, it seems that there are "challenges" that would require some human evaluation. Would these challenges be factored into whether people "graduate" from the course or not? I'm asking because some platforms have classroom discussion areas, for example, and others don't. Wondering if that would be a desired feature, or if you'd prefer to have the Challenges live on other platforms—e.g. Discourse, Twitter—as described in the module outlines.

**Comment by jgmac1106** [comment]
@chrislarry33  Google Classroom is the easiest of the options that would meet all of @Carotejada points.
Its probably the cheapest route as well. This would mean much of your Instructional Design would all occur within your Google Apps suite.  If its politically feasible its the most doable.

@amirad ease of localization might have to be deciding factor. 

--Rest of this more long term thinking and  blogging in an issue. Apologies a head of time. 

Just feel like we are so close on the platformless platform. Someway a "class" is spun up with students  getting one of these heroku>ghost>s3 blogs you hear whispers about. Each blog is automatically added to a Planet for that class. 

The CMS is easy no coding required by push button remixing. Think  like in Google Doc Templates or Caulfields [Wikity.cc](http://wikity.cc)

Let students and facilitators chat on channel du juor or create dedicated stream using any number of FOSS tools. 

Have some analytics tool that scrapes the Planet and streams for specific terms.

Help build leaders of the web by training them using the web. There is something special that happens in the federated classroom. I think @Carotejada is correct. The barrier has been too high. I think it makes a nice long term goal.

**Comment by jgmac1106** [comment]
Jim Groom just published a timely post of options available:
http://bavatuesdays.com/nothing-is-real-without-a-domain/comment-page-1/#comment-234741

@amriad I would say out of all the options the easiest would be Google
Apps. You make slidecks in gSlides, videos in YouTube, content in gDocs,
quizzes in gForms, and have them self grade using the Flubaroo plug-in for
gSheets. It is all hosted in Google Classroom.

Being that MoFo already has a Google Apps for Work account everything is
paid for except staff and contributor hours. You could quickly spin up a
training module template that anyone could remix without coding skills.

In terms of the others listed I only have experience with Versal. Ease of
use on the learner. There is some lifting on the instructional designer but
no system is free of this burden. It was super easy.

I have used  Tophat but that is just more mobile quizzes and clicker stuff
than anything.

**Comment by Carotejada** [comment]
@jgmac1106 thanks for sharing!

@chrislarry33  good that you opened the spectrum with the open source alternative.  We are taking some time to learn more about the options shared, considering this process in two phases: 1. try a ready to use solution to fulfill the immediate needs, while learnig in the process 2. move forward to open source solution in a long term project, capitalizing the lessons learned. 

@hannahkane classroom discussion are desirable. Teachable seems to have this option as a third party extension. 

@amirad  Teachable offers a really friendly experience, has nice features and allows branding. Will keep testing it with clubbers.

**Comment by chrislarry33** [comment]
Love this thread flagging @openmatt who is working/thinking on similar things

**Comment by hannahkane** [comment]
Agree, this is a great discussion. @Carotejada - do you mind if I reassign this ticket to you? It seems you'll be evaluating and informing a decision about which product to use ultimately.

**Comment by amirad** [comment]
I did a quick demo in teachable and both @Carotejada and I really liked it for the training program. We can fully brand it as well. And will dig into the language translations like the mentioned which is a huge +1. @hannahkane let us know if you see any flags with this program! We're using the free program right now but might need to upgrade to get the full report. 
http://mozilla.teachable.com/courses

**Comment by omnignorant** [comment]
FWIW, teachable is pretty cool.

**Comment by amirad** [comment]
Yay love the vote of confidence @omnignorant - took us so long to narrow down to one but we're excited about our choice. So many potentials.

**Comment by hannahkane** [comment]
Flagging @simonwex to see if he has any concerns about using [Teachable](https://teachable.com/) as a platform to deliver trainings.

**Comment by davidascher** [comment]
Things to explore & understand:
- learner flow -- this requires every student get a teachable account.  This would require legal & data privacy review of that service. Does it matter that it's not a Mozilla account system?
- do we care that we can't influence the tool?
- does it give us the engagement data that we need? 
- is the localization approach what we need?

I like the idea of using a specialized third party tool (esp. if ppl think it's good at this point!).  We just need to go in with eyes open.

**Comment by amirad** [comment]
We did an in-depth assessment of many of them and did determine teachable was the best one - https://docs.google.com/spreadsheets/d/1svRytzfjotojsQcuLxd5kFFeyBwjYZWPSr_Lr9RVirQ/edit 

@davidascher some notes on what I do know:
•I personally don't think it matters if it's a Mozilla account system. I think we might be able to discuss that directly with them (like The Next Web did) but not sure how that affect data collecting to which it seems like they have a good system that would be the benefit of using them. 
•I think we can influence it more than we need. Fully whitelable - able to manipulate html and css if we want. Designed to look and feel like Mozilla. Saleforce integration. Custom domain (we can use that clubs site we've been holding). 
•Definite plus to engagement data via salesforne and google analytics add ons that we can add. 
•Info on localization http://support.teachable.com/support/solutions/articles/9000010418-can-i-create-a-non-english-teachable-school- and http://support.teachable.com/support/solutions/articles/9000010340-can-i-use-rtl-languages-on-my-teachable-school-

**Comment by simonwex** [comment]
Teachable looks really good. Did you do a demo with them? Do we have a technical contact there?

I'd suggest we kick off a vendor review and move the investigation forward.

**Comment by amirad** [comment]
@simonwex emailed them last week for more info on data and customer privacy. Will keep you in the fold as I find out more!

**Comment by davidascher** [comment]
Usually the terms of service and privacy policy are enough for the legal
team to start with.

**Comment by hannahkane** [comment]
Apologies. I feel like I dropped the ball on this one. @simonwex - should we file a legal review ticket for Teachable?

**Comment by ldecoursy** [comment]
Ping @simonwex

**Comment by ldecoursy** [comment]
@hannahkane Can I close this ticket? Think it's duplicated someplace else?

**Comment by hannahkane** [comment]
Yes, I think we can close.
