### ISSUE TITLE
Establish file structure for Clubs Guides, including localized content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#333]
Let's set up a file architecture in this repo that allows localized content to be grouped together

cc @amirad @Carotejada

**Comment by amirad** [comment]
cc: @soapdog

**Comment by ldecoursy** [comment]
@hannahkane @amirad Can we close this?

**Comment by hannahkane** [comment]
It looks like we're just creating individual folders within the Clubs folder for each guide. I think that's probably fine for now, especially since we're likely to move all of this to the CMS sooner rather than later.

Closing, but @amirad, feel free to re-open if you want to discuss further.

**Comment by soapdog** [comment]
@hannahkane if we decide to use the little web interface shown in #335, then I'd like to make an addition to the file structure. 

Right now, we have a little markdown file for the content, if we start hosting translated files then we could have the other markdown files on the same folder as the English one with a different naming scheme such as `content.pt-BR.md` and `content.es.md` and also hosting a little JSON file that contains the pointers to to each locale. 

This is the approach we took in our other L10N campaign and it worked well. What do you think?

**Comment by hannahkane** [comment]
@soapdog - yes I think that adjustment makes sense. Let's plan on that.

**Comment by ldecoursy** [comment]
@hannahkane Is this now duped by #335? Wondering if we should close or move milestone.

**Comment by hannahkane** [comment]
Yeah, I think the structure for EN content is set, and #335 is where we can discuss localization.
