### ISSUE TITLE
Draft materials for announcing new community engagement channels

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#336]
This ticket is for drafting and publishing communications of the new MLN Community Engagement Proposal (Ed Hub) [here](https://docs.google.com/document/d/1ta-ePLgF8t5oMuRIJUSDAML4JzaeGk_R1oWh5khzIkU/edit#heading=h.ew2wra6vgoi0). 

Communications include:
- Blog post
- Forum announcement
- Tweets for MozTeach Twitter handle
- newsletter inclusion

New channels are being officially launched in [March](https://docs.google.com/spreadsheets/d/18Cl4Ouez3LQq828WKCg6igQj-INEznRbxw7ubTi3mQY/edit#gid=1086948807).

@ldecoursy

**Comment by KGorr** [comment]
Draft blog post can be found here: https://docs.google.com/a/mozilla.com/document/d/149-9a4GLm0NozrDn2B01INGNsbgpGylVfNvdGa1nNXo/edit?usp=sharing

**Comment by ldecoursy** [comment]
Aim to publish by last week of Feb.

**Comment by KGorr** [comment]
Finalized - just awaiting youtube/hangout links and tweetchat #.

**Comment by KGorr** [comment]
Blog post has been published: https://blog.webmaker.org/introducing-new-ways-to-connect-with-mozilla-learning
Discourse thread: https://discourse.webmaker.org/t/introducing-new-ways-to-connect-with-mozilla-learning/619
Tweets have been scheduled.
Newsletter content included in events section.

Closing!
