### ISSUE TITLE
Write content for updated Thimble/curriculum info packet

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#337]
This ticket is for drafting Thimble/curriculum info packet for distribution to the community.

Outline/content can be found [here.](https://docs.google.com/document/d/17uxB6khbQkOWFwYpbc9rcy0KB4uUJ32LYruo4Om06xY/edit)

@ldecoursy

**Comment by KGorr** [comment]
Currently on second round of edits - awaiting final approval.

**Comment by KGorr** [comment]
Status update: Distribution pending release of new web lit map 2.0.

**Comment by ldecoursy** [comment]
@KGorr We can close this, let's file a new one for outreach.
