### ISSUE TITLE
Rio: Start a bi-lingual blog about project

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#34]
This issue has been migrated from mozilla/teach.webmaker.org#67.

It was originally written by [thornet](https://api.github.com/users/thornet) on Thu Feb 19 2015 and had the following description:

> Andre kicking this off

On Thu Feb 19 2015, [davidascher](https://api.github.com/users/davidascher) commented:

> Nice!

On Thu Mar 12 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> I need a contact to set this up. I think Michelle sent me one but I still need to set LDAP and email so that I can do this blog with a Moz account and not my personal one.

On Tue Mar 31 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Can someone provide me with a contact to set the LDAP account and email?

**Comment by soapdog** [comment]
LDAP account is working. Will move to get the blog and mailing list going.

**Comment by ldecoursy** [comment]
@soapdog Is this still on the table?  Should we plan for post-MozFest?

**Comment by soapdog** [comment]
we should plan for post mozFest :D we might want to revise the scope and make it a clubs blog since the Rio project has a blog at http://riomozillaclub.org

**Comment by ldecoursy** [comment]
Just flagging @HPaulJohnson, as a note to think about l10n for a more unified blog strategy as it develops.

**Comment by ldecoursy** [comment]
Going to close this, as it's an old ticket, and re-address l10n as part of a potential updated blog strategy in 2016.
