### ISSUE TITLE
Create Mozilla Clubs Guide for Libraries

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#340]
This ticket is to create a Mozilla Clubs guide for libraries. Will conduct research and collaborate with @anmechung and others for resources, topics, and other content to include. 

**Resources:**
https://blog.webmaker.org/maker-party-2014-resources-for-libraries-and-learning-spaces 
https://blog.webmaker.org/?s=library

CC: @amirad, @ldecoursy

**Comment by KGorr** [comment]
Draft is here: https://docs.google.com/a/mozilla.com/document/d/1u_M05M7u7aH3N4d7gw-32Wqq9GNTD4i79ZWNlk7Q_MU/edit?usp=sharing

**Comment by KGorr** [comment]
Thanks, @amirad and @chadsansing for taking a look at the draft and providing excellent feedback! @anmechung, it would be great to have your eyes on it as well. I will plan to put it into the github template for publishing next Monday, 3/7.

**Comment by amirad** [comment]
NP! Also just sent @smithisgeneric a quick message to see if she has anything to add!

**Comment by anmechung** [comment]
@KGorr added my 2 cents!  Let me know what you think.

**Comment by KGorr** [comment]
Thanks @anmechung and @smithisgeneric! Great feedback. Implemented changes and ready for another look, if you'd like. Otherwise, I'll put it into the guide template tomorrow or Monday.

**Comment by anmechung** [comment]
@KGorr happy to take another look

**Comment by KGorr** [comment]
Thanks, @anmechung! https://docs.google.com/a/mozilla.com/document/d/1u_M05M7u7aH3N4d7gw-32Wqq9GNTD4i79ZWNlk7Q_MU/edit?usp=sharing

**Comment by KGorr** [comment]
Finished and ready for sharing! http://mozilla.github.io/learning-networks/clubs/hosting-mozilla-club-in-library/.

**Comment by amirad** [comment]
Beauty! Great job @KGorr
