### ISSUE TITLE
Allow embedding of videos in the template

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning-networks#344]

**Comment by ldecoursy** [comment]
@flukeout Do we still need this ticket?

**Comment by flukeout** [comment]
@ldecoursy Depends if you are still wanting to have embeddable videos, like youtube etc. Let me know if it's a priority for these guides!

**Comment by ldecoursy** [comment]
OK is this for the CMS templates like the community calls? Then yes :) Wasn't sure if you were still tracking that in this repo...

**Comment by flukeout** [comment]
Originally, this ticket was for the github hosted Clubs Guides in this repo, the ones with the purple side-navigation on the left side. Are you planning to continue using them or are you looking to transition your content to the CMS?

**Comment by ldecoursy** [comment]
My bad! @amirad Do you still need embedded videos in the Clubs Guides?

**Comment by hannahkane** [comment]
Just a note - I'd suggest we transition this content to the CMS when we can, so, unless there's a need for embedded video content now, I'd prefer to close this ticket. But it's up to @amirad!

**Comment by amirad** [comment]
It would definitely be nice to be able to place videos in the guides!

**Comment by flukeout** [comment]
Embedding videos via an iframe works just fine, you can copy and paste the markup from Youtube  (for example) directly into the markdown.md file...

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/otaEPVwwz-0" frameborder="0" allowfullscreen></iframe>
```

...and it will work. Closing.

**Comment by amirad** [comment]
Thanks @flukeout 

cc: @Carotejada @KGorr

**Comment by Carotejada** [comment]
Great!
