### ISSUE TITLE
Rio: propose how to engage and on-board local volunteers for LAN house events

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#35]
This issue has been migrated from mozilla/teach.webmaker.org#68.

It was originally written by [thornet](https://api.github.com/users/thornet) on Thu Feb 19 2015 and had the following description:

> Andre & Mario beginning to draft what this volunteer strategy would look like. 

On Thu Mar 12 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> The plan is to start with a group of volunteers from the local Mozilla/WebDev community and then use this group to train volunteers in the local neighborhood of the Lan Houses. This way we can tap in the local amazing web community and also engage them in social cause. In the end we have a mixed group of highly talented and accomplished web developers working with new volunteers full of energy and potential.
> 
> On 11th of April we'll have a web dev event here in Niterói called NiteroiJS where I plan to recruit some volunteers. I already have a group of close to four volunteers (besides our current team of 3 or 4 people). My aim is to have 12 volunteers engaged with the project which would make it 2 per Lan House in this initial phase.
> 
> After we collect contact with interested volunteers-to-be, we'll have an informal meeting to present the project and do a train the trainers session.
> 
> Once we start doing the workshops on the Lan Houses we plan to spot people that are keen to take the web as their own and are aligned with our mission. We plan to further empower them by doing "train the trainer" workshops with those folks and leveraging their help as mentors for new workshops thus engaging the local/neighborhood community.

On Tue Mar 31 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Also approaching key web developers with a strong desire to cause an impact and social transformations here in Rio to help with awareness to this project and with an initial set of volunteers.

**Comment by soapdog** [comment]
We have a list of people interested in helping us here. This list is composed mostly of university students and young professionals from the local Web Developer Interest Groups and local Mozilla Community. Our plan is to use this group as a seed group to do mentorship on the initial workshops while we engage with the community that is local to each cybercafe.

**Comment by ldecoursy** [comment]
Closing this, as it's being covered by Mozilla Clubs in those LAN houses.
