### ISSUE TITLE
X-Ray Goggles Tutorial

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#354]
It seems many people are having issues accessing the X-Ray Goggles tutorial sample activity (using Firefox and Chrome). @hannahkane, can you provide specific instructions on how to access it? Would love to have it added to [this document](https://public.etherpad-mozilla.org/p/EdHubnewsletter) for future reference too.

@Saallen @amirad @Carotejada

**Comment by amirad** [comment]
Yes! We were all looking at it during our RC call today and no one could find the tutorial with step by step instructions that the sample activity mentions. Are we missing something?

**Comment by Saallen** [comment]
Hi @hannahkane I had trouble too but had to restart firefox to get x-ray googles to activate.

**Comment by hannahkane** [comment]
Hmm...so, a direct link to the sample activity/tutorial is https://goggles.mozilla.org/ftu

When you land there, you should see this pop-up:
![screen shot 2016-03-04 at 8 16 39 am](https://cloud.githubusercontent.com/assets/8389648/13532660/8065c22a-e1e1-11e5-9d86-04c237b71d67.png)

At that point, if you click on the X-Ray Goggles button in your bookmarks bar, you should see the start of the tutorial:

![screen shot 2016-03-04 at 8 17 50 am](https://cloud.githubusercontent.com/assets/8389648/13532681/9dc52d06-e1e1-11e5-8fdc-a24aa998269a.png)

Is that not what people were seeing? If not, can you describe what people were seeing? I just tried it and it worked fine for me in both Firefox and Chrome.

@Saallen - hard to diagnose that problem. Was Firefox crashing? If it happens again, perhaps you could see if there are any errors in your dev console?

**Comment by ldecoursy** [comment]
Ahh, I know what I was doing wrong - maybe others did the same too. I clicked the X to remove that pop-up. Then when I clicked the Goggles - they activate, but there is no tutorial.

**Comment by hannahkane** [comment]
Oh, that makes perfect sense.

@Pomax - what are the things we can do here? It probably doesn't make sense to make the first lightbox non-dismissable. Is it possible to trigger the tutorial if the user enables goggles after dismissing the lightbox?

**Comment by amirad** [comment]
Oh yes, that's the problem. If I click x on the pop-up we loose the tutorial.

**Comment by jgmac1106** [comment]
That would mirror why nobody in my class used the tutorial.

**Comment by Carotejada** [comment]
We can also change the message in the light-box.

**Comment by Pomax** [comment]
we can replace the [x] and make it a text link that says "click here to skip the tutorial" and have that close the dialog instead?

**Comment by hannahkane** [comment]
perfect. I'll file a ticket in the goggles repo. thanks, all!

**Comment by hannahkane** [comment]
https://github.com/mozilla/x-ray-goggles/issues/280
