### ISSUE TITLE
Add step to add hashtag in #2nextprez activity instructions 

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#355]
@chadsansing Spoke with @hannahkane about Thimble dashboard fixes - more on that soon. 

In the meantime and as prep for that, can we add a step in the #2nextprez activity tutorials for people to add that hashtag in the description when they save their remix?

**Comment by chadsansing** [comment]
Planning to add this copy to the "Publish" step already inside each project's tutorial - sound okay, @ldecoursy?

"When you describe your project, be sure to tag it with #2NextPrez so it shows up as part of the [online campaign](https://twitter.com/2NextPrez)."

**Comment by chadsansing** [comment]
This is finished for:
- Letters to the Next president intro page.
- My Letter to the Next President project.
- Candidate Meme project.
- Candidate Quote project.
- Campaign Poster project.
- Thimbe/Hypothes.is lesson.

Okay to close, @ldecoursy?

**Comment by ldecoursy** [comment]
Gr8 thanks!

**Comment by chadsansing** [comment]
Closing pending any new edits that need to be made in the future.

**Comment by hannahkane** [comment]
Note from Gideon's email: "If we are redirecting them to a project (or three), I suggest creating that project with the description/tags already filled out so that they wouldn't need to do it themselves."

We should do this ^
