### ISSUE TITLE
April Mozilla Learning Newsletter: Internet of Things

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#356]
Write and publish April Mozilla Learning Newsletter, which includes:

Community Spotlight
- [x] Contact Community Spotlight Nominee
- [x] Write Community Spotlight Article
- [x] Publish to blog.webmaker.org

Newsletter
- [x] Write newsletter block content (featured activity, events, announcements, spotlight]
- [x] Incorporate Hive community information
- [x] Send content to @stephaniemcv by March 18
- [x] Determine A/B testing plan for subject line and distribution date 
- [x] Test and distribute newsletter by April 1

**Comment by KGorr** [comment]
Spotlight article ready for review here: https://docs.google.com/document/d/1AhUefZkLrjOJLI8vhT5uy59q8AvlzCZwHz2BwyEeJmw/edit May need another pass to streamline connection between community member and IoT

**Comment by KGorr** [comment]
@thornet - please let me know by March 16 at the latest if there are any specific IoT resources, topics, announcements, etc. that should be included in the newsletter content! The earlier the better, of course.

**Comment by thornet** [comment]
Thanks! We're drafting an announcement text about our IoT efforts that will
be live in time for the newsletter. The draft is here:
https://docs.google.com/document/d/1YA_D8ClPRUUMvO8B5CVwPlD7_a9hiRuqWgJHHRaxEiU/edit#

Please note it's being actively edited right now, so if we pull content
from it, let's check in before publishing so we're not out of sync.

On Fri, Mar 4, 2016 at 10:25 PM, Kristina Gorr notifications@github.com
wrote:

> @thornet https://github.com/thornet - please let me know by March 16 at
> the latest if there are any specific IoT resources, topics, announcements,
> etc. that should be included in the newsletter content! The earlier the
> better, of course.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/learning-networks/issues/356#issuecomment-192472465
> .

## 

_Michelle Thorne_
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by KGorr** [comment]
Thanks for sharing, @thornet. Super helpful.

**Comment by KGorr** [comment]
@stephaniemcv, based on the other emails being sent next week and our testing plan, can you confirm when the email will be sent? I believe it will be over a 3 day span, yes? Just need to know when to publish the community spotlight article. Thank you!

**Comment by stephaniemcv** [comment]
We can send the 20% test on 3/30 (Wed.), based of the winner of that test, the remaining 80% of the list will get the email on 4/1 (Fri).

**Comment by KGorr** [comment]
Thanks, @stephaniemcv. We are all set with this except the final 2 to-dos: publish community spotlight (3/29 pm) and then send the newsletter! Thanks, all, for the great help!

**Comment by KGorr** [comment]
@stephaniemcv, the community spotlight is now[ live](https://blog.webmaker.org/community-spotlight-mark-shillitoe), so you are OK to send the first A/B test tomorrow morning. Thank you!

**Comment by chrislarry33** [comment]
love this profile!

**Comment by stephaniemcv** [comment]
@KGorr , A/B test will send out in about an hour.

**Comment by KGorr** [comment]
Thank you @stephaniemcv! And thanks, @chrislarry33!

**Comment by KGorr** [comment]
Done, done, and done. Moving on to https://github.com/mozilla/learning-networks/issues/374
