### ISSUE TITLE
Update web-lit-basics-two module 

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#357]
@mmmavis, @hannahkane - still having dev environment issues and I'm about to dive back into leadership curriculum development. Is there any time in the next production heartbeat to update this module? Would be great to update this in tandem with the Web Lit Map 2.0 launch, as well.

Updated links at the top of this content page:

https://docs.google.com/document/d/1TK2AAc5Bhe0sO1plj_ZtfI7LIMoc7rHnzmHoTt_URMI/edit#

cc @ldecoursy, @chrislarry33, @anmechung 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by hannahkane** [comment]
@chadsansing - I can do this. Can you clarify—is it just updating the links, or are there other deltas between this doc and what's live on the site now?

**Comment by chadsansing** [comment]
Just updating links, @hannahkane - thanks muchly!

**Comment by hannahkane** [comment]
Merged. Will go live with the next roll to production.
