### ISSUE TITLE
Add intermediate-web-lit-css-one to /activities

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#358]
@mmmavis, @hannahkane - this module would be good to add to /activities along with the Web Lit 2.0 launch, as well. Not quite where I need to be to add it yet - any time available in the next heartbeat or so?

Content doc - https://docs.google.com/document/d/1j6kTdhfTION7_N63Ws-qv1NC-V2a0Iuh-4PDkGfQRIE/edit#

cc @ldecoursy, @chrislarry33, @anmechung 

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by hannahkane** [comment]
@chadsansing - for sure. I should be able to add these whenever you'd like, and @mmmavis can review my PR. Let me know when it's ready to be published.

**Comment by chadsansing** [comment]
I think we're set on the content doc now, @hannahkane -

**Comment by hannahkane** [comment]
@chadsansing - should the activities be divided into the Read/Write/Participate categories, or should they all go under "Writing the Web"?

**Comment by chadsansing** [comment]
@hannahkane - they are all write the web activities :)

**Comment by hannahkane** [comment]
Closed with https://github.com/mozilla/teach.mozilla.org/pull/1689. Will be live with next push to production.
