### ISSUE TITLE
Follow up items and dates for IPPD

### ISSUE THREAD

**Issue by jvallera** [mozilla/learning-networks#359]
- [x] Follow up call one: March 7, 2016, 6-7 pm
- [x] Follow up call 2: April 4, 2016, 8-9 pm pm EDT
- [x] February 29/Prompt 1: What are you most interested in/excited about working on in the coming weeks?
- [x]  March 14/Prompt 2: What project(s) did you choose to work on and how do you plan to implement it?
- [x]  March 21/Prompt 3: What challenges have arisen so far? Do you have any adaptations or suggestions based on experiences?
- [x]  March 28/Prompt 4: What are your plans for testing your project?
- [x]  April 11/Prompt 5: How do you plan to share your work in the open?

**Comment by jvallera** [comment]
@chadsansing @anmechung @ldecoursy our check list and dates

**Comment by chadsansing** [comment]
Can we close this, @ldecoursy, @jvallera?

**Comment by jvallera** [comment]
yes @chadsansing
