### ISSUE TITLE
Left Nav bar on teach site

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#360]
Is it just my display or did the left navigation bar on the teach site grow too large? https://teach.mozilla.org/

**Comment by hannahkane** [comment]
Hey @jgmac1106 - can you attach a screenshot? I'm not sure I see what you're seeing.

**Comment by jgmac1106** [comment]
![unnamed image](https://cloud.githubusercontent.com/assets/10534566/13644527/3cbeaef8-e5f4-11e5-9448-d305292aa4b6.png)

Not as bad on my laptop. You do notice that the callout box overlaps on the nav bar. I guess it was just the size of my home desktop display that made the left nav bar seem gigantic. I will take a screenshot when I get home.

**Comment by hannahkane** [comment]
Ah, okay, yes I see what you mean. @mmmavis has a patch in for that, I believe.

**Comment by jgmac1106** [comment]
@hannahkane Here is my desktop display. 
![unnamed image 6](https://cloud.githubusercontent.com/assets/10534566/13654777/64950038-e628-11e5-817b-ed8593aad46c.png)
