### ISSUE TITLE
Spring 2016 IPPD Mozilla Web Literacy Leaders Celebration/Close-Out

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/learning-networks#361]
We wrap-up our Web Literacy Leaders training via the NYC DOE's IPPD program with the culminating event on April 20th. 

Still to do:
- [x] Confirm location date/time with METRO (@ldecoursy)
- [x] Send calendar invite
- [x] Event logistics (snacks, drinks) (@jazoulai)
- [x] Put together swag packs for students (sets of 30 stickers, patches, what else?)
- [x] Documentation (group photo and recap blog post featuring participant's outcomes)
- [x] Music playlist
- [x] Finalize agenda and roles as a group https://docs.google.com/document/d/1vjr7cD1Ijp2p8XF038dMzAKn-ECEtF6apsLpLBsRKt4/edit

Other things to consider:
- Will we have badges or printed certificates for participants in web lit trainings?
- Thimble selfie photo booth (using masks from Hive holiday party?)
- Incentives to bring a student or colleague along?
- Consider ways to share student feedback - Vines, student Thimble remixes, etc. 
- Agenda - When/how to incorporate Hive, new web lit map, #2NextPrez 

cc @chadsansing @anmechung @jvallera @Carotejada @jazoulai

**Comment by chadsansing** [comment]
Can we close this, @ldecoursy, @jvallera?

**Comment by jvallera** [comment]
yes @chadsansing
