### ISSUE TITLE
Outreach: Education Information Kit for Partners and Teachers

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#363]
Education Kit for sending to teachers, ed tech influencers, partners, and others we'd like to know about our free, open-source teaching kits, tools, and resources. [Kit can be found here](https://docs.google.com/document/d/17uxB6khbQkOWFwYpbc9rcy0KB4uUJ32LYruo4Om06xY/edit).

Current status: Distribution pending release of new web lit map 2.0.

**Comment by KGorr** [comment]
@ldecoursy, here is the [email draft](https://docs.google.com/a/mozilla.com/document/d/1iKEOLImV57o1y-JzLGBhnek4rnmaXtrr-L3QY_CNUtQ/edit?usp=sharing) for review.

**Comment by KGorr** [comment]
@ldecoursy, email has been updated. Discuss next steps on Monday?

**Comment by KGorr** [comment]
@KevZawacki, we are hoping to distribute this kit soon, but would love to schedule around your media pitch strategy for the Web Lit map. Looking at your comms plan, it seems most of your work happened this week... Do you have suggestion for when would be best to release? Thoughts on next week?

**Comment by KevZawacki** [comment]
@KGorr Next week sounds good! We'll (hopefully) have a Web Lit Map op-ed published then, and be tweeting about the map again, too.

**Comment by KGorr** [comment]
Awesome, thanks @KevZawacki. I'll check in with again right before we send.

**Comment by KGorr** [comment]
@KevZawacki - how is the timing for us to send the ed kit today? I'm also going to send you an email with a request to look over our contact list to see if there is overlap with your efforts so we aren't contacting folks twice. Thanks!

**Comment by KevZawacki** [comment]
@KGorr Go for it! Only a few media contacts you'll want to hold off on (just sent an email).

**Comment by KGorr** [comment]
2 waves of personal invitations have been sent and the Mozilla Learning Team has also starting distributing. Great feedback so far. Closing!
