### ISSUE TITLE
Draft series of onboarding emails for CCs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#364]
We can automate a series of emails that will go out to CCs upon approval. This will help all CCs, but particularly those who are not matched with an RC.

The first email should prompt the CC to participate in the online training platform.

**Comment by hannahkane** [comment]
@amirad - assigning this to you, though I think in the past we'd talked about you doing this with @HPaulJohnson. Let me know if this ticket needs more detail.

**Comment by amirad** [comment]
While I would love to do this with @HPaulJohnson I'm not sure if he has capacity?!?!?! 

@KGorr and I have been cranking out a lot of club content recently so many we can set up a call to scope this out. Kristina, maybe we set up a call last week in March or First week in April and talk about the email flow for new CC's?

**Comment by HPaulJohnson** [comment]
I'd love to jump in and assist here. Encryption campaign is getting close to wrapping (next week) so I should have some extra capacity. @amirad @KGorr, let's discuss at our regular weekly call next week?

**Comment by amirad** [comment]
Weeee ok.

**Comment by amirad** [comment]
Quick notes from meeting March 22nd:

**Current flow.** People sign up at teach.mozilla.org/club (need to update the signup process). They receive a survey to fill out https://docs.google.com/forms/d/1J-S6nKTHd-yLzcWaE6Wu3pFesSYYdr3yfPlGECOPp44/viewform and respond to survey. If no response then Kristina follows up again and if no response after that they get denied. If they respond to survey Kristina reviews responses to make sure they align with what we are doing and approves them. Once in the system they get monthly emails with info on what to do at their events, new curriculum, calls to join and convos in discourse to engage in. 

**New flow.** Existing survey is embedded into signup process. Individuals sign-up and receive link to training with info: http://mozilla.teachable.com/courses/mozilla-club-training If they don't sign-up they go through a series of follow-up emails with different prompts (first email: sign-up again, second email: can the clubs team help you etc.). Once signed up we monitor their progress and tbd approve their training and they become club captain. Receive monthly emails and newsletters. 

@KGorr does that sound right to you?!
@Carotejada to give this some thought and start drafting proposal 
@HPaulJohnson @KevZawacki and rest of team to review next steps next Tuesday

**Comment by KGorr** [comment]
Yes, this seems right. I'm happy to help with the transition. Looking forward to next week's call.

**Comment by hannahkane** [comment]
Question about the new flow: Do individuals receive the link to training after submitting the application form, or after getting approved?

**Comment by amirad** [comment]
Hmm, that is up for debate. I can see it working either way. Will let @Carotejada plan that out in her draft proposal.

**Comment by Carotejada** [comment]
So, [this](https://docs.google.com/a/mozilla.com/document/d/1Ds_uAJvuYa0ACLWmQfUukRHAyX5Stj_8AXGlPjTDW3Q/edit?usp=sharing) is the new application flow for Club Captains. @hannahkane would you mind taking another look and let me know what´s next to implement the ones that are connected to our site and mailing list (steps 1, 2, 3, 4)?

The ones from Teachable (step 5) I will create them.

Thank you!

**Comment by hannahkane** [comment]
Tickets filed for:
- [ ] [Changes to /Clubs page layout](https://github.com/mozilla/teach.mozilla.org/issues/1605)
- [ ] [Update application form](https://github.com/mozilla/teach.mozilla.org/issues/1822)

Not sure about step 4, since the doc says that's manual. Do you want to make that automatic?

**Comment by Carotejada** [comment]
Thank you @hannahkane! 
Regarding step 4 today @KGorr reads the applications to see if they meet the requirements.

However, we can make it automatic and let the people go through the training. If they don't complete it, we can revoke the application... What do you think @amirad ?

**Comment by hannahkane** [comment]
Sorry, to clarify, I know that @kgorr reviews the applications and wasn't suggesting we change that. The part I wasn't sure about was whether we should automatically send an email if she chooses "Approved" in the Clubs admin dashboard (versus having her send the email manually). Does that question make sense?

**Comment by amirad** [comment]
+1 for the auto email and for kristina to just mark approved.

**Comment by Carotejada** [comment]
:)

**Comment by hannahkane** [comment]
OK, in that case, I just filed this: https://github.com/mozilla/teach.mozilla.org/issues/1826

Will need discussion with engineers since it's a new workflow for us.

Thank you!

**Comment by Carotejada** [comment]
Thank you @hannahkane!!

**Comment by ldecoursy** [comment]
OK to close @Carotejada @amirad?

**Comment by amirad** [comment]
Yah I think @Carotejada has it covered.
