### ISSUE TITLE
Scope & Create "Partnering with local Orgs" Club Guide

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#365]
**Mozilla Club Guide: Partnering with local businesses, organizations, and clubs**
Outline can be [found here](https://docs.google.com/a/mozilla.com/document/d/1agiZpkMonHpb9U4xoirKIokkpZC3-SHs_2jPN1z1HNY/edit?usp=sharing).
- [x] Receive approval on outline
- [x] Research credible resources/references
- [x] Write content by filling out approved outline
- [x] Receive feedback, edits, suggestions from the team
- [x] Once approved, put guide into Github template

Feedback, suggestions, and resource contribution appreciated!

**Comment by KGorr** [comment]
@amirad, anyone in particular with expertise that I should reach out to for support?

**Comment by amirad** [comment]
@soapdog will have some info here based on some things he's done. Might be worth enlisting him to co-create this since I know he was thinking of something similar!

**Comment by amirad** [comment]
@soapdog can you share the info you created here for @KGorr - thanks!

**Comment by amirad** [comment]
I put together this presentation for someone today which can be used as an asset in the guide for people to use when talking to partners: https://docs.google.com/presentation/d/18TvYogZefxmybDmAPxXVyqj9r4NEoH7ngS3V5hwuYBE/edit?usp=sharing

**Comment by soapdog** [comment]
@KGorr and @amirad,

Sorry for not seeing this earlier. I ended up duplicating a lot of work here. I placed my little draft at:

  http://mozilla.github.io/mozilla-club-guides/local-partnerships/

I think we should rework my stuff and cherry pick the useful parts for the google doc.

**Comment by KGorr** [comment]
Hi @soapdog, the outline didn't take long, so not much work was duplicated. I think we can merge the resources from both easily, and have a very robust guide. Which is what the RCs have told me they want, so that's great! I'll work on this early next week. Thanks!

**Comment by KGorr** [comment]
This guide is ready for review. It is a doozy, spilling over to 5 pages. BUT, I hope that you'll find it is all helpful information. As you review it, consider if we should include the funding conversation here too, or if that should remain a separate guide. I'm learning towards separate as to not overwhelm the reader...

@soapdog, I incorporated your original content (edited slightly) into the first half of the guide. It was so incredibly helpful to have that and I was able to build on the great ideas you had in there. Thank you!

**Comment by KGorr** [comment]
Oh, and also @amirad, @soapdog, I'd love to include photos of clubs meeting in the non traditional spaces. Anything available come to mind?

**Comment by soapdog** [comment]
@KGorr thanks a lot for the kind words! You're awesome! As for the photos, you can pick any pic from my albumns at https://www.flickr.com/photos/soapdog/albums if you want.

**Comment by KGorr** [comment]
Thanks for the photos, @soapdog! I added a couple. I would love to get this into a github template next week - any content suggestions @amirad @soapdog? Anyone else who should give this a look?

**Comment by soapdog** [comment]
@KGorr,

Congratulations on the awesome content! It is looking really good! I believe this will be a great addition to our ever-increasing guide collection.

**Comment by KGorr** [comment]
Woo - this one is github'd! [View it here.](http://mozilla.github.io/learning-networks/clubs/partnering-local/#introduction) & I managed to embed a video for the 1st time! Happy dance!

BUT....the logo in the upper left hand side has disappeared. @amirad or @flukeout - can you help? No idea what I did. Once that is fixed, I'll close this ticket.

**Comment by flukeout** [comment]
@KGorr The logo goes away when there are too many navigation items on the left-hand side. It's to try to reduce the amount of scrolling that has to be done within the nav, which is cumbersome.

**Comment by KGorr** [comment]
Whew! So I didn't mess anything up. Thanks, @flukeout. @amirad, do you want to reduce the amount of nav items, or is it OK as-is?

**Comment by amirad** [comment]
I think it's fine @KGorr - also I made a small tweak to your title to make it more broad since you also talk about students and informal learning spaces in the guide. Hope that's okay!

**Comment by KGorr** [comment]
A-OK! Thanks for the help, all. On to the next!
