### ISSUE TITLE
Scope & Create "Public Speaking" Club Guide

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#366]
**Mozilla Club Guide: Public Speaking: Becoming comfortable with speaking in front of your Mozilla Club and Club partners**
Outline can be [found here](https://docs.google.com/a/mozilla.com/document/d/1MBL87oZ0Ww3U3MbkIy_OaoeqEu78r0k2yprx_a836_o/edit?usp=sharing).
- [x] Receive approval on outline
- [x] Research credible resources/references
- [x] Write content by filling out approved outline
- [x] Receive feedback, edits, suggestions from the team
- [x] Once approved, put guide into Github template

**Comment by KGorr** [comment]
@KevZawacki, do you have any resources that I can pull for this topic? Thanks in advance!

**Comment by KevZawacki** [comment]
Hey! There might be some helpful language / ideas in our [project call playbook](https://docs.google.com/document/d/13HYsqi0B-MIXvr08FR87JOC4hgYT4ZtA31AF_6oqiUM/edit).

**Comment by KGorr** [comment]
Awesome - thank you @KevZawacki! @amirad, any thoughts on resources or other people I should reach out to?

**Comment by amirad** [comment]
Might be some places to pull here: https://wiki.mozilla.org/TechSpeakers
Faye has done some public speaking workshops for community: https://www.youtube.com/watch?v=QSF9jIIcQ3k and http://fatecabag.com/2015/03/20/fsa-ph-public-speaking-workshop/

**Comment by amirad** [comment]
Again @soapdog might have some ideas!

**Comment by KGorr** [comment]
[This guide](https://docs.google.com/document/d/1MBL87oZ0Ww3U3MbkIy_OaoeqEu78r0k2yprx_a836_o/edit#) is ready for feedback! @KevZawacki, @amirad @soapdog - would you mind taking a look? Who else would be great to look it over?

**Comment by amirad** [comment]
<3 @Carotejada check it out and see if you have any edits!

Once the group above is done feel free to send to a couple RCs to get their feedback - I'm thinking Tina and Shreyas.

**Comment by KevZawacki** [comment]
@KGorr This is great! I plan to borrow from it liberally when we start planning MozFest speakers :-)

**Comment by KGorr** [comment]
Thanks, @KevZawacki! @amirad, I'll be sure to send it over to a couple of the RCs for a look once I hear from everyone.

**Comment by Carotejada** [comment]
@KGorr <3 awesome! Just added a suggestion.

**Comment by KGorr** [comment]
@amirad, I'm just waiting on one link suggestion from Shreyas, and then this is ready to put into the template. Do you want to scan it one last time, or am I good to go to github (say that 5 times fast!)?

**Comment by amirad** [comment]
good to go to github
good to go to github
good to go to github
good to go to github
good to go to github

**Comment by KGorr** [comment]
Thanks for all of the help and support! Here is the finished guide in github: http://mozilla.github.io/learning-networks/clubs/public-speaking/ I added it to your resource list, @amirad. Closing this ticket and moving on to https://github.com/mozilla/learning-networks/issues/365.

**Comment by amirad** [comment]
Thank you @KGorr
