### ISSUE TITLE
Obtain Mozilla email addresses for Mozilla Club Regional Coordinators

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#367]
The Mozilla Club Regional Coordinators have expressed interest in getting Mozilla email addresses to improve credibility and professionalism when contacting current and potential partners, members, and other contacts. 

CC: @amirad

**Comment by KGorr** [comment]
@hannahkane, do you know how we can get started with this? Who is the best contact for this type of request? Thank you!

**Comment by ldecoursy** [comment]
Good to check into this process, but we probably should have some guidelines surrounding this too...

**Comment by hannahkane** [comment]
Was just looking for info on Mana about this, but I can't find anything about the process nor what the org guidelines are. Maybe a question for the ops team?

**Comment by KGorr** [comment]
Tom Farrow actually happened upon this ticket and sent me an email regarding his support. I will fill you in and modify this ticket once I learn more from him. Thank you!

**Comment by KGorr** [comment]
An update on this: @tomfarrow has been working with us on both community guidelines and process of securing email addresses using mozilla.club.org. 
- There are about 120 volunteers across the globe that have a Mozilla email address.
- You've not had any issues with volunteers using Mozilla email addresses to-date.  
- The email addresses are not monitored (privacy)
- There is a team of Mozillians that are available to help the users with questions/concerns/support for the email address.

Regarding email use guidelines, no "official" guidelines are in use. Let's collaborate to create one that can be used across teams, [here](https://docs.google.com/a/mozilla.com/document/d/18yeTXjPX9PFOzhF6HF9sDm808mj-v8qqVJnJ1zaw6Tg/edit?usp=sharing). @amirad @ldecoursy @hannahkane @tomfarrow

From Tom: "The process for getting a new email address would be to file a bug (though we are moving to a service desk tool in near future), and my Service Desk team will check the requester's identity against our records, and follow any approval path that you have defined.

We currently have a non-profit license available for the Community Account that simply hasn't been activated yet. Awaiting confirmation that we are confirmed to set up account."

Are there any other unknowns, processes, approvals we need to go through for this project?

**Comment by hannahkane** [comment]
Thanks, @KGorr. I added a few comments to the doc.

**Comment by KGorr** [comment]
Marking this as blocked as we wait on the broader branding strategy to be played out.
