### ISSUE TITLE
Update Web Literacy Basics II Teaching Kit

### ISSUE THREAD

**Issue by anmechung** [mozilla/learning-networks#369]
@chadsansing can you take a look at my crosswalk of the web literacy map 2.0 and web lit II basic skills, and update each activity to reflect? https://docs.google.com/document/d/15B2ccF-DSTl74SwNbyZ0W5qMu-jQNOXUS4C6BsvjF9s/edit#

**Comment by chadsansing** [comment]
@anmechung, take a look when you have the chance. If all seems right, let's close.
