### ISSUE TITLE
Determine which badges (if any) to issue in Q2

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#37]
This issue has been migrated from mozilla/teach.webmaker.org#86.

It was originally written by [thornet](https://api.github.com/users/thornet) on Wed Feb 25 2015 and had the following description:

> See: https://github.com/mozilla/webmaker-curriculum/issues/140 for context
> 
> Reply here since other repo no longer active. 

On Fri Mar 13 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> My vote is to have a Club Leader badge  - question is could it cover a range of involvement from helping to develop the program, create curriculum, and actually run clubs, or do we need more nuance here. 

On Mon Mar 16 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> I think we keep
> Hive Community Members
> Webmaker Menor/Super Mentor
> Web Lit Skill Sharer-er
> Event Organizer
> 
> Add: Club Leader Badge

On Tue Mar 17 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> Add'l questions to consider:
> - Do we "retire" other badges, or just not offer them on the landing page? (that is, should someone who previously earned the Curriculum remixer badge still be able to access it? assuming yes.)
> - Do any of these badges come with add'l privileges? e.g. Should Super Mentors be able to approve certain other badge applications? 
> - Should the Event Organizer badge be system-issued based on adding an event to the database, or does it need to be human-verified?

On Wed Apr 08 2015, [thornet](https://api.github.com/users/thornet) commented:

> Notes from chat with **@****chrislarry33**: 
> 
> **Webmaker Mentor & Super Mentor:**
> -  consider an "almuni" badge. Then prompt to apply for / earn new badges.
> 
> **New participation badges:**
> -  "Frontline Educator" -- aka aligned practioner. Someone pledging or joining. 
> -  Club Leader
> -  Regional Coordinator
> -  Organizer
> 
> **Web Lit Badges:** 
> -  Privacy ones great to start with. 

On Wed Apr 08 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> Do we have to look at the badging criteria again or just the current badges align with v 1.1 of the map? 
> 
> I don't think it's a major change at all, maybe a couple of words. We will need to split the design and accessibility badges plus combine web mechanics.
> 
> Sent from my iPad
> 
> > On Apr 8, 2015, at 5:44 AM, Michelle Thorne notifications@github.com wrote:
> > 
> > Notes from chat with **@****chrislarry33**:
> > 
> > For Webmaker Mentor & Super Mentor: consider an "almuni" badge. Then prompt to apply for / earn new badges.
> > 
> > New badges:
> > 
> > "Frontline Educator" -- aka aligned practioner. Someone pledging or joining.
> > Club Leader
> > Regional Coordinator
> > Organizer
> > 
> > Web Lit Badges:
> > 
> > Privacy ones great to start with.
> > —
> > Reply to this email directly or view it on GitHub.

On Wed Apr 08 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> Excited for this!
> 
> A few questions:
> - How are you envisioning the alumni badges? Is it almost like a "currently inactive Mentor"? And then it can get re-activated?
> - Is the Web Lit Basics curriculum not associated with any badges?
> - Do we still want to have Event Host, Skill Sharer, and Curriculum Remixer badges?

On Thu Apr 09 2015, [Saallen](https://api.github.com/users/Saallen) commented:

> I would like to add a MozFest Volunteer badge to this list please -

**Comment by hannahkane** [comment]
Can we start a doc to capture and agree upon the following for each badge we want to offer:
- Criteria
- How is the badge typically granted—e.g. the user applies for it, and it's approved by a staff member; claim codes distributed at an event; batch issuing based on collecting email addresses from an event or list?
- Does the badge come with any additional functionality—e.g. add'l privileges?

Also, still not sure I totally understand what "alumni" badges means. Does that mean a badge that we no longer offer?

**Comment by ldecoursy** [comment]
@hannahkane what timeframe is this needed by?

**Comment by hannahkane** [comment]
I think we're on track to begin implementing the new badging platform on June 1 (contractor start date). While we won't necessarily need to know the specific badges on day 1, I think that makes sense as a target date to have our badge offerings worked out. At the very least, we should know if any of the badges will require any special functionality (e.g. do "alumni badges" require different behavior? do SuperMentors need to automatically get badge-granting privileges?)

**Comment by chrislarry33** [comment]
Can we make this main/only topic of next week's team call

**Comment by hannahkane** [comment]
We've decided to offer Club Captain and Regional Coordinator badges in Q3, so closing this.
