### ISSUE TITLE
Scope & Create "Incorporating Mozilla Club content in your school curriculum" Club Guide

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#370]
Mozilla Club Guide: Incorporating Mozilla Club content in your school curriculum
- [x] Create & receive approval on outline
- [x] Research credible resources/references
- [x] Write content by filling out approved outline
- [x] Receive feedback, edits, suggestions from the team
- [x] Once approved, put guide into Github template

Feedback, suggestions, and resource contribution appreciated!

**Comment by KGorr** [comment]
Guru @chadsansing, hoping to collaborate with you heavily on this one. Are you available to push resources, ideas, tips, real life examples, etc. my way? Happy to set up a call if that makes it easier. I'll also be pulling ideas, content as well. @amirad, anyone else that would be a great value add here?

**Comment by KGorr** [comment]
Let's use [this document](https://docs.google.com/a/mozilla.com/document/d/18Cn0TrrKMsV35nU0gDjqJfZ8u8mWW6sHGtfYejZc3gg/edit?usp=sharing) to compile resources and draft an outline.

**Comment by chadsansing** [comment]
@KGorr, you bet. Call after my PTO? Could also do a call on 3/25 before 2PM ET.

**Comment by KGorr** [comment]
@chadsansing, I'll put something on your calendar. Thanks!

**Comment by amirad** [comment]
Woop! There's a teacher in NYC, Gina, who would be good to involve here. We can ask her to review or for tips: ginatesoriero@gmail.com

**Comment by KGorr** [comment]
Requested collaboration from Paul Allison, Rafranz Davis, Gina Tesoriero, Kim Wilkens and team via a few easy questions over email. Will gather info from them, frame/draft content structure then ping @chadsansing when ready for further input.

**Comment by jgmac1106** [comment]
@kgorr here is a piece I wrote last year on using Clubs in my curriculum:
http://jgregorymcverry.com/how-i-forked-mozilla-web-clubs-for-a-formal-educational-setting/

**Comment by KGorr** [comment]
@jgmac1106 - this is incredibly helpful! Thank you! Feel free to send any other thoughts, best practices, and "be sure to add this to the guide" suggestions. We are open to all feedback to ensure this guide is as helpful as possible.

**Comment by KGorr** [comment]
Alright, @chadsansing - [this](https://docs.google.com/document/d/18Cn0TrrKMsV35nU0gDjqJfZ8u8mWW6sHGtfYejZc3gg/edit) is ready for your expertise and magic touch. We can send over to @amirad for review once you've looked it over. Thanks!

**Comment by KGorr** [comment]
@chadsansing - I'm going to push this to a future heartbeat...what are your thoughts on trying to wrap this up by May 20?

**Comment by KGorr** [comment]
Thanks for looking it over @chadsansing!  @amirad - this guide is now ready for your review. I pushed the milestone to the next heartbeat.

**Comment by amirad** [comment]
This is a reallllly good guide! Great job @KGorr - ready for publishing.

**Comment by KGorr** [comment]
Thanks, @amirad! Hopefully it is helpful to a lot of folks. Here's the finished product: mozilla.github.io/learning-networks/clubs/incorporating-mozilla-in-school Thanks to everyone who helped!
