### ISSUE TITLE
Scope & Create "How to find/secure funding for Mozilla Clubs" Club Guide

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#371]
Mozilla Club Guide: How to find/secure funding for Mozilla Clubs
Outline/Resources[ here](https://docs.google.com/a/mozilla.com/document/d/1qO0MezJeR0r0uzZ6zUIJ1ISaDtmOtBU5sItZhNVttTY/edit?usp=sharing).
- [x] Create & receive approval on outline
- [x] Research credible resources/references
- [x] Write content by filling out approved outline
- [ ] Receive feedback, edits, suggestions from the team
- [ ] Once approved, put guide into Github template

Feedback, suggestions, and resource contribution appreciated!

**Comment by KGorr** [comment]
@amirad, best folks to bring in for collaboration here?

**Comment by amirad** [comment]
Hmm Su has some recent experience helping a librarian with funding so might ask her what she did. @soapdog will of course have lots of valuable info to share here too. Maybe also ask Simona what she's pointed to for global Hives in the past or any resources she has.

**Comment by soapdog** [comment]
Do you both think that there might be some overlap with #365?

**Comment by KGorr** [comment]
Great thought @soapdog! I'm going to be working on #365 first, so after it is fully fleshed out, we can see if it makes sense. We may also find that there isn't a lot of information on the funding topic, which means adding it to another guide will may sense anyway.

**Comment by KGorr** [comment]
Hey there @amirad and @soapdog - just FYI I dropped a few things into the outline from my preliminary research. I definitely think this can be a separate guide. I'm waiting on thoughts from Su to include as well. Thoughts?

**Comment by amirad** [comment]
Sorry, yes this can be a separate guide from the partnering one. This might be a tough one to create lots of info for and we might want to have a call to action for those to submit info on their experiences.

**Comment by KGorr** [comment]
Thanks, @amirad . I'll add a CTA for more resources and input into the guide. I'll let you know once it's ready to review!

**Comment by KGorr** [comment]
@amirad @soapdog - This guide is ready for your eyes.  https://docs.google.com/document/d/1qO0MezJeR0r0uzZ6zUIJ1ISaDtmOtBU5sItZhNVttTY/edit

**Comment by soapdog** [comment]
Great work @KGorr 😸 this will be very useful for CCs!!!

**Comment by KGorr** [comment]
Thanks @soapdog! @amirad, let me know what needs tweaked before I add to the github template. (I think Lainie mentioned it may need to be run by legal?)

**Comment by amirad** [comment]
Yay! Most edits i put right into the doc but there are a couple comments on the side. I can share with Brian from Legal if that works.

**Comment by KGorr** [comment]
Great! I addressed the comments, so as soon as we hear from Brian we should be good to github and start sharing.

**Comment by KGorr** [comment]
Pending conversation with Brian - pushing to next heartbeat.

**Comment by hannahkane** [comment]
Removing this from the Ma 20 heartbeat, so we can close it!
