### ISSUE TITLE
Scope & Create "Turning Learners into Facilitators" Club Guide

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#372]
Mozilla Club Guide: Turning Learners into Facilitators
- [ ] Receive feedback, edits, suggestions from the team on the initial draft
- [ ] Rework guide based on suggestions
- [ ] Once approved, put guide into Github template

Feedback, suggestions, and resource contribution appreciated! 

Initial draft: https://docs.google.com/a/mozilla.com/document/d/1z819RZQSKuehlQM4yt5G74duurrkyYr2F5HdAnqXhj4/edit?usp=sharing

**Comment by soapdog** [comment]
cc @amirad @Carotejada @KGorr

**Comment by KGorr** [comment]
hey @soapdog - I took a look at this one and added lots of suggestions and edits. Please let me know if you'd like to discuss anything in detail. I'm more than happy to!

**Comment by soapdog** [comment]
@KGorr,

Accepted the edits there and commented on some of the issues raised. The content is not yet ready because I want to arrange the visuals you asked for first. Thanks for the edits! 🐹
