### ISSUE TITLE
Scope & Create "Methods for Introducing Topics" club guide

### ISSUE THREAD

**Issue by soapdog** [mozilla/learning-networks#373]
Mozilla Club Guide: Methods for Introducing Topics
- [ ] Receive feedback, edits, suggestions from the team on the initial draft
- [ ] Rework guide based on suggestions
- [ ] Once approved, put guide into Github template

Feedback, suggestions, and resource contribution appreciated! 

Initial draft: https://docs.google.com/a/mozilla.com/document/d/1uu2RzRjiTg7QnXGPuDOD3FbU9nijdKmbcfUwYIq8qhk/edit?usp=sharing

**Comment by soapdog** [comment]
cc @amirad @Carotejada @KGorr

**Comment by KGorr** [comment]
Hey @soapdog - sorry it took me awhile to get back with you on this. I made several edits and suggestions in the doc. I hope they are helpful!
