### ISSUE TITLE
May Mozilla Learning Newsletter: Gigabit

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#374]
Write and publish May Mozilla Learning Newsletter, which includes:

Community Spotlight
- [x] Contact Community Spotlight Nominee
- [x] Write Community Spotlight Article
- [x] Publish to blog.webmaker.org

Newsletter
- [x] Write newsletter block content (featured activity, events, announcements, spotlight]
- [x] Incorporate Hive community information
- [x] Send content to @stephaniemcv by April 22
- [x] Determine A/B testing plan for subject line and distribution date
- [x] Test and distribute newsletter by Friday, May 6
- [x] Post to Medium

CC: @ldecoursy @LindseyFrost @jenntbeard

**Comment by KGorr** [comment]
@LindseyFrost @jenntbeard - can you take a glance over the [newsletter content](https://docs.google.com/spreadsheets/d/19IGv9mqUA_oATs4wmtKkx1JX1B3fe2Iyc1PT-dmjXPc/edit#gid=939289325) by this Friday, April 22 (EOD) and let me know if there are any content additions, edits, or other feedback before it goes to layout? Thank you!

**Comment by KGorr** [comment]
Also, @stephaniemcv, I chatted with @ldecoursy and we'd like to make the order of this month's newsletter the following:
-     Featured Activity
-     Community Spotlight (new position)
-     Announcements (new position)
-     Upcoming Events 

Also, I can't remember if this will be an A/B test, or simply a new layout send to the entire list. Can you confirm? Thanks!

**Comment by jenntbeard** [comment]
The link in the Community Spotlight didn't work for me: https://wp.me/p6e0l1-3LY. Everything else looks good to me.

**Comment by KGorr** [comment]
Thanks @jenntbeard! We don't publish that link until right before the newsletter is released, so I'm glad it didn't work. ;) Sorry I forgot to mention that!

**Comment by LindseyFrost** [comment]
Looks great! The only thing I would change is this:

"Her\* work in Chattanooga\* has led to educational breakthroughs for
students, using gigabit technology to send high-definition 4K images of
microorganisms cross-country. She is also a thought leader around many
gigabit and education projects in the community, _including many Mozilla
Gigabit Community Fund and Hive Chattanooga projects_. Here's a sneak peek
of what she has to say about her work: "The blended learning models that
are and will be possible with gigabit technology are changing education-
maybe as much or more than the printing press." Read more here! [LINK:
https://wp.me/p6e0l1-3LY"

Thank you!

**Comment by KGorr** [comment]
@LindseyFrost - thank you! I adjusted.

**Comment by KGorr** [comment]
@ldecoursy (or @LindseyFrost)  - there is one final unresolved comment in the newsletter content (cell C7) and then it's ready for layout. Can you address today or tomorrow?

**Comment by KGorr** [comment]
@stephaniemcv - the newsletter content is ready for you!

**Comment by KGorr** [comment]
Update: the final distribution of the mailing list is pushed back to Monday, May 9. Will post on Medium today.
