### ISSUE TITLE
Supporting a CHI EduHack event w/ Web Literacy workshop/training for teachers

### ISSUE THREAD

**Issue by omnignorant** [mozilla/learning-networks#377]
Looking for support on running a local Web Literacy training for public school teachers.

We've been asked to support a local hack event focused on educators and public schools that's being run by Cleverbridge a local ecommerce tech company. They're calling the event "[Hack to the Future](https://hacktothefuture.splashthat.com)."

Mozilla is a featured partner/sponsor because we've offered to promote the event locally via Hive channels (newsletter, meetups, etc.) and because they've asked us to run a Web Literacy workshop for educators present at the event. The person coordinating the event had signed up to be a local regional coordinator in the fall, but her schedule fell through. She likes what we do.

I thought this would be a good opportunity to test out some of the materials we've used in other trainings this Fall and Winter. @jvallera @chadsansing @anmechung 

If we're all good on this, I could also use some broader promotional support to make sure that event branding and language are consistent, share out the event, or maybe even provide them with Mozilla event stuff if there's something to test @KGorr @ldecoursy @edrushka

**Comment by KGorr** [comment]
@omnignorant - I'm happy to tweet this event from @MozTeach and include it in the newsletter which will be going out a week before the event.  I'll draft a few things and send them your way to look over.

**Comment by jvallera** [comment]
@omnignorant this is awesome. Would love to hear more and help any way I can. Maybe a quick chat will help? Curious about deets, like how many educators, for how long, etc.

**Comment by edrushka** [comment]
The [name tags](https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eRzJyT2l3M1ZjMnM&usp=drive_web) and [participation guidelines poster](https://drive.google.com/a/mozillafoundation.org/folderview?id=0B4Q8pzCpDS_eVHJ0Mlc2MWUtX0U&usp=drive_web) are ready for use if they want to hack these with their own branding.

**Comment by omnignorant** [comment]
Thank you all! 
- [ ] @KGorr – sounds good. I'll review and edit when I get them!
- [x] @jvallera – let's setup a quick meeting w/ you, me and Kenyatta to get a brief overview and then we can decide if we should follow-up with @anmechung and @chadsansing  
- [x] @edrushka – I'll take a look at those and share with our planning partner at Cleverbridge

**Comment by omnignorant** [comment]
@edrushka are those drive files public?

**Comment by omnignorant** [comment]
from @jvallera... we're going to remix these sample agendas:
- https://d157rqmxrxj6ey.cloudfront.net/anmechung/43241/
- https://d157rqmxrxj6ey.cloudfront.net/anmechung/40860/

**Comment by ldecoursy** [comment]
@omnignorant I see the event is this weekend - anything else we can do to help?

**Comment by jvallera** [comment]
Excited to hear how it goes @omnignorant and to see what/how you remix. Also curious to hear what your participants think. Keep us posted :)

**Comment by chadsansing** [comment]
So excited - can't wait to hear feedback and suggestions, @omnignorant.

**Comment by omnignorant** [comment]
Hey @chadsansing @jvallera @ldecoursy the event was GREAT! 

I had an audience of about a dozen folks who were classroom teachers from grade 2 to high school, educational administrators, leaders, and folks from Cleverbridge, the hackathon host. A lot of excited interest from their team in particular: they train non-developer, entry-level employees to better understand HTML & CSS to improve their overall workplace culture and they found our tools to be great! Lots of excitement about tag tag revolution in particular.

You can find my agenda Remix – 2 hours focused on Navigate, Search, Code, Remix and Share – here: https://thimbleprojects.org/omnignorant/67868/

I had one elementary teacher particularly geeked on HW excuse generator who wants to remix it to generate poetry or _similes_ (note, not smiles, though I suppose those too)!
