### ISSUE TITLE
April #TTWchat production

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#378]
When: Thursday, April 28

Planning document [here](https://docs.google.com/a/mozilla.com/document/d/1RMcRqFyZpHsfNjFmZ52BPPVPmfe4PxdS1KT-j43E4ww/edit?usp=sharing).

**Pre-chat To Dos:**
- [x] Planning meeting
- [x] Determine new KPIs
- [x] Write/Post Discourse thread explaining process (Include sample tweet)
- [x] Draft promo tweets (including 1-2 tweets explaining process)
- [x] Draft questions 
- [x] Reset #TTWchat Sprinklr dashboard
- [x] Schedule Qs in Sprinklr
- [x] Send out calendar invite to MozTeach team (Include sample tweet)
- [x] Send personal invites for participation

**Post-chat To Dos:**
- [x] Storify
- [ ] Write & post summary blog article
- [x] Follow backs
- [x] Compile engagement report

**Comment by jgmac1106** [comment]
@adamlofting and @kgorr do we have a tool for archiving Tweets yet?
Temporary or for the community that may not have access to internal
analytics you may want to set up a Twitter Archive for tor Google Sheets
using an associated Google Account.

**Comment by adamlofting** [comment]
@jgmac1106 no tools setup for that at the moment, but I like the idea of storing to a place that community can access easily.

**Comment by jgmac1106** [comment]
Okay if you have a Google Account you want to use setting up TAGS is super
easy. I can set it up and hand off ownership if needed.

**Comment by ldecoursy** [comment]
@jgmac1106 @adamlofting Is this different from posting a Storify following each tweetchat?

**Comment by jgmac1106** [comment]
Yes a storify is a media product. TAGS is an archive. Allows for open
research and @adamlofting can play with SNA. Here is an example:
https://docs.google.com/spreadsheets/d/1xdWm5pvDM9GiHnLQmbZxIwqA4JOLvoHnZKZdvit0-SI/edit?usp=sharing

Basically I see Storify as a way to curate and shape the data. TAGS allows
us to get the raw data and a searchable database.

Here is one using the #mozfest hashtag:

https://docs.google.com/spreadsheets/d/15v9XCq_FGR5WL4-oWyhSNOyKSuNLmJgveyqfBczQEBg/edit?usp=sharing

---

On another note is it considered bad form to comment on these meta-tickets?

**Comment by ldecoursy** [comment]
Thanks @jgmac1106! Perhaps worth filing as a separate ticket if interested in setting this up for evergreen purposes, since this is for planning the April TTWchat specifically.

**Comment by KGorr** [comment]
[Storify](https://storify.com/kgorr/internet-of-things-ttwchat#publicize)
[Engagement Report](https://docs.google.com/a/mozilla.com/document/d/1wJ-It0Vdz2ZG06bV5fA-F0fzQ6nj0y0tRx6Mmg_3vaY/edit?usp=sharing)
