### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Storytelling with Three Buttons

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#381]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session02-three-buttons.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50664

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-storytelling-with-three-buttons/760).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson plan**
• Intro - There is a lone “Write the web” subheader at the top with no content beneath
• 2nd bullet under learning objectives; “Code multiples button” should be “code multiple buttons”?
• Materials typo: “Internect-connected computers”
• #1 Prep – remove 2nd “for” from 1st sentence
    o   Thimble link has typo & doesn’t work
• #2 Round Robin – remove “a” from # 3 in activity instructions
    o   #6 typo “fnctions”
    o   Very last word on the page typo “broswers”
• #3 Coding Multiple Buttons – 1st sentence typo “hit each button the page” & remove the word “all”
    o   7th paragraph has an extra “the”
    o   Last paragraph, 1st sentence, remove the 1st “and”
• #4 Reflection – 5th bullet point typo “scriptes”

**Thimble Tutorial**
• 3rd paragraph typo “spearate” 
• 4th paragraph remove 1st “and”
• 5th paragraph – remove “also” and change “use” to “You”
• #2 2nd paragraph typo “vairbales”
• #3 last sentence typo “paet”
• #4 last sentence typo “whenver” 
• #5 last paragraph typo “youe” and is this missing the step about clicking on preview to test the buttons?

**Comment by chadsansing** [comment]
Noted & edited - thanks, @KGorr!

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
