### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Simple Story Generator

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#382]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session03-simple-story-generator.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50667/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-simple-story-generator/761).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**
• Intro - There is a lone “Write the web” subheader at the top with no content beneath
• Materials typo “Internect-connected computers”
• #1 Prep – remove 2nd “for” from 1st sentence
    o   Thimble link has typo & doesn’t work
• #2 Storytelling Buckets – typo in #12 “eash”
• #3 Coding with Arrays: 1st sentence typo “broswers”
    o   typo in today’s activity link and not working
• #4 typo in 4th bullet “yoru”
    o   5th bullet typo “havd”

**Thimble Tutorial**
• #1 change “an” to “a” in 2nd sentence
    o   in last paragraph, typo: Mozilla Develope Network 
• #2 6th paragraph typo “Replce”
    o   There is something wrong in that same paragraph here “go with each the name of each variable that is an array.” An extra “each”?
    o   Optional paragraph typo “un” and “vairable's”
• #4 2nd paragraph typo “of web address” should be “or web address” & remove “now” at the end of that sentence.

**Comment by chadsansing** [comment]
Invaluable help, as always, @KGorr. I think we have enough data now to make a @chadsansing typo bot for Twitter or automatic curriculum generation :) You know how I love those broswers.

**Comment by KGorr** [comment]
@chadsansing - Haha! Happy to help. :)

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
