### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Storytelling with Pictures

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#383]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session04-storytelling-with-pictures.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50669/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-storytelling-with-pictures/762).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**
• Overview:
    o   “Write the web” subheader has not content beneath
    o   Materials typo “Internect-connected computers”
• # 1 Preparation – Thimble link not working
• # 2 Setting the Tableau
    o   This sentence is not super clear: “The script we'll write today will check the webpage to see which picture is on it and then respond by showing the next picture in the story - or by restarting the story after it ends.” Since it is the introduction to the whole activity, I would break it up into 2-3 sentences so there is no confusion.
    o   1st sentence in the second paragraph is missing the closing  quotation mark.
    o   # 2 – “groups” should be singular
    o   # 4 typo “theu”
    o   # 6 needs a bit more clarity. How does the 1st student know when to go again if they can’t see the 3rd student move from right to left? Do the students immediately turn right again after the next person in line finishes their movement?
    o   # 8 is missing the word “for” before “each group to perform.”
• # 3 Storyboarding your script. The image doesn’t directly connect to the copy. Maybe adding “Here is an example template” or something like that will make it more clear.
    o   Last sentence on the page typo “pout”
• # 5 Reflection – 5th bullet, second question phrase needs capitalized

**Thimble Tutorial:**
• # 1 typo in 1st paragraph “JavScript”
    o   2nd paragraph typo “conditioal”
• # 3 last paragraph – missing the instruction to click on the preview tab to test the button
• # 5 # 1 typo “sats”
• # 6 4th paragraph typo “web adress”
    o   6th paragraph typo “wscript”
    o   last paragraph missing instruction to click on preview to test
• # 7 2nd paragraph typo “finx”
• # 8 last paragraph typo “thr”

**Comment by chadsansing** [comment]
Thanks for helping me "finx" the page, @KGorr.

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
