### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Storytelling with User Input

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#384]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session05-storytelling-with-user-input.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50670/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-storytelling-with-user-input/763).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**
Overview
- Weird thing – the image scrolls up (and disappears) when you scroll down on the page, but the rest of the nav bar stays put. It doesn’t do this on any other page.
- Write the Web section is empty
- Typo under materials: “Internect-connected computers”

Preparation
- Remove “for” in first sentence
- Thimble link not working

Storytelling with templates
- Typo in 1st sentence: “stoeies”
- Remove the strikeout part of this sentence and add the comma: “This will look an awful lot like fill-in-the-blanks stories, which are popularly known as Mad Libs.”
- 1st sentence after image typo “inut”
- 1st numbered bullet needs ending punctuation to match the others
- 2nd bullet – change “pass out” to “distribute” (2xs & also in 3rd bullet…just an old rule from my training development days to never say “pass out” cause of what else it means, haha) and typos “ate” should be “are” and “repared” should be “prepared”

Rewriting Stories
- 1st sentence is missing the word “on” here, “hit the button the page”

**Thimble Tutorial:**
- # 4, 7th paragraph typo “adbove”
- # 5 seems to need line call outs to make it clear where they are making the changes
- # 6 typo in 1st paragraph “inouts” & last paragraph “spota”
- the “template “story needs a comma after the 1st input

**Comment by chadsansing** [comment]
Super - thanks, @KGorr!

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
