### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Storytelling with Color

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#385]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session06-storytelling-with-color.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50671/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-storytelling-with-color/764).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**

Overview
- Write the web section empty
- Materials typo: “Internect-connected computers”

Preparation
- Thimble link not working
- Why is this needed? “Also post the link to the code example, or "pen," used in the lesson.”

Annotating a gallery Walk
- Last word on page typo “broswers”

Mixing Colors in the Web
- In the last bullet, there is an HTML color code callout. Is that supposed to have a comma separating the last 2 color value numbers?
- Today’s project hyperlink not working
- Last word typo “broswers.” ☺

Storytelling with colors
- Remove “the” from 1st sentence  
- Should you hyperlink “step three, Mixing Colors on the Web” about half way down the page?

Reflection
- 1st bullet, 2nd comma is a typo period

**Thimble Tutorial:**
- # 1 – missing preview tab instructions?
- # 2 last paragraph missing preview tab instructions?
- # 4 – typo “don;t”

**Comment by chadsansing** [comment]
Many thanks, @KGorr! I'm going to leave out that hyperlink since the side navbar is right there and we want learners to keep going - make sense?

**Comment by KGorr** [comment]
+1!

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
