### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Creating a Storytelling Resource

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#386]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session07-creating-a-storytelling-resource.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50675/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-lit-ii-creating-a-storytelling-resource/765).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by KGorr** [comment]
**Lesson Plan:**
Overview:
- Write the web subhead has no content – it’s like that on all the teaching kits…is that purposeful?
- Materials typo “Internect-connected computers” ☺
- Same weird photo scrolling problem as the other teaching kit

**Preparation**
- Thimble link not working
- I think the 5th paragraph should link to examples (more on that in discourse).

**Defining a Cat Object**
- # 2 “out loud” should not be hyphenated
- # 3 typo “drswing”
- # 4 has 2 quotation marks before “hair color”
- very last word typo “broswers” (This is a funny typo that keeps recurring and I laugh every time I say it in my head the way it is spelled. Haha!)

**Storytelling with OOP**
- 1st sentence typo “browwers” (Seriously, I am cracking up now! I think it’s obvious that I am doing this on a Friday afternoon after a long week. HA!)
- This section also does the weird photo scrolling away thing

**Thimble Tutorial:**
- Intro – 4th bullet has double “the”
- # 1 – 4th paragraph typo “parentehses”
- # 2 – missing the “go to preview tab” instructions?
  - 5th 10th & 11th paragraph typo “vairbales”
- # 3 2nd paragraph needs closing punctuation
- # 5 typo “atrrbiutes” & something is wrong with this phrase “to see how the change you make affect the page”
- # 6 2nd paragraph has some weird spacing after the 2nd comma

**Comment by chadsansing** [comment]
Got it, @KGorr - no fixes on the image or Write the web content for now, though refreshing and waiting to scroll (so all the CSS and JS loads) sometimes helps with the image problem.

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
