### ISSUE TITLE
[Testing] [Intermediate Web Lit II] Storytelling with Interactive Fiction

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#387]
Help test this new storytelling-with-scripts activity!

Lesson plan: http://chadsansing.github.io/curriculum-testing/intermediate-web-lit-two/session08-storytelling-with-interactive-fiction.html#overview
Thimble Project: https://thimbleprojects.org/chadsansing/50676/

Looking for help with copy editing, broken links and images, and other bugs here on GitHub.

Looking for feedback on content, difficulty, and tutorials [over on Discourse](https://discourse.webmaker.org/t/testing-intermediate-web-literacy-ii-storytelling-with-interactive-fiction/766).

Testing closes on 4/29/16.

[Back to issues.](https://github.com/mozilla/learning-networks/issues)

**Comment by ghost** [comment]
Hey @chadsansing not sure if it was on purpose, but web lit colors are all grey on the lesson plan page

**Comment by chadsansing** [comment]
@KipOmaha - grey it is for now. As we move ahead from launching the Web Lit Map 2.0 the styling for new skills buttons will likely be different from that of the older buttons referencing 1.0.

**Comment by KGorr** [comment]
**Lesson Plan:**
Overview
- Write the web subheader has no content
- Materials Typo “Internect-connected computers”
- Weird scrolling image thing

Preparation
- Typo in second paragraph “it's”
- Thimble link not working

Paper Prototyping 
- 2nd paragraph – I would change “work” to “lesson” or “activity”
- # 1 – change “apiece” to “each”
- # 3 & # 4 typos – “prototpyed” & “selecing”
- # 9 typo : “windo”

Coding Interactivity
- 1st paragraph typo “browwers”

**Thimble Tutorial:**
- 2nd paragraph of intro “collaborative create” – not sure the variation it is supposed to be…
- # 2 in overview typo “What's are”
- # 1 1st paragraph typo “confitions”
  - 4th paragraph typos “contine” & “weboage”
- # 2 title typo “What's are”
  -  In your 1st set of symbol explanations – the bottom 2 are duplicates of of the above 2, but with different explanations
  - Last paragraph has double “if”
- # 3 2nd paragraph typo “reponse”

**Comment by chadsansing** [comment]
Had to switch to "browwers" before "broswers" got old, @KGorr - thanks muchly!

**Comment by chadsansing** [comment]
The curriculum template might get a light overhaul soon to improve readability. In the meantime, please ship me any addition feedback here or via email.
