### ISSUE TITLE
Published xray goggles projects

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#389]
I tried a few xray projects with students and they all came out like this once published: https://thimbleprojects.org/sequoia09/54846/

I thought it might be a proxy blocker but then xray shouldnt load. Is there anything we can do to fix it?

**Comment by Pomax** [comment]
This is an unfortunate side effect of the http-resources-on-https-websites situation we're currently in, https://github.com/mozilla/goggles.mozilla.org/issues/27 is open for this on the goggles side.

**Comment by jgmac1106** [comment]
Okay will close as a dupe
