### ISSUE TITLE
Why are we using a different hashtag for #ttwchat than #teachtheweb

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#390]
I was thinking about archiving and how we can surface different metrics and network activity and that made me question why we the #teachtheweb chat would have a different hashtag.

Its been kind of spammy since the pledge auto-tweeted but its still the central place for Mozilla Learning on Twitter. We shouldn't dilute it further. 

I see no problem having the thimble chats, x ray goggle chats, or the new show chat on the #teachtheweb hashtag. The former are topics the latter is a channel.

**Comment by jgmac1106** [comment]
Going to close so I don't forget to later. 

TLDR: Fewer hashtags better. When adding new social media channels it only makes sense as long as it doesn't cannibalize established spaces.

**Comment by ldecoursy** [comment]
Sorry for delayed response @jgmac1106! We wanted to experiment with a separate hashtag, in part to help us measure engagement/success of the new monthly tweetchats. We'd like to give it another month or so but definitely will consider this when we review how the new engagement channels are working overall.

**Comment by chadsansing** [comment]
Close this, @jgmac1106 or @ldecoursy?
