### ISSUE TITLE
Review Every1Mobile App for Mozilla Clubs

### ISSUE THREAD

**Issue by amirad** [mozilla/learning-networks#391]
Wanting to share an early release of the app we've been building with Every1Mobile: http://mymoz.club/home/mymozclub/ 

Things to note: 
•Updates are happening daily and will continue even though we are doing a soft launch with the clubs in the next week. Updates to profile pages, a code of conduct, some light banners on secondary pages, a club captain corner etc. are all coming in the next week. 
•This is an html based app for easy access and use by club captains and club members. We are trying to keep it easy to load and not brought down by images/media etc.
•This is only going to be open to our 16+ Mozilla Clubs in Nairobi and Cape Town and for women and girls to start. Objective has been to be a safe space for them to learn and share. 

We have been leaving feedback in this pad https://public.etherpad-mozilla.org/p/every1mobile or you can do it here

@chadsansing @ldecoursy @xmatthewx @flukeout @chrislarry33 please check it out and let me know if there are any flags.

**Comment by ldecoursy** [comment]
@amirad Should I move this? still collecting feedback or ok to close?
