### ISSUE TITLE
Add a step to tag annotations on letters 2nextprez step 4

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/learning-networks#393]
Add 4. How to add the #2nextprez tag to your annotation. 

(technically hypothes.is ignores the has but so many users do it the system take them both ways now).

**Comment by chadsansing** [comment]
Is this for the lesson plan w/ Hypothes.is? Or inside the letter project on Thimble?

**Comment by chadsansing** [comment]
We've added the hashtag to the title of each project - is that enough to aid discoverability, @jgmac1106? Since there is no tag feature, just the opportunity to type hashtags as part of the description, I'm not sure what else is wanted/needed. What do you think?

**Comment by chadsansing** [comment]
@gideonthomas, @flukeout - think we'll have tagging soon, or should we close this? @jgmac1106, did the hashtags in the title of each project help any with discoverability? Can we close?

**Comment by gideonthomas** [comment]
Tagging should be easy to enable, just need UI for it.
