### ISSUE TITLE
May Mozilla Community Call: Gigabit [Planning]

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#394]
Gigabit Community Call is gonna ROCK...Let's do it!

May 25: 11am HADT/ 1pm PT/ 4pm ET/ 8pm GMT/ 10pm SAST

[Monthly Community Call Planning Template](https://docs.google.com/document/d/1_IgXfSXHQ-iC56oVdE5i9Yn8QrRjp04ABZMQC-ebHQ0/edit)

**Call Curator To-Do List: @LindseyFrost @jenntbeard**
- [x] Solidify date/time on Mozilla Ed Hub Editorial Calendar
- [x] Book 2-3 speakers (cc Kristina on confirmation emails)
  - [x] Template logistics email to send speakers AFTER they are booked [here](https://docs.google.com/a/mozilla.com/document/d/1UL-P1D6IsTr7LJFZy5RAoW3B5SxdIvsAwSvgTZDcEN8/edit?usp=sharing). Highlighted in yellow are the details you’ll need to change. 
- [x] Prepare paragraph summary of call content & speakers (for marketing)
- [x] Confirm agenda and add to etherpad (ideally 3 days before event day or sooner)
- [x] Invite participants
  - [x] Send a personalized email to your network 1-2 weeks before the call urging those who might be interested in the topic to attend will help increase participation.
  - [x] Send call [invite templates](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit) or tweets to your speakers for them to share with their network.

**Production To-Do List: @kgorr**

Pre Call:
- [x] Set up new G+ event page
- [x] Create new etherpad template
- [x] Send new live stream embed code & landing page copy to programmers
- [x] Add speakers & call details to youtube page/G+ page as soon as it is available
- [x] Write and distribute marketing communications, includes 
  - [x] tweets
  - [x] discourse post
  - [x] calendar invites to mozteach list serv
  - [x] mofo email invitation
- [x] Ping Hives with [invitee template](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit)

Day of Call:
- [x] Hives, @MozTeach, MLN team to tweet reminder
- [x] Broadcast/produce HOA live!

Post Call:
- [x] Send thank you emails to speakers (day-of)
- [x] Follow participants on Twitter from @MozTeach
- [x] Tweet mass thank you to participants
- [x] Compile data for engagement report
- [x] Write and post call summary blog post

**Comment by jenntbeard** [comment]
We have confirmed Chad Sansing as a speaker - he will cover dreaming in VR. I haven't send him the speaker template email but he does have a calendar invite for the May 25 at 3pm CST.

**Comment by KGorr** [comment]
Discourse post: https://discourse.webmaker.org/t/may-2016-community-call-gigabit/804

**Comment by KGorr** [comment]
@jenntbeard - I know you are swamped this week with all of the exciting Gigabit events and announcements. Can I help with invites for the comm call?

**Comment by jenntbeard** [comment]
Yes, we are meeting tomorrow morning as a team and will discuss. Thank you!

**Comment by jenntbeard** [comment]
We are adding contacts here: https://public.etherpad-mozilla.org/p/invites. Others will be sending their invites directly to their contacts. Thanks for your help!

**Comment by KGorr** [comment]
Thanks, @jenntbeard! All invites have been sent.

**Comment by jenntbeard** [comment]
Fantastic, thank you so much!!!

**Comment by KGorr** [comment]
We are going to combine the community call recap with the recap for the #TTWchat (#396). I'll aim to post next Wednesday.

**Comment by KGorr** [comment]
Blog post: https://blog.webmaker.org/transforming-learning-through-gigabit-technology
Engagement report: https://docs.google.com/spreadsheets/d/1YVBLfq55XGzFDCSgdkfA7L-b9tUkZDJMqhnSUwk3CFk/edit#gid=209502847

Closing!
