### ISSUE TITLE
Updating Club Resources with learning.mozilla.org

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#407]
I'm doing some research on our materials and discovered several Club Guides/resources that reference **teach.mozilla.org** and need to be updated to **learning.mozilla.org**. I can tackle the club guides easily enough. Hoping to get help from those who own the other resources (cc'd). Let me know if you have any questions! 
- [x] https://github.com/MakerBox-NZ/makerParty-WGTN/blob/master/mozillaClubs_template.svg @cyanidecupcake
- [x] http://mozilla.github.io/learning-networks/clubs/train-the-trainer-guide/#introduction
- [x] http://mozilla.github.io/learning-networks/clubs/hosting-mozilla-club-in-library/
- [x] http://mozilla.github.io/mozilla-club-guides/your-first-month-as-a-club-captain-without-rc/
- [x] http://mozilla.github.io/learning-networks/clubs/encouraging-participatory-playful-learning/#activity-ideas
- [x] http://mozilla.github.io/learning-networks/clubs/increasing-womens-web-literacy/#activity-ideas
- [x] http://mozilla.github.io/learning-networks/clubs/participation-to-collaboration/#activity-ideas
- [x] http://mozilla.github.io/learning-networks/clubs/growing-community/#activity-ideas
- [ ] https://www.youtube.com/watch?v=I6MbOtWyaKE&feature=youtu.be @tinaverbo
- [x] https://docs.google.com/presentation/d/18TvYogZefxmybDmAPxXVyqj9r4NEoH7ngS3V5hwuYBE/edit#slide=id.g1191d7057f_1_0 @amirad 
- [x] https://thimbleprojects.org/juliavallera/45073/ @jvallera 
- [ ] Content on mozilla.teachable.com @Carotejada

**Comment by cyanidecupcake** [comment]
I will update the Mozilla clubs template first thing next week.  I have added it to my task list so I don't forget and will let you know when it is complete.

**Comment by KGorr** [comment]
Thanks @cyanidecupcake!

**Comment by jvallera** [comment]
Done @KGorr

**Comment by KGorr** [comment]
Thanks, @jvallera!

**Comment by cyanidecupcake** [comment]
My resources have been updated, @KGorr.

**Comment by KGorr** [comment]
Thanks @cyanidecupcake!

My eyes are now crossing, but I have now updated all Club Guides (with both learning.mozilla.org and our new twitter handle @MozLearn). Whew.

@amirad - I just requested access to the doc you are cc'd in so that I can make the small change there.

@tinaverbo and @Carotejada - please let me know if I can help make the updates on the remaining resources.

Thanks so much, team!

**Comment by hannahkane** [comment]
Removing from past heartbeat, but feel free to add to an upcoming one

**Comment by tinaverbo** [comment]
Sorry for the delay @KGorr here's the updated vid:
https://youtu.be/ftwyuHGLk-A

**Comment by KGorr** [comment]
excellent @tinaverbo! Thank you. Any way you can send me a link so I can download? I'd love to re-upload it to the Mozilla Learning YouTube Channel.

**Comment by tinaverbo** [comment]
here's the link: [Vid](https://drive.google.com/file/d/0B0Nrf69MLrXzbTUxNUtPLTU4Q1U/view?usp=sharing)

**Comment by KGorr** [comment]
Thank you @tinaverbo! Since teachable is an ongoing project, @Carotejada has instructed me to move forward. Closing this ticket! Thanks all!
