### ISSUE TITLE
Gigabit Hive Austin Logo creation (and CHA recreation)

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#408]
#### DARCI

Driver: @jenntbeard
A:
R:
C:
I: @LindseyFrost @omnignorant 
#### Overview

With the launch of our newest Gigabit Hive, we are in need of a logo for them. We also can't locate a high resolution version of the Hive Chattanooga logo. Should both use the hollow pipe version of the design (like the KC example below).
#### Links
- Existing version of Gigabit Hive logo: https://www.facebook.com/hivecha
- https://drive.google.com/open?id=0B5jxGZykGTyFUnFJZG5uSzlaYUU (KC version)
#### KPIs
- [ ] Creation of Austin version of existing Mozilla Gigabit Hive logo
- [ ] Locate/create higher res version of Gigabit Hive Chattanooga logo
#### Key Deadlines
- [ ] Hive Austin will start public activities on July 11 (it would be great to have the logo by July 1 for promotional materials)

**Comment by hannahkane** [comment]
@sabrinang - can I assign this to you?

**Comment by ldecoursy** [comment]
cc @mcdermott415 

I think ideally we'd move Cha, KC and Austin to a version that looks like NYC, with Mozilla in the logo too. Same for Chi and TO.  That will help distinguish Mozilla-stewarded Hives from those that are not stewarded/staffed/funded by us.

**Comment by jenntbeard** [comment]
So, the closed version of the outer pipe? Just want to make sure we're being consistent across our Gigabit channels - we're using the plain open pipe on the Hive Twitter handles (see https://twitter.com/hivekc for reference, but are happy to change to the recommended version). Thanks!

**Comment by mcdermott415** [comment]
Hi All,

The sooner we can take advantage of Lainie's suggestion above, the better!

M

**Comment by jenntbeard** [comment]
If we are creating a different Hive CHA logo, let's also make for KC. Thanks!

**Comment by chrislarry33** [comment]
@ldecoursy's suggestion is what I would endorse

**Comment by xmatthewx** [comment]
Is there any reason that we shouldn't add `Austin` to this logo? 

<img width="155" alt="screenshot 2016-05-26 13 05 28" src="https://cloud.githubusercontent.com/assets/53411/15583155/9733b3de-2342-11e6-85b9-23fa5c7e6fb8.png">

Based on the conversation in [this thread](https://github.com/MozillaFoundation/plan/issues/790), the plan seemed to be to consolidate brands and move toward the Mozilla name to connect our various initiatives. Given Austin's newness, using the hive logo seems like a step back that will require more work and explanation as we move forward.

I don't have all the info regarding these programs and grants – forgive any mistaken assumptions. Purely from a brand and comms perspective, that's my recommendation.

**Comment by jenntbeard** [comment]
@xmatthewx That is the Mozilla Gigabit Community Fund logo. This request is for the Gigabit Hive Austin logo - we operate both programs in each city.

**Comment by LindseyFrost** [comment]
Hi all,

Apologies for slow response. The Mozilla Gigabit word mark @xmatthewx includes above is used for the Gigabit Fund project across all Gigabit Hive cities.  Because these Gigabit Hives are more than just the Gigabit Fund though, each needs its own Hive logo.

Updated Hive Chattanooga, Hive Kansas City, and Hive Austin logos should look like the Hive New York one here: http://hivenyc.wpengine.com/wp-content/uploads/Mozilla_HiveNYC_Official_LOG0x2501.png

Thanks!

**Comment by jenntbeard** [comment]
Hi - just checking in on status for this. @omnignorant is now in Austin and will need this logo ASAP for his Hive activities. Thanks!

**Comment by xmatthewx** [comment]
I spoke with @mcdermott415 about this while in London, but I failed to follow up. Sorry for the delay. Am I correct in assuming she holds a birds eye view of Hive past, present, and future? 

@hannahkane – I've added it to our list to triage on Friday.

**Comment by LindseyFrost** [comment]
Hi! Noting that Hive Austin has tremendous promise outside of Gigabit work
and therefore needs its separate logo beyond that of the Mozilla Gigabit
work as Hive CHA and Hive KC already do.  Though we're consolidating web
presences elsewhere to simplify life, I think maintaining these separate
city logos (Gigabit or not) is very important, especially to the local
funding community in Austin who is very interested in our local work. To
maintain the attention of this funder community and our momentum in ATX,
the local logo is needed ASAP.  Thanks!

**Comment by xmatthewx** [comment]
@hannahkane – based on a discussion in this doc, we should: 
- Create an Austin logo that mirrors Hive NY
- Produce files for use in print and digital
- <s>I recommend that we do a second logo using the same elements with a revised hierarchy to emphasize Mozilla more (quick draft as demo, no polish necessary).</s>

**Comment by hannahkane** [comment]
@xmatthewx - putting this in the next milestone, but can you clarify your third bullet? Are you suggesting we create two options and then decide which to use?

**Comment by xmatthewx** [comment]
We'll use a logo that mirrors Hive NY. You can ignore that 3rd bullet.

**Comment by flukeout** [comment]
Just to double-check, this is what we're after, correct?

![image](https://cloud.githubusercontent.com/assets/25212/17118675/84f9b00c-5276-11e6-909d-c12d7ad7b299.png)

**Comment by omnignorant** [comment]
@flukeout yes 😅 ☀️

**Comment by flukeout** [comment]
Cool, here are some files for it then...
- Illustrator - https://dl.dropboxusercontent.com/u/109902/logos/hive-austin-logo.ai
- PDF - https://dl.dropboxusercontent.com/u/109902/logos/hive-austin-logo.pdf
- Transparent PNG - https://dl.dropboxusercontent.com/u/109902/logos/hive-austin-logo.png

Slight adjustment from the one I just posted, looks like this...

![image](https://cloud.githubusercontent.com/assets/25212/17119094/c38ceada-5278-11e6-9f4c-44dff9f95ea0.png)

**Comment by omnignorant** [comment]
Awesome!!! Any chance we could do some single colors too? Black, white, and Orange should do. Just transparent PNGs for those would be AOK.

**Comment by flukeout** [comment]
Oh for sure...
- Orange - https://dl.dropboxusercontent.com/u/109902/logos/hive-austin-logo-orange.png
- Black - https://dl.dropboxusercontent.com/u/109902/logos/hive-austin-logo-black.png

**Comment by flukeout** [comment]
Okay, closing but happy to make adjustments or provide alternate versions as needed.
