### ISSUE TITLE
June Mozilla Community Call: Summer Learning & Making [Planning]

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#409]
Summer Learning and Making Community Call is gonna be F-U-N!

June 29: 11am HADT/ 1pm PT/ 4pm ET/ 8pm GMT/ 10pm SAST

[Monthly Community Call Planning Template](https://docs.google.com/document/d/1_IgXfSXHQ-iC56oVdE5i9Yn8QrRjp04ABZMQC-ebHQ0/edit)

**Call Curator To-Do List: @jvallera** 
- [x] Solidify date/time on Mozilla Ed Hub Editorial Calendar
- [x] Book 2-3 speakers (cc Kristina on confirmation emails)
  - [x] Template logistics email to send speakers AFTER they are booked [here](https://docs.google.com/document/d/1UL-P1D6IsTr7LJFZy5RAoW3B5SxdIvsAwSvgTZDcEN8/edit). Highlighted in yellow are the details you’ll need to change.
- [x] Prepare paragraph summary of call content & speakers (for marketing)
- [x] Confirm agenda and add to etherpad (ideally 3 days before event day or sooner)
- [x] Invite participants
  - [x] Send a personalized email to your network 1-2 weeks before the call urging those who might be interested in the topic to attend will help increase participation.
  - [x] Send call [invite templates](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit) or tweets to your speakers for them to share with their network.

**Production To-Do List: @kgorr**

Pre Call:
- [x] Set up new G+ event page
- [x] Create new etherpad template
- [x] Send new live stream embed code & landing page copy to programmers
- [x] Add speakers & call details to youtube page/G+ page as soon as it is available
- [x] Write and distribute marketing communications, includes
  - [x] tweets
  - [x] discourse post
  - [x] calendar invites to mozteach list serv
  - [x] mofo email invitation (or mattermoz)
  - [x] Ping Hives with [invitee template](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit)

Day of Call:
- [x] Hives, @MozLearn, MLN team to tweet reminder
- [x] Broadcast/produce HOA live!

Post Call:
- [x] Send thank you emails to speakers (day-of)
- [x] Follow participants on Twitter from @MozLearn
- [x] Tweet mass thank you to participants
- [x] Compile data for engagement report
- [x] Write and post call summary blog post

CC: @omnignorant

**Comment by jvallera** [comment]
@omnignorant you mentioned that Lisa Kim might be a good addition to the call. Still think so? If so, do you mind connecting me? I have to NYC people confirmed so looking for one/two more.

**Comment by KGorr** [comment]
@flukeout @hannahkane Here is June's community call embed code:

`<iframe width="560" height="315" src="//www.youtube.com/embed/Uig7s0fChj8" frameborder="0" allowfullscreen></iframe>`

And here's the etherpad: https://public.etherpad-mozilla.org/p/mozcommunitycallJune16

**Comment by hannahkane** [comment]
@KGorr - thanks! 

Do you have:
- description/teaser 
- list of speakers
- Date / time / topic for July call
  ?

**Comment by KGorr** [comment]
Hi @hannahkane - @jvallera is helping finalize the page content. I'll send it your way once it is finished. It's June 29; 1pm PT / 4pm ET / 8pm UTC and we'll be discussing Summer Learning & Making!

**Comment by KGorr** [comment]
Flagging this for myself to update next week: https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit

**Comment by KGorr** [comment]
@hannahkane @flukeout - Here is the copy for the landing page:

Upcoming Call Box:
June 29, 1pm PT / 4pm ET / 8pm UTC
Learning & Making
Featured Speakers: Lisa Kim, Youth Commission Director for Mikva Challenge in Chicago, IL;
Niberca (Gigi) Polo, Emoti-con 2016 design fellows lead, Part-Time Associate Teaching Professor at Parsons The New School for Design, and Principal at Myellow Boots Studio; Dr. Dixie Ching, co-lead of the Hive Research Lab; Andy Forest, lead at STEAMLabs.

Content below call box: (is this too long?)
Summer learning loss is a real challenge, especially for those who may not have access to enriching educational opportunities. There has been a good amount of research and discussion on this topic, and on the June community call, we’ll be exploring the types of fun and engaging learning experiences that can–and do–happen during the summer. Educators from Hive NYC, Hive Chicago and Hive Toronto will join us to share real examples of programs that illustrate the impact that learning and making can have on young people during this critical time of the year.

How do these summer programs Demystify the Web for young learners? Explore our learning space at the Mozilla Festival and how you can submit a proposal to share your program strategies and best practices with a community of like-minded peers in a professional learning environment that models hands-on, interest-driven learning for youth and adults alike.

**Comment by KGorr** [comment]
Discourse post: https://discourse.webmaker.org/t/june-2016-community-call-learning-making/891

**Comment by hannahkane** [comment]
Thanks, @kgorr. Handling website updates in https://github.com/mozilla/learning.mozilla.org/issues/1895

**Comment by hannahkane** [comment]
OK, info is live on the site now.

**Comment by KGorr** [comment]
Thanks, @hannahkane!

**Comment by KGorr** [comment]
Draft summary blog post here: https://docs.google.com/document/d/1Fsu4uPDjwsbG7k5j_XBO6LzzXL5o1V5Qt6cNnQxFmvo/edit#

**Comment by KGorr** [comment]
Blog recap: https://blog.webmaker.org/engaging-learners-outside-of-formal-education
