### ISSUE TITLE
pages link to non-functional MozTeach twitter account

### ISSUE THREAD

**Issue by kumar303** [mozilla/learning-networks#411]
I see that [this page](https://learning.mozilla.org/about) and a couple others link to https://twitter.com/MozTeach ('Follow us') which says "account suspended"

**Comment by hannahkane** [comment]
Thanks for reporting this. 

A PR has been filed to fix this, but we haven't rolled it to production yet. Will do so soon. In the meantime, you can find us at https://twitter.com/MozLearn.
