### ISSUE TITLE
July Mozilla Learning Newsletter: Brokering Learning

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#412]
Write and publish July Mozilla Learning Newsletter, which includes:

Community Spotlight
- [x] Determine/contact Community Spotlight Nominee
- [x] Write Community Spotlight Article
- [x] Publish to blog.webmaker.org

Newsletter
- [x] Write newsletter block content (featured activity, events, announcements, spotlight]
- [x] Incorporate Hive community information
- [x] Send content to @stephaniemcv by June 22
- [x] Determine A/B testing plan and distribution dates
- [x] Test and distribute newsletter by Wednesday, July 6
- [x] Post to Medium

CC: @ldecoursy @simonaramkisson @stephaniemcv

**Comment by KGorr** [comment]
@stephaniemcv - thoughts on the send date since it's around a holiday in the U.S.? (I don't know how many folks in our list are U.S. based) I moved it to Tuesday, July 5, but would love your input.

@simonaramkisson - do you have any suggestions for potential community spotlights that would be a great fit with the theme? If so, can you please send their name, contact info, and why they are a great fit to me by the end of the week?

**Comment by KGorr** [comment]
@secretrobotron, @LauraReynal - flagging you in case you still have content you'd like to be included in our July newsletter. Please send content/info my way as you have it available, noting timetable listed above. Thanks!

**Comment by stephaniemcv** [comment]
@KGorr I can run a query and see how many subscribers have country-US, but that won't be an exact number of how many emails are actually US, since we don't require that people tells us that info.

I would suggest a little later in the week for a send, Wed the 6 as the earliest. You can expect US inboxes to be flooded with 4th of July messaging starting the week of June 20th. And since the holiday is a Monday, many people will not be in the office either Friday before or the Tuesday after. 

We probably won't have good timing for testing either because of the holiday.

**Comment by KGorr** [comment]
Thanks @stephaniemcv. I adjusted the timetable based on your recommendation. We can adjust further if you feel running a query on our list would be worth it. If not, let's stick with Wed, June 6 to send this month.

**Comment by lauradereynal** [comment]
Hey @KGorr thanks for the flag ! YES we have content so send for the July newsletter. 
Is there a limit to the number of characters? Or a template we can follow maybe?

**Comment by KGorr** [comment]
@LauraReynal - no specific limits - but keeping each announcement/event blurb to 1-3 sentences is best. I'll forward you the newsletter from last month so you can see how it's laid out and where your content might fit. Also, please include links and photos as applicable. Thank you!

**Comment by KGorr** [comment]
Spotlight article: https://blog.webmaker.org/july-community-spotlight-arkodyuti-saha 

Newsletter to be sent tomorrow!

**Comment by KGorr** [comment]
Newsletter sent and posted to medium here: https://medium.com/@MozLearn/july-2016-community-newsletter-brokering-web-literacy-around-the-world-230be9dfe29c#.x0xmavus9
