### ISSUE TITLE
Email signup not accepting test emails

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/learning-networks#416]
Hey @mmmavis,
I'm running into a similar issue I had before with the MLN form not accepting my test emails. We are currently testing all forms for the CRM integration project. 

![error-mln-email-form](https://cloud.githubusercontent.com/assets/11812272/16315867/3b0aaac6-3941-11e6-8e74-ffcb9124f2ef.jpg)

**Comment by mmmavis** [comment]
sorry i'll get to this soon (hopefully later today!)

**Comment by stephaniemcv** [comment]
Thanks! Also want to note that I'm having the same problem with Webmaker signup (https://id.webmaker.org/signup)

**Comment by mmmavis** [comment]
@cadecairos ^ 😄

**Comment by cadecairos** [comment]
Signup appears to work fine - Keep in mind that that URL (https://id.webmaker.org/signup) _Should not_ work when you navigate directly. it's only supposed to be accessed through registered applications (like via clicking signup on learning.mozilla.org)

**Comment by cadecairos** [comment]
The signup for works, but I think the regular expression checking for email validity wasn't written to accept emails with a "+" in them

**Comment by stephaniemcv** [comment]
Just want to make sure I understand; that since both https://id.webmaker.org/signup and
https://learning.mozilla.org/?signup are direct URLs, email sign ups should NOT work.

**Comment by cadecairos** [comment]
`https://id.webmaker.org/signup` will not work, becuase it's not meant to be navigated to directly. It's the signup form for Thimble, Goggles, and Teach accounts.

`https://learning.mozilla.org/?signup` Is an email list signup (although that `?signup` doesn't seem to open the form on page load). It does work, with the exception for emails containing a "+" - which is probably something that can be fixed.

**Comment by stephaniemcv** [comment]
Ok. Well the only need for the + was just to help with tracking testing of data flow from signups into SalesForce. Which once we took the plus out, MLN and webmaker worked. Thanks for the clarification.
