### ISSUE TITLE
July Mozilla Learning Community Call: Brokering Learning

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#418]
Brokering Web Literacy Community Call is gonna be F-U-N!
Wednesday, July 27 9am PT, 12pm ET, 4pm UTC

[Monthly Community Call Planning Template](https://docs.google.com/document/d/1_IgXfSXHQ-iC56oVdE5i9Yn8QrRjp04ABZMQC-ebHQ0/edit)

Call Curator To-Do List: @simonaramkisson
- [x] Solidify date/time on Mozilla Ed Hub Editorial Calendar
- [x] Book 2-3 speakers (cc Kristina on confirmation emails)
  - [x] [Template logistics email](https://docs.google.com/document/d/1UL-P1D6IsTr7LJFZy5RAoW3B5SxdIvsAwSvgTZDcEN8/edit) to send speakers AFTER they are booked. Highlighted in yellow  are the details you’ll need to change.
- [x] Prepare paragraph summary of call content & speakers (for marketing) DUE 7/6
- [ ] Confirm agenda and add to etherpad (ideally 3 days before event day or sooner)
- [ ] Invite participants
  - [ ] Send a personalized email to your network 1-2 weeks before the call urging those who might be interested in the topic to attend will help increase participation.
  - [ ] Send call [invite templates ](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit)or tweets to your speakers for them to share with their network. (Highlighted in yellow are things that need to be adjusted)

Production To-Do List: @kgorr

Pre Call:
- [x] Set up new G+ event page
- [x] Create new etherpad template
- [x] Send new live stream embed code & landing page copy to programmers
- [x] Add speakers & call details to youtube page/G+ page as soon as it is available
- [x] Write and distribute marketing communications, includes
  - [x] tweets
  - [x] discourse post
  - [x] calendar invites to MLN list serv
  - [x] mofo email invitation (or mattermoz)
  - [x] Ping Hives with [invitee template](https://docs.google.com/document/d/17JgFz7k_eZ7DNsLSAZm3aGOD7Y5BY_2QupN1GHiuIdQ/edit)

Day of Call:
- [x] Hives, @MozLearn, MLN team to tweet reminder
- [x] Broadcast/produce HOA live!

Post Call:
- [x] Send thank you emails to speakers (day-of)
- [x] Follow participants on Twitter from @MozLearn
- [x] Tweet mass thank you to participants
- [x] Compile data for engagement report
- [ ] Write and post call summary blog post

**Comment by KGorr** [comment]
Etherpad: https://public.etherpad-mozilla.org/p/mozcommunitycallJuly16
Live stream embed: 

`<iframe width="420" height="315" src="http://www.youtube.com/embed/Elr7leEmfcs" frameborder="0" allowfullscreen></iframe>`

**Comment by KGorr** [comment]
**Upcoming Call Box content:**
July 27 9am PT, 12pm ET, 4pm UTC
Representing libraries, game education organizations, Mozilla Club leads and Mozilla staff, guests include: Hive Cascadia (Portland, Oregon, USA), Hive Toronto (Canada), Tina Verbo from the Mozilla Philippines community

**Content for below upcoming call box:**
Learning has the potential to make global impact, especially when it starts local. During this month’s call, we’ll discuss how to develop successful learning opportunities that go  beyond local borders. What is the recipe for small and large organizations to move their projects beyond city limits? We’ll discuss developing city-wide learning projects, including successes and challenges, and how they connect to the global Mozilla Learning networks for broader impact.

Have an idea on how to scale a project globally? Ask questions, share ideas and feedback with us live through embedded agenda and chat on the 27th!

@hannahkane - landing page copy, etherpad and live stream embed code are all listed on this ticket for you!

**Comment by KGorr** [comment]
@simonaramkisson - I fleshed out the etherpad with placeholders for speaker content and whatever else you'd like to add.

**Comment by KGorr** [comment]
We've had to change the date of the community call to July 28! Same time.

**Comment by KGorr** [comment]
Discourse post: https://forum.learning.mozilla.org/t/july-2016-community-call-brokering-web-literacy/939

**Comment by hannahkane** [comment]
Is this ticket closeable? (Trying to close out past milestones.)

**Comment by KGorr** [comment]
I'm just waiting to post the community spotlight - waiting until @simonaramkisson gets back from the Canadian holiday tomorrow. It's on my non-github to do list, so I'll close this here to help clean up.
