### ISSUE TITLE
[Testing] Make Your First Webpage module

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning-networks#427]
I've put together a rough draft of a _Make Your First Webpage_ module in response to a recent request on Discourse and some of our experiences with adult learners who want to make relevant sites (but not necessarily on GitHub).

Links below. Let's do bug reports (typos, broken links, missing resources) here and [general feedback on content with the community on Discourse](https://forum.learning.mozilla.org/t/testing-make-your-first-webpage-module/1120).

Thanks in advance for all your help! **I will close this issue on 9/30/16**, so please get your feedback in by then.
- [Session 1 - Tag Tag Revolution remix](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session01-tag-tag-revolution.html#overview)
- [Session 2 - HTML Puzzle Boxes remix](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session02-html-puzzle-boxes.html#overview)
- [Session 3 - Build a Blank Page](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session03-build-a-blank-page.html#overview)
- [Session 4 - #commontags](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session04-common-tags.html#overview)
- [Session 5 - Revise a Résumé](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session05-revise-a-resume.html#overview)
- [Session 6 - Revise a Business Page](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session06-revise-a-business-page.html#overview)
- [Session 7 - Working with a Grid](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session07-working-with-a-grid.html#overview)
- [Session 8 - Make Your First Webpage](http://chadsansing.github.io/curriculum-testing/make-your-first-webpage/session08-make-your-first-webpage.html#overview)

**Comment by mattdigitalme** [comment]
@chadsansing This would be interesting to tag as a potential pathway through some of the Web Lit badges we've all been working on - be good to discuss and see where other pathways may lie as well

**Comment by chadsansing** [comment]
@mattdigitalme, for sure! As you explore the activities, please share your suggestions here. Those of us working on the web lit badges can do the same.

cc @anmechung, @hannahkane

**Comment by jgmac1106** [comment]
The link in session 7 working "today's project" within a grid points to a
dead link to a github page on your repo.

Do we think teaching grid layout would come before building a page? That in
my experience, css layout, is a much bigger task. The first website people
build is rarely a blank page but a remix from a template like the 3 thing I
heart project.

**Comment by chadsansing** [comment]
Thanks, @jgmac1106! Just caught those links, too - bad quotation marks. Should be resolved.

Curious about what others think about the blank-page activity and sequencing of the grid activity.

The idea of the blank page is to draw learners' attention to the shell of a page and to wind up with a project in Thimble they can re-use as boilerplate.

The idea of the grid is to teach some CSS users can apply to their own webpage designs in the last activity. I wonder if teaching and trouble-shooting the grid is easier than teaching and trouble-shooting positioning. #commontags, Revise a Résumé, and Revise a Business Page all give people experience remixing content ahead of the capstone activity here. How might users otherwise approach layout in the last activity if there was a) no grid lesson, b) an alternate layout lesson using positioning, or c) another page to remix, rather than build?

**Comment by KGorr** [comment]
Hi @chadsansing - I put all of my edits in [this google doc.](https://docs.google.com/document/d/1TVyVUgnS73x0fA8nb5fRoc7bBTI56a51WcSirDU4Myc/edit?usp=sharing) Hope it's helpful!

**Comment by chadsansing** [comment]
Thank you very much, @KGorr!

**Comment by chadsansing** [comment]
Thank you for the feedback! Closing this issue, but please feel free to contact me with additional thoughts and suggestions.
