### ISSUE TITLE
November Mozilla Learning Newsletter

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#428]
Write and publish October Mozilla Learning Newsletter, which includes:

Community Spotlight
- [x] Determine/contact Community Spotlight Nominee
- [x] Write Community Spotlight Article
- [x] Publish to blog.webmaker.org

Newsletter
- [x] Write newsletter block content (featured activity, events, announcements, spotlight]
- [x] Incorporate Hive community/Science community information
- [x] Send content to @stephaniemcv by Friday, Oct 21
- [ ] Determine A/B testing plan and distribution dates
- [x] Test and distribute newsletter by Friday, November 4
- [x] Post to Medium

cc: @ldecoursy @stephaniemcv

**Comment by hannahkane** [comment]
Hey @KGorr - any chance we could include a CTA for helping to localize curricular content in the newsletter? @gideonthomas and I are trying to get a new campaign going, this one around the "Offline Icebreakers" module.

**Comment by KGorr** [comment]
@hannahkane - absolutely! I just need the relevant/important info for a short 2-3 sentence blurb no later than Oct 20.

**Comment by hannahkane** [comment]
thanks, @KGorr. We'll have something for you by then!

**Comment by gideonthomas** [comment]
Hi @KGorr, I believe we settled on:

```
Help make valuable educational resources available to people in your community. Join the campaign to localize the Offline Icebreakers module of our Web Literacy Curriculum. See <link> for more information.
```

Is it possible for us to provide the link after Oct 20th? We aren't really done with the content on it. I can try to provide the link to it by tomorrow but the page itself will not be completed. Thoughts?

**Comment by KGorr** [comment]
@gideonthomas - if you can provide the link by Friday, that would be great. The newsletter isn't published until Nov 4, so there is no worries about it being shared before then if it's not ready. If you think it won't be ready by that date, let me know and we can figure out something else.

**Comment by gideonthomas** [comment]
Perfect, I think I can give you the link by Friday

**Comment by gideonthomas** [comment]
@KGorr the link is `https://mozilla.github.io/curriculum-localization`, it should be active soon

**Comment by KGorr** [comment]
Newsletter content ready to go @stephaniemcv: https://docs.google.com/document/d/1OQx1F8nq4Xog4-WUF3JCSenlR9ARJIrnYstOhVKam70/edit#heading=h.ugluyadq8ykl

**Comment by KGorr** [comment]
Community Spotlight published here: https://learning.mozilla.org/blog/community-spotlight-andrew-brennan

**Comment by KGorr** [comment]
Medium post is here: https://medium.com/@MozLearn/november-2016-community-newsletter-youth-leadership-9e01e137cbe8#.yowzcqng0
