### ISSUE TITLE
Oct 20: Draft curriculum localization campaign blurb for Nov newsletter

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning-networks#429]
2-3 sentences

I'm imagining something like, "Help make valuable educational resources available to people in your community. Join the campaign to localize the Offline Icebreakers module of our Web Literacy Curriculum. See `<link>` for more information."

Linked page needs to be created. Will file a separate ticket for that.

**Comment by gideonthomas** [comment]
I think this looks great (also not mentioning incentives here since we're unclear on that)!
~~What will the linked page contain?~~ (nvm just saw the issue filed)

**Comment by gideonthomas** [comment]
This is done, just need to add the link once it has been created
