### ISSUE TITLE
January Mozilla Learning Newsletter

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#432]
Write and publish December Mozilla Learning Newsletter, which includes:

Community Spotlight

- [x] Determine/contact Community Spotlight Nominee (Story Engine Profiles)
- [x] Write Community Spotlight Article

Newsletter

- [x] Write newsletter block content (featured activity, events, announcements, spotlight]
- [x] Incorporate MLN community information (Pulse)
- [x] Send content to @stephaniemcv by Thursday, Jan 5
- [ ] Determine A/B testing plan and distribution dates
- [x] Test and distribute newsletter by Wednesday January 11

cc: @ldecoursy

**Comment by KGorr** [comment]
@stephaniemcv - Does this work with any PTO you may be taking and/or the MoFo email calendar?

**Comment by stephaniemcv** [comment]
I think the 1/11 would be a better date for a send. Also, I recognize that most of you are probably taking next week off so would more time wrangling content help? Say get it to me by 1/5? I got Will to help out now. ;-)

**Comment by KGorr** [comment]
That works for me! Thanks, @stephaniemcv.
