### ISSUE TITLE
Update Desk.com MLN Macros

### ISSUE THREAD

**Issue by KGorr** [mozilla/learning-networks#433]
Desk.com macros used for incoming emails to teachtheweb@mozillafoundtion.org need to be updated for 2017. 

**Current MLN Macro Titles:**
Mozilla Clubs - Learn more - needs updated
Apply to be a Club Captain - needs updated
Club Captain Pledge - needs removed
Mozilla & Firefox Clubs - needs removed
Want to Contribute - needs updated
Event - needs updated
Interested in Mozilla - needs updated
SPAM - OK as is
*MLN - Confirm Subscription - OK as is 

**Requests for new Macros:**
Localized Newsletter Content
Campus Club vs Mozilla Club

Macro content updates (and text for new macros) are highlighted yellow & labeled via comments in the [MLN Support FAQs](https://docs.google.com/document/d/18FUPmsHV30XpMPPMz-fY2FzLUT5UFdoQEPcOqYpmvU8/edit#). 

CC: 
@jvallera - Do any Club comms need to be updated before macros are set (now or in near future)? We can discuss during our 12/16 meeting
@stephaniemcv - you graciously helped us initially set these up. Are you the right person to help update them?
@ldecoursy - general FYI 😄

**Comment by stephaniemcv** [comment]
Yup! You finalize the content, I'll get it loaded into Desk.

**Comment by KGorr** [comment]
Thanks, @stephaniemcv! I'll ping you as soon as I get the final OK from @jvallera on the Clubs content.

**Comment by jvallera** [comment]
I suggested one edit @KGorr for Clubs - see doc. Otherwise, all looks good.

**Comment by KGorr** [comment]
Thanks @jvallera! @stephaniemcv - these should all be good to go for updating/adding macros. Thank you!

**Comment by KGorr** [comment]
@stephaniemcv - I just added an additional macro in the FAQ document. You can call it "Hive Inquiry." Is there any way we can get these updated by the end of the month (before my contract expires)? Thanks!

**Comment by KGorr** [comment]
@stephaniemcv - When @annmarie123 & I were running through desk.com, I also realized that some of the macros auto populate me as the assignee. Can you change those to Ann Marie? Thank you!

**Comment by stephaniemcv** [comment]
I updated all the Teach and Maker Party macros from a specific assignee to (Current User). So anyone who uses the macros will be automatically assigned.
