### ISSUE TITLE
Update Guides Template for Mozilla Clubs

### ISSUE THREAD

**Issue by Carotejada** [mozilla/learning-networks#434]
Hola! We are updating our channels with the new banding, and need some help changing the logo of this [template](http://mozilla.github.io/learning-networks/clubs/marketing-your-mozilla-club-writing-a-blog/).

Here is the [logo](https://drive.google.com/drive/folders/0B2irLVDJivhLMTBnbzJTU09tT0k?usp=sharing) 

cc @flukeout @jvallera

**Comment by hannahkane** [comment]
cc @xmatthewx
