### ISSUE TITLE
Thimble template for Mozilla Club's logo

### ISSUE THREAD

**Issue by Carotejada** [mozilla/learning-networks#435]
In collaboration with @barrosgeraldo, we are creating Thimble templates to help captains remix their Club's logo. We also added a brief tutorial. 

[Without background image](https://thimbleprojects.org/carotejada/272333/)
[With image](https://thimbleprojects.org/carotejada/272301/)

Thoughts? @hannahkane @flukeout 

cc @jvallera @amirad

**Comment by jvallera** [comment]
This is fantastic! Thanks for the update. Should we add a license to it? The way we have licenses on our curriculum and activities?

**Comment by Carotejada** [comment]
@jvallera agreed! we'll add it at the bottom.
