### ISSUE TITLE
Update certificate for Mozilla Clubs

### ISSUE THREAD

**Issue by Carotejada** [mozilla/learning-networks#437]
We also need to update this certificate with the [new branding](https://drive.google.com/drive/folders/0B2irLVDJivhLMTBnbzJTU09tT0k?usp=sharing). I just changed the logo, but wondering if it needs a redesign.
 
[Training_certificate.pdf](https://github.com/mozilla/learning-networks/files/1005844/Training_certificate.pdf)

Also, I found this post on a Discourse thread. A community member created this Repo "[PDF Certificate Generator with a csv file](PDF Certificate Generator with a csv file ) ". Maybe we can use it... but not sure! My GH skills are not that good (yet).

cc @jvallera @hannahkane @flukeout

**Comment by hannahkane** [comment]
cc @xmatthewx

**Comment by jvallera** [comment]
Hi @Carotejada can you share link to discourse thread? or repo?

**Comment by Carotejada** [comment]
Oh! Sorry: https://forum.learning.mozilla.org/t/certificates-for-members/1033/42?u=carot
