### ISSUE TITLE
Suggestion for using the repo wiki

### ISSUE THREAD

**Issue by ghost** [mozilla/learning-networks#438]
Maybe you can use the repo wiki to outline the different parts of the Mozilla Learning Network initiatives.

**Comment by hannahkane** [comment]
Hi @KipOmaha - thanks for sharing your idea. Others in this repo might have more to say, but I just wanted to let you know that perhaps the best way to learn about the Learning Network's initiatives is to check out https://learning.mozilla.org.

**Comment by ghost** [comment]
True, I just like browsing through repos, lol...I guess it would be for people who like to poke around in repositories on GitHub. I was thinking of a wiki page of links is all.
