### ISSUE TITLE
Update "Club Audit" with a curriculum audit

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#44]
This issue has been migrated from mozilla/teach.webmaker.org#93.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Wed Feb 25 2015 and had the following description:

> Moving from the curriculum repo:
> 
> We have this audit of orgs with club-like activities. It notes that certain orgs have curricula, we should be auditing to see how we might be able to use what already exists. Need to check for licensing, remixability and alignment to Web Lit Map, especially for competencies that don't have a lot of materials to pull from.
> 
> https://docs.google.com/a/zythepsary.com/spreadsheets/d/1JvIm1nAVBqtbOTwEpwzc_WyGL11Sx3QG5zSGUy1SQk8/edit#gid=0
> 
> (note: back in Textbook phase, Kat and I had worked on listing curriculum from both inside and outside webmaker that covered competencies. Might be worth cross referencing both in the audit as well as for future curriculum production. https://teach.etherpad.mozilla.org/best-in-show )

On Wed Feb 25 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> Related: https://github.com/mozilla/webmaker-curriculum/issues/85

On Tue Mar 31 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> based on web lit map http://myfuture.net/essentials

**Comment by thornet** [comment]
Is this ticket still needed?

(ticket clean-up day!)
