### ISSUE TITLE
Rio: localize initial report about Rio de Janeiro LAN houses

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#46]
This issue has been migrated from mozilla/teach.webmaker.org#95.

It was originally written by [soapdog](https://api.github.com/users/soapdog) on Wed Feb 25 2015 and had the following description:

> Localize the report made by Laura into Brazilian Portuguese. I have InDesign here and can do it once I have access to the original file. 

On Wed Feb 25 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Hi **@****soapdog** Can you clarify, are you referring to the field research from Kenya? https://blog.mozilla.org/m4d/2015/02/03/webmakers-field-research-report-from-kenya/
> 
> If so, would you mind filing in the webmaker.org repo? https://github.com/mozilla/webmaker.org/issues
> 
> Thanks!

On Wed Feb 25 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Hi **@****ldecoursy**. I am referring to the initial report made about Rio de Janeiro, not the one about Kenya. Thanks a lot for sending me the Kenya related info though. That report is great.

On Mon Mar 02 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Closing this here - refiled in Research repo https://github.com/MozillaFoundation/research/issues/17

**Comment by soapdog** [comment]
This was a quick translation. It could be improved but it works.

Localized PDF: https://www.dropbox.com/s/s2x9ksx1yo955rr/Rio_pt-BR.pdf?dl=0

The changes have been saved to the original localized InDesign file shared with @LauraReynal
