### ISSUE TITLE
Rio: localize the web literacy map into pt_BR

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#47]
This issue has been migrated from mozilla/teach.webmaker.org#96.

It was originally written by [soapdog](https://api.github.com/users/soapdog) on Thu Feb 26 2015 and had the following description:

> Most of our audience in the Rio LAN houses project does not speak English. All resources made available to them needs to be in Brazilian Portuguese.
> 
> One special resource that will aid self-assessment is the Web Literacy Map. Right now the map is in that hybrid state where some strings are in Portuguese but most of it is still in English.
> 
> ![recursos 2015-02-26 10-05-34](https://cloud.githubusercontent.com/assets/23247/6392413/19024cbe-bd9f-11e4-9465-3cbfa4cae49f.png)

On Thu Feb 26 2015, [dajbelshaw](https://api.github.com/users/dajbelshaw) commented:

> Hi **@****soapdog**! Just flagging that this is v1.1 of the Web Literacy Map and v1.5 will be ready by the end of March. The idea is to include localisation as part of that push. :)
> 
> https://github.com/mozilla/webliteracymap/
> 
> / cc **@****hannahkane** 

On Thu Feb 26 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Perfect **@****dajbelshaw**! I will help on that repo. Thanks a lot.

On Thu Feb 26 2015, [dajbelshaw](https://api.github.com/users/dajbelshaw) commented:

> I think the translation/localisation itself will happen on Transifex, but the English v1.5 will appear on the above repo first.
> 
> We'd love your input on the community calls if you ever get time: https://wiki.mozilla.org/Webmaker/WebLiteracyMap/v1.5
> 
> (there's actually a call at 4pm UTC [today](https://teach.etherpad.mozilla.org/weblitmap-26feb15)!)

On Tue Mar 31 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> **@****dajbelshaw** is it on Transifex already? If it is not, then, is it ok to translate and do a pull request?

**Comment by thornet** [comment]
@soapdog the new version of the map is live here: https://teach.mozilla.org/teach-like-mozilla/web-literacy/

cc @hannahkane who may know if and when the live website content will be available to translate in Transifex.

**Comment by soapdog** [comment]
Will localize shortly :+1:

**Comment by mofodevops** [comment]
Ignore this test message

**Comment by ldecoursy** [comment]
Closing this, will readdress following launch of Web Literacy Map 2.0
