### ISSUE TITLE
Document all mailing lists Learning Networks team has access to

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#51]
This issue has been migrated from mozilla/teach.webmaker.org#130.

It was originally written by [ldecoursy](https://api.github.com/users/ldecoursy) on Wed Mar 04 2015 and had the following description:

> RACI
> - Owner: **@****amirad**
> - Decision Maker: **@****amirad** **@****chrislarry33**
> - Consulted: Kelli, **@****ldecoursy** **@****simonaramkisson** **@****LucyeoH** 
> 
> We need to compile a list of all the mailing lists we have full access to, and include how many people are on each as a baseline.
> 
> Pull from BSD, Hives, anywhere else?
> Also to include list of contributors referenced here: https://github.com/mozilla/teach.webmaker.org/issues/122

On Wed Mar 18 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Tracking here: https://teach.etherpad.mozilla.org/retain4k
> 
> **@****Saallen** can you add #'s from MozFest lists? 

On Thu Mar 19 2015, [Saallen](https://api.github.com/users/Saallen) commented:

> **@****ldecoursy** added! I added 2013 numbers too but not sure we can still access these emails due to data storage guidelines as set out by **@****adamlofting**  on the mana. Can you confirm **@****adamlofting** 

On Thu Mar 19 2015, [adamlofting](https://api.github.com/users/adamlofting) commented:

> I made a note in the etherpad. Have we stayed in touch with these people since then? If not, a "random" email two years later will have poor response rates which would have a negative impact on our general mailing stats (deliverability rate etc).

On Thu Mar 19 2015, [Saallen](https://api.github.com/users/Saallen) commented:

> Thanks **@****adamlofting** I would not of had emailed 2013 folks since 2013. But I have pinged the 2014 list already since MozFest.

On Thu Mar 19 2015, [adamlofting](https://api.github.com/users/adamlofting) commented:

> I'd also expect there's some overlap in these lists :smile: 

On Thu Mar 19 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Agree - let's just add 2014 for now. Thanks **@****Saallen**

**Comment by ldecoursy** [comment]
Closing this - all lists have been migrated to Exact Target.
