### ISSUE TITLE
Outline and Map Peaks for Mobilizing Clubs

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#54]
This issue has been migrated from mozilla/teach.webmaker.org#174.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Mon Mar 09 2015 and had the following description:

> These questions stood out to me **@****ldecoursy** when I was thinking over the processes needed for building out the roadmap headers for Mobilizing section within [Clubs Roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1FZk_0-zAcjF0nc7fa3EK7QfVVDgRAhMoOuCoxsVR4Ts/edit#gid=0)
> What counts as a peak in the yearly arc of the Clubs for Mobilization?
> Are we creating these peaks or are they naturally within the calendar of community events ?
> What tools kits are needed for RC for yielding peaks outcomes?
> 
> Are they relevant or points already decided upon?

On Mon Mar 09 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> I think our campaigns and key events mark the peaks here. Plus anything from your events calendar that we think make sense. 

On Mon Mar 09 2015, [Saallen](https://api.github.com/users/Saallen) commented:

> I will add events into the roadmap steming from our events calendar which we can then review on Wed :smile:

**Comment by ldecoursy** [comment]
Closing based on more recent work around Clubs workflow.
