### ISSUE TITLE
Create and link to "How to adapt this to your learners" resource

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#59]
This issue has been migrated from mozilla/teach.webmaker.org#201.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Tue Mar 10 2015 and had the following description:

On Wed Mar 18 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> **@****jvallera** if you have ideas here after your April 1st meetup, definitely throw some in!! 

On Wed Mar 18 2015, [jvallera](https://api.github.com/users/jvallera) commented:

> Will do. Thanks.

On Fri Apr 17 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> holy! Just found **@****smithisgeneric**'s resource on adding Appmaking. This is good to pull from/think about for this ticket: https://karenlouisesmith.makes.org/thimble/LTk0ODk1ODcy/align-with-appmaking

**Comment by LauraHilliger** [comment]
http://laurahilliger.gitbooks.io/teach-like-mozilla/content/teaching_learning/en/remixing-context.html
