### ISSUE TITLE
Provide expectations and resources for RCs during Maker Party

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#8]
This issue has been migrated from mozilla/teach.webmaker.org#18.

It was originally written by [Saallen](https://api.github.com/users/Saallen) on Thu Feb 12 2015 and had the following description:

> ### RACI
> - Phase: 
> - Owner: 
> - Decision Maker: 
> - Design Lead: NA 
> - Dev Lead: NA
> - Quality: 
> ### Deliverables
> - [ ] List of expectations for our RCs during and post-Maker Party 
> - [ ] Resources to support RCs during and post Maker Party (e.g. "How to see potential in MP event hosts as CC's," "How to use the Self, Us, Now model to invigorate new recruits," and "How to expand clubs within regions")

On Mon Mar 02 2015, [thornet](https://api.github.com/users/thornet) commented:

> Proposing **@****amirad** takes this one as part of her Maker Party planning

**Comment by ldecoursy** [comment]
@thornet and @amirad What are our best next steps here? How can we re-purpose current resources or best prep RCs to participate/lead in MP this year?

**Comment by amirad** [comment]
@thornet can we lead with this in one of the next RC calls?
I think expectation for RC's will be to throw a MP with club leaders or new potential club leaders or just new people. This can be at any time of year or align with campaign, though would be nice if it was in July

**Comment by ldecoursy** [comment]
@amirad @thornet Should this be something we dig into specifically at Whistler, or might it be too late?

**Comment by amirad** [comment]
It might be too late. I thought we were going to do it in the last RC call but we might have run out of time? Can we add it to the next call?

**Comment by amirad** [comment]
We've discussed this in the call and with RCs. Expectation is for each club or RC to run a Maker Party.
