### ISSUE TITLE
15 RCs are onboarded

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#90]
This issue has been migrated from mozilla/teach.webmaker.org#286.

It was originally written by [thornet](https://api.github.com/users/thornet) on Mon Mar 16 2015 and had the following description:

> - [ ] Kick off call -- scheduled for May 5
> - [ ] Regular comms (#19)
> - [ ] Assigned clubs to support

**Comment by hannahkane** [comment]
Can we close this?
