### ISSUE TITLE
Recruit Q2 testers

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#91]
This issue has been migrated from mozilla/teach.webmaker.org#288.

It was originally written by [thornet](https://api.github.com/users/thornet) on Mon Mar 16 2015 and had the following description:

> Goal: 200 cities 
> 
> Path includes: 
> - [ ] leverage partners
> - [ ] recruit from Q1 testers
> - [ ] RCs reach out
> - [ ] staff leads
> - [ ] marketing
> - [ ] emerging Hives (@simona)

On Mon Mar 30 2015, [thornet](https://api.github.com/users/thornet) commented:

> Next steps: 
> - Prepare pipeline of partners & eager clubbers with **@****amirad** **@****ldecoursy** **@****simonaramkisson** 
> - Customize Q2 asks depending on recipient

**Comment by hannahkane** [comment]
Removing from May 8 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?
