### ISSUE TITLE
Rio: Prepare invite list & agenda for LAN house kick-off meeting

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#93]
This issue has been migrated from mozilla/teach.webmaker.org#306.

It was originally written by [thornet](https://api.github.com/users/thornet) on Tue Mar 17 2015 and had the following description:

> We should do an in-person kickoff with all the participating LAN house owners.
> 
> Include Graci in agenda development and meeting. 

On Fri Mar 27 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Agreed! :D Will talk to ITS and Mario so that we can set a date.

On Tue Mar 31 2015, [soapdog](https://api.github.com/users/soapdog) commented:

> Our initial desired LAN House set is:
> - 1 - Marios LAN House - Abolição
> - 4 - Jacsandi LAN House - Realengo
> - 6 - Naigel LAN House - Santa Cruz
> - 7 - Alessandro LAN House - Engenho Novo
> - 9 - Marco LAN House - Colegio
> - 10 - Otacilio & Loiane LAN House - Sepetiba
> 
> I've sent an email to Mario and Constance and we're starting to organize this meeting. It will require some back and forth until we find a date where everyone can meet. We must remember that these LAN Houses are very far away from each other and getting around in Rio is difficult. I will update this task as we move along.
> 
> PS: The numbers are from the Rio Report.

**Comment by soapdog** [comment]
We're tentatively scheduling the meeting to 15th of May. We already have our invitee list and place.

**Comment by amirad** [comment]
Outdated ticket
