### ISSUE TITLE
Add Media release form to clubs tip page

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#94]
This issue has been migrated from mozilla/teach.webmaker.org#313.

It was originally written by [LauraHilliger](https://api.github.com/users/LauraHilliger) on Wed Mar 18 2015 and had the following description:

> we need to have a quick blurb + link on media release forms for clubs aimed at youth. Meredith from Mouse suggested this form from the NYCDOE:
> 
> http://schools.nyc.gov/NR/rdonlyres/2E974D18-2CA2-445D-8A0F-8AAE9B4EF238/88120/consent_form_revised35.pdf
> 
> **@****amirad** is it too late to add that to the Clubs tips content?

On Thu Mar 19 2015, [amirad](https://api.github.com/users/amirad) commented:

> Hm not sure! **@****hannahkane** thoughts? 

On Thu Mar 19 2015, [chrislarry33](https://api.github.com/users/chrislarry33) commented:

> This would be great to have. Might not be ready for launch, shouldn't be a blocker. Basically has to involve Angela and legal. Can someone start an Ops bug on this? If/when we have it I agree it will be a key asset.

On Thu Mar 19 2015, [hannahkane](https://api.github.com/users/hannahkane) commented:

> We can add it whenever it's ready.

On Mon Mar 30 2015, [LauraHilliger](https://api.github.com/users/LauraHilliger) commented:

> Heya – found this from Hive Toronto: https://docs.google.com/a/zythepsary.com/document/d/1aO0rEdV5QpMGoRDFJupf3xRtEWO7ByM4x0h9615xXAk/edit
> 
> sounds like it was written by legal, so we might just do a slight remix. Closing https://github.com/MozillaFoundation/plan/issues/398 (please reopen if you think we need a new one for Clubs)

On Mon Mar 30 2015, [ldecoursy](https://api.github.com/users/ldecoursy) commented:

> Also **@****Saallen** may have one from MozFest?

On Tue Mar 31 2015, [Saallen](https://api.github.com/users/Saallen) commented:

> This is the form I use for MozFest -https://drive.google.com/a/mozilla.com/file/d/0B_B9-Ny1xBaRYU4tYUZEUlNKUFU/view?usp=sharing

**Comment by ldecoursy** [comment]
@amirad Is this still something we need or should create as part of RC or CC kit?

**Comment by amirad** [comment]
Yes, we should create this as a resources. But it's not priority for now.

**Comment by ldecoursy** [comment]
Adding to a future milestone for now (post MozFest) so we can revisit. Thanks!

**Comment by ldecoursy** [comment]
@amirad @Carotejada Is this covered in any of the current/upcoming Club guides?

**Comment by amirad** [comment]
Here's the doc that we worked on with Abigail. https://docs.google.com/document/d/1VFPE1N2RcvtdF1FHhl6sRA4-oAkau00hD3akZNicA_w/edit?usp=sharing

**Comment by ldecoursy** [comment]
This doesn't include any mention of photos/videos - do you know if that's addressed in a separate doc? Or maybe can be added to this one (since would need parental consent for that, makes sense to have one form vs. several)

**Comment by amirad** [comment]
I added it to the document.
