### ISSUE TITLE
What's happening in the Mozilla Learning team communities shareout

### ISSUE THREAD

**Issue by toolness** [mozilla/learning-networks#97]
This issue has been migrated from mozilla/teach.webmaker.org#318.

It was originally written by [amirad](https://api.github.com/users/amirad) on Wed Mar 18 2015 and had the following description:

> Turn community stories pilot into blog post and email by April 15th.

On Mon Mar 30 2015, [thornet](https://api.github.com/users/thornet) commented:

> Moving to a heatbeat milestone.

**Comment by hannahkane** [comment]
Removing from April 24 milestone, since that's passed. Can we close this or add to an upcoming heartbeat?
